### ISSUE TITLE
Issues regarding duplicate symbols

### ISSUE THREAD

**Issue by alok1upadhyay** [iZettle/sdk-ios#1]
Hi,

we are using latest iZettle library in our app, however it is using internally two file Discount and LoadingView. Our app also have two files with same name Discount and LoadingView.I have to change my file names in order to successfully compile and run.can you please prefix your class names with IZettle, for example IZettlediscount and IZettleLoadingView..

Thanks, 
Alok

**Comment by bartg** [comment]
+1 For this, I dont have problems yet, but they arised when I have tried to use SumUp and zbar (well, basically this is not possible). Will be good to avoid problems here.

Prefix maybe could be smaller like IZLoadingView etc?

**Comment by mattiasjahnke** [comment]
We're prefixing classes every release, sorry for the inconvenience.

@alok1upadhyay The Discount class should no longer be part of the distribution, are you sure you're using the latest binaries?

**Comment by alok1upadhyay** [comment]
Thanks, for the response.

we are using latest SDK in iPhone and iPad app. LoadingView class caused problem definitely.I have resolved it at our end.

One question : i am using a sample account (externaldemo@izettle.com, may be others also using ). I  am getting error "Your session was interrupted. Please sign in again." is it due to some where else the same login credentials being used. I am trying to make a real time payment, using iZettle bluetooth card reader.

**Comment by pushpak** [comment]
We also had the same problem with `LoginController`. I reported it few weeks back not sure if its fixed in the latest version.

**Comment by mattiasjahnke** [comment]
@alok1upadhyay We'll address ```LoadingView``` in the next release. Regarding your other issue; are you still experiencing this problem?

@pushpak ```LoginController``` is prefixed in v1.0

**Comment by alok1upadhyay** [comment]
@matt No, it looks like it have disappeared automatically, today i see one interesting pop up telling me about update..(it was something related to firmware?), when i connected bluetooth card reader.
Bottomline : issue fix , i am not experiencing any more.

**Comment by alok1upadhyay** [comment]
@mattiasjahnke can you please help or comment on :

Earlier I was doing some testing with the iPhone app and iZettle and the reader was connected to my phone via Bluetooth but everytime I touched 'Pay' and 'Credit Card' it said no device connected.  I then removed the device and re-paired it, but it still had the issue.

After a 2nd time of removing the device and re-pairing it worked.  Any ideas?

**Comment by mattiasjahnke** [comment]
@alok1upadhyay Please open up a new issue where we can discuss your problem (not related to duplicate symbols).

**Comment by alok1upadhyay** [comment]
Thanks for the comment, i am opening new issue.
