### ISSUE TITLE
Return details of izettle account after successful payment

### ISSUE THREAD

**Issue by skiddle** [iZettle/sdk-ios#10]
Our use case will have one main izettle login (which we can restrict enforceUserAccount) however in some cases, it may be more suitable for the user to login using their own account. This will make a big difference to us, in the flow of payments and reconcilliation

We would like to be returned the user account which the payment was made through, upon successful charge. We can then use this to ensure the payments are tagged against the correct account

**Comment by mattiasjahnke** [comment]
Please refer to #16
