### ISSUE TITLE
Connecting Izettle checkout/payment with Vend POS

### ISSUE THREAD

**Issue by VedraneSmokes** [iZettle/sdk-ios#102]
![20161212_115011](https://cloud.githubusercontent.com/assets/24292715/21097911/2cfe5128-c067-11e6-9caa-29cde62aa7f8.jpg)
![20161130_153351](https://cloud.githubusercontent.com/assets/24292715/21097915/302d4642-c067-11e6-8a52-d7d9f275de93.jpg)

Hi. 
We are trying to switch from iZettle POS to Vend POS but we still want iZettle payment. iZettle payment has been added to Vend app as payment solution but once we log in we get error message saying that iZettle cash register is already connected to iZettle account and we cannot use it through Vend. We have contacted Izettle technical department and were told to write here. 
I hope you can help us make it work. 
Thank you. 

Vedran / Black Box Sweden AB / info@esmokes.se

**Comment by jensutbult** [comment]
We don't support cash register enabled accounts with the SDK. If you wish to switch to Vend POS and keep using iZettle for payments you need to disable the cash register functionality associated with your account. Contact our support and I'm sure they will help you.
