### ISSUE TITLE
New iZettle reader not supported?

### ISSUE THREAD

**Issue by hughconway** [iZettle/sdk-ios#106]
I have purchased the new iZettle reader (https://www.izettle.com/gb/register?selected_reader=7) to use with my POS app (from Ebizmarts: https://pos.ebizmarts.com/) but it does not appear to be supported.  I contacted the developer who said that is not yet part of the SDK.  When will it be supported by the SDK?

**Comment by mattiasjahnke** [comment]
Hi,

Our SDK supports all readers that the iZettle app supports, including the new iZettle Reader.

SDK version 1.3, which was released July 13th, added support for the new reader.

The POS developer must update their app to use the latest iZettle SDK.
