### ISSUE TITLE
Test / simulation mode ?

### ISSUE THREAD

**Issue by zabojad** [iZettle/sdk-ios#107]
Hi there !

I'm implementing the IZettle SDK in my application and I was wondering if there is any test or simulation mode that would allow to perform calls to `[[iZettleSDK shared] chargeAmount ...` without really charging the credit card I use.

Is there such setting somewhere (user account ? card reader setting ?).

Thanks in advance !

**Comment by TomasPro** [comment]
Hi Zabojad,

Not exactly. You will be developing in production environment and as such any authorisation attempt (if valid) will actually be sent for online approval to the issuer of your card.

However, to avoid actual charges to your card during development we have special accounts. When payment is attempted with them and is actually approved, our systems will automatically revert the transaction. As a result, you bank may temporarily show a pending ('reserved') charge for each successful transaction attempt. The charge will however never be taken and will disappear within hours or days (depending on your issuer).

You receive details for your 'test' account when registering for API key here: https://developer.izettle.com
