### ISSUE TITLE
Payments stuck...

### ISSUE THREAD

**Issue by zabojad** [iZettle/sdk-ios#108]
Hi !

I'm implementing the iZettle SDK in my app and tried my first payments.

I haven't received an API key yet (I've applied already on https://www.izettle.com/fr/developer) so I use the one from the demo: `demo-app-izorn`.

When I try to charge myself of 1.0 € (call to `[[iZettleSDK shared] chargeAmount:...`), here is what happens:
1- the iZettle waits for my card,
2 - I insert it
3 - the iZettle asks me for the card code,
4 - I type it,
5- the iZettle then gets stuck on "En attente de montant" which means in French "awaiting amount".

I don't get it... What am I missing?

**Comment by zabojad** [comment]
PS: I've checked my iZettle account online and there is no trace of those payments.

**Comment by mattdouhan** [comment]
I think you need to post your entire code snippet for the charge please so that someone can look and try help

**Comment by mattiasjahnke** [comment]
Hi @zabojad you might have encountered a bug that we've fixed in the latest version of the SDK (1.4). Please have another go using that version

**Comment by Sajjon** [comment]
@zabojad Hi, Alex from iZettle here. We have just release a new version of the SDK, version `1.4.1` ( https://github.com/iZettle/sdk-ios/releases/tag/1.4.1 ), it is available using cocoapods as well.

Can you please try to use that version and verify that it solves your issue? Please feedback to me when you have verified. Thanks!

**Comment by arikis** [comment]
Closing due to the inactivity. The issue described here is fixed in the latest versions of SDK.
