### ISSUE TITLE
armv7s library support

### ISSUE THREAD

**Issue by Hless** [iZettle/sdk-ios#11]
For our app we need to compile for armv7s. However the iZettle SDK doesn't seem to have support for this architecture. Currently, we cannot compile for armv7 or arm64. Is it possible to include armv7s support into the library?

Compiler throws the following error:
```
ld: file is universal (4 slices) but does not contain a(n) armv7s slice:
<projectpath>/Pods/iZettleSDK/iZettleSDK/iZettleSDK.framework/iZettleSDK file
'<projectpath>/Pods/iZettleSDK/iZettleSDK/iZettleSDK.framework/iZettleSDK' for architecture armv7s
```

**Comment by mansbernhardt** [comment]
We are using the architectures recommended by Apple. Apparently Apple don’t think adding armv7s has much benefit. From apple dev forums:

*The reason for including armv7s would be marginal backward compatibility. But the general differences between armv7 and armv7s instruction sets are minor. So if you choose not to include armv7s, the targeted armv7 machine code still runs fine on 32 bit A6 devices, and hardly one will notice performance gap.*

-- Zhou Yang

**Comment by Hless** [comment]
Ok. I suppose that sounds reasonable.

Eventually, it appeared something was not quite right in our project. We've got it to work by checking our other dependencies (we're using CocoaPods), and making sure those would work with armv7.
