### ISSUE TITLE
Possible to obtain API key for webapp

### ISSUE THREAD

**Issue by Crowdedlight** [iZettle/sdk-ios#114]
Is it possible to obtain an API key for usage of the OAuth2 in an webapp. 

I don't have an bundle ID, as it is an webapp, so can't use the normal form. Should I just use the normal form and write nothing in the bundle id? 

I wrote to your support that told me to write an issue here.

**Comment by mattiasjahnke** [comment]
Hi @Crowdedlight 

This SDK is a framework to be integrated in an iOS application. If you have a webapp, you'll have to write an ios app wrapping our SDK or your webapp.

We used to have a URL-scheme but that has been deprecated.

**Comment by Crowdedlight** [comment]
Ahh alright. I didn't find that point clear in the documentation. I thought it was still accessable though https://oauth.izettle.net/authorize as stated in: https://github.com/iZettle/api-documentation/blob/master/authorization.adoc
