### ISSUE TITLE
SDK crashes after updating to iOS 10.x.  -[__NSDate length]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by GJNilsen** [iZettle/sdk-ios#116]
We are controlling a HomeKit appliance in an app using the iZettle SDK. On iOS 9, everything works, but the HomeKit appliance has some mysterious behaviour, not reacting correctly and so on. So after updating to iOS 10, every time the HomeKit appliance is turned on or off, the app crashes. And ONLY when the iZettle libraries are added. They do not even have to be imported, as long as they are added to the app, every attempt to write values to the HomeKit appliance results in a crash.

2017-02-08 10:17:47.804825 POS[602:171994] -[__NSDate length]: unrecognized selector sent to instance 0x1740169c0

iZettlePayments`-[NSDictionary(Fractionized) dateForKey:]:
    0x100973d88 <+0>:   stp    x22, x21, [sp, #-48]!
    0x100973d8c <+4>:   stp    x20, x19, [sp, #16]
    0x100973d90 <+8>:   stp    x29, x30, [sp, #32]
    0x100973d94 <+12>:  add    x29, sp, #32              ; =32 
    0x100973d98 <+16>:  mov    x19, x0
    0x100973d9c <+20>:  nop    
    0x100973da0 <+24>:  ldr    x20, #861056              ; (void *)0x00000001ad8966b8: NSDateFormatter
    0x100973da4 <+28>:  nop    
    0x100973da8 <+32>:  ldr    x21, #851248              ; "izDateFormatterUsingISO8601"
    0x100973dac <+36>:  mov    x0, x2
    0x100973db0 <+40>:  bl     0x1009e9b54               ; symbol stub for: objc_retain
    0x100973db4 <+44>:  mov    x22, x0
    0x100973db8 <+48>:  mov    x0, x20
    0x100973dbc <+52>:  mov    x1, x21
    0x100973dc0 <+56>:  bl     0x1009e9b30               ; symbol stub for: objc_msgSend
    0x100973dc4 <+60>:  mov    x29, x29
    0x100973dc8 <+64>:  bl     0x1009e9b78               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x100973dcc <+68>:  mov    x20, x0
    0x100973dd0 <+72>:  nop    
    0x100973dd4 <+76>:  ldr    x1, #849044               ; "valueForKey:"
    0x100973dd8 <+80>:  mov    x0, x19
    0x100973ddc <+84>:  mov    x2, x22
    0x100973de0 <+88>:  bl     0x1009e9b30               ; symbol stub for: objc_msgSend
    0x100973de4 <+92>:  mov    x19, x0
    0x100973de8 <+96>:  mov    x0, x22
    0x100973dec <+100>: bl     0x1009e9b48               ; symbol stub for: objc_release
    0x100973df0 <+104>: mov    x0, x19
    0x100973df4 <+108>: bl     0x1009e9b78               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x100973df8 <+112>: mov    x19, x0
    0x100973dfc <+116>: nop    
    0x100973e00 <+120>: ldr    x1, #851168               ; "dateFromString:"
    0x100973e04 <+124>: mov    x0, x20
    0x100973e08 <+128>: mov    x2, x19
    0x100973e0c <+132>: bl     0x1009e9b30               ; symbol stub for: objc_msgSend
    0x100973e10 <+136>: mov    x29, x29
    0x100973e14 <+140>: bl     0x1009e9b78               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x100973e18 <+144>: mov    x21, x0
    0x100973e1c <+148>: mov    x0, x19
    0x100973e20 <+152>: bl     0x1009e9b48               ; symbol stub for: objc_release
    0x100973e24 <+156>: mov    x0, x20
    0x100973e28 <+160>: bl     0x1009e9b48               ; symbol stub for: objc_release
    0x100973e2c <+164>: mov    x0, x21
    0x100973e30 <+168>: ldp    x29, x30, [sp, #32]
    0x100973e34 <+172>: ldp    x20, x19, [sp, #16]
    0x100973e38 <+176>: ldp    x22, x21, [sp], #48
    0x100973e3c <+180>: b      0x1009e9ac4               ; symbol stub for: objc_autoreleaseReturnValue

The funny thing is that the view controller calling the HomeKit appliance does not send a NSDate value, it does not even have any iZettle related code in it.

```
        guard
            let services = accessory?.services else {
                print("No Service")
                return
        }
        for service in services {
            if service.serviceType == HMServiceTypeOutlet {
                for characteristic in service.characteristics {
                    print(characteristic.characteristicType)
                    if characteristic.characteristicType == HMCharacteristicTypePowerState {
                        print(characteristic.metadata!)
                        dump(characteristic)
                        // Turning off the outlet
                        characteristic.writeValue(false, completionHandler: { (error: Error?) -> Void in
                            if error == nil {
                                print("Yup")
                            } else {
                                print("Nop")
                            }
                        })
                    }
                }
            }
        }
```

As you can see, there is no date sent, or anything remotely related to iZettle. I guess you guys need some more information, Ill try to provide you with whatever you need.

Hope you can get on this asap, this is used in an app that should be in use, but because of the crash, the client system is down at the moment.

**Comment by mansbernhardt** [comment]
We have an extension on NSDictionary:

```objc
@interface NSDictionary (Fractionized)
- (NSDate *)dateForKey:(id)aKey;
@end
```

Do you have one as well? Or perhaps home kit has added one. I think we have a collision causing this crash. We will make sure to prefix ours with iz.

**Comment by GJNilsen** [comment]
No, I do not have any extensions on that specific project, so there has to be a collision with HomeKit after iOS 10. How long would it take to get a fix?

**Comment by mansbernhardt** [comment]
Hopefully later today.

**Comment by GJNilsen** [comment]
👍

**Comment by GJNilsen** [comment]
The conflict is fixed. Thanks!

**Comment by mansbernhardt** [comment]
Create, but remember to wait for the official release before do any release yourself.

**Comment by GJNilsen** [comment]
Ok, since the release is not official, Ill reopen the issue until its officially closed.

**Comment by Sajjon** [comment]
@GJNilsen Hello, Alex from iZettle here. I just release version `1.4.1` (https://github.com/iZettle/sdk-ios/releases/tag/1.4.1)

It is avaiable using cocoapods as well.

Can I close this issue?

**Comment by GJNilsen** [comment]
Ofcoz 😉 Great job guys! Ill release my app as well then!

**Comment by Sajjon** [comment]
@GJNilsen Thank you very much for your help! 🙌
