### ISSUE TITLE
Crash on long reference string

### ISSUE THREAD

**Issue by andriirogulin** [iZettle/sdk-ios#12]
Hi, I use as reference string a list of order id's.
Every id is 6-digit number:

"order_ids" =     (
        108719,
        108720,
        108721,
        108722,
        108723,
        108724
    );

And if there are more that 5 orders - i get app crash:
*** Terminating app due to uncaught exception 'iZettleSDKException', reason: 'Reference exceeded max length (128)'

**Comment by mansbernhardt** [comment]
I would suggest you create a hash (such as md5 or a sha1) from your concatenated order_ids string and use that as your reference instead.
