### ISSUE TITLE
Login window

### ISSUE THREAD

**Issue by shifteo** [iZettle/sdk-ios#124]
Hello,

I apologize in advance for my English.
We have an ergonomic problem with your SDK.
For each payment the login window to the izetlle account appears.

Does an API exist to be able to save its connection parameters in our POS to no longer have this modal IFRAME ?
OR
Is there another way to connect without going through the iframe?

thank you in advance,
Best Regards,
Greg

**Comment by mansbernhardt** [comment]
This is not how it is supposed to work. The SDK remembers active sessions. Which version of the SDK are you using? Are you using encorcedUserAccount? Does it work with the provided sample app?

**Comment by zabojad** [comment]
Hi @mansbernhardt!

> The SDK remembers active sessions
Yes it is what we actually observe.

What @shifteo wanted to say is that he would like to avoid this login window to show up and thus have another way to provide the iZettle SDK with the iZettle account username / password.

Some hidden iZettle API method maybe ? Or some config file ?

Thanks in advance for your answers...

**Comment by mansbernhardt** [comment]
@zabojad Yes this has been requested in the past. We can't open up username/password for security reason, but we might open in the future to pass a valid session token that could have been created else-where.

**Comment by shifteo** [comment]
Thank's @mansbernhardt!,

So does this mean that all sellers of a restaurant need to know the access to the iZettle account?
This is a big security issue because sellers are not boss and do not have to have access.

Do you have a set date for using a JWT type token ?

Thank's

**Comment by mansbernhardt** [comment]
@shifteo Perhaps you should describe your scenario instead and we will work from there? Why can't the "supervisor" login, or you might also add iZettle sub-accounts for the sellers?

**Comment by shifteo** [comment]
I explain our solution:
We work for big franchises like Columbus Café.
Each store has our sales terminal solution. And when installing the POS, we want to send a secure and encrypted key that would contain the izettle account and our internal license for POS use. In this way each store has a transparent use without knowing the accesses and directly synchronized with iZettle

**Comment by shifteo** [comment]
@mansbernhardt , 
Do you think we can work in that direction to achieve that result? As mentioned, we are already working with Columbus Café and also subsidiaries of the SNCF or airlines. And I would really like to be able to offer this solution automatically to all ours customers

**Comment by mansbernhardt** [comment]
@shifteo How would you perceive you would retrieve and distribute this token. For example, we could open up a web server for you to manually login that passes back a token that you then have to distribute to your clients?

**Comment by letsila** [comment]
Hi @mansbernhardt ,
Exactly, you could create an interface on a webserver or an API on your side in order to allow @shifteo or any other user of the iZettle SDK to create and manage encrypted tokens for their clients. Those token would then be used to authenticate programmatically to the iZettle service rather than  authenticating via the login window.

**Comment by TomasPro** [comment]
Hi guys,

we will review this request internally and come back to you in a few days. 

btw regarding the security aspects of having to share username/password with the staff. Through my.izettle.com you can create staff accounts. While the main admin account has access to all account information, staff accounts can only (1) perform payments, view their payment history & refund only transactions performed through their staff account and importantly (2) staff accounts do not have access and cannot change any admin data (e.g. business details, payout account etc.).
