### ISSUE TITLE
How to implement iZettle settings in react native app?

### ISSUE THREAD

**Issue by borglind** [iZettle/sdk-ios#127]
I was asked to raise an issue on github if i had any tech relatied questions, so I hope you can help me.

First off: i'm a javascript dev trying to implement iZettle into my React Native project, and I'm quite inexperienced with objective-c/ios development.

I've successfully added the iZettle ios SDK to my project, and I've connected to the API in my AppDeligate.m with startWithAPIKey - which all seems to work fine.
I can also successfully @import iZettleSDK into other files (at least without errors).

I need to do two things:
**1)** Create a native module so i can use the SDK to create payments
**2)** Somehow be able to connect/change settings for the iZettle reader

Regarding **1)** I think this can easily be achieved by creating a React native bridged module ([docs here](https://facebook.github.io/react-native/docs/native-modules-ios.html)) and mapping the SDK methods to javascript methods, so I'm not concerned with that.

My issue is implementing **2)**. As far as i can tell the only way to connect to the iZettle service / device settings is trough the presentSettingsFromViewController view.

Looking in the react native docs i came upon this: [Native UI components](https://facebook.github.io/react-native/docs/native-components-ios.html), but I believe that it's not possible to implement it like that since they implement a UIView in the docs, and presentSettingsFromViewController returns a UIViewController.

Correct me if i'm wrong.

I've successfully implemented another framework with a view into my react native application (not sure if it's a UIViewController or just a UIView) by following this guide: [Adding MapBox to your react native app](https://medium.com/ibm-watson-developer-cloud/create-native-ui-component-in-react-native-6f4b7fe4cc95#.bcb90n5iv)
And I've tried with my best of efforts to implement the presentSettingsFromViewController with the above method and using:
`[[iZettleSDK shared] presentSettingsFromViewController:self];`
but i run into this warning: 
`Incompatible pointer types sending 'PaymentSettingsView *' to parameter of type 'UIViewController * _Nonnull'`
(As I said, I'm very inexperienced with objective-c)

Do you have any ideas on how to use the presentSettingsFromViewController in a react native app? I'm open to any ideas.

Is it possible to somehow login to iZettle trough other means that the presentSettingsFromViewController, perhaps trough simple API methods instead of a view?
And the same questions goes for setting up the device.

**Comment by mattiasjahnke** [comment]
Hi,

You are calling `[[iZettleSDK shared] presentSettingsFromViewController:self];` and get an error saying that you are passing something else than a `UIViewController`, that means that `self` in this context isn't a `UIViewController` (sounds like it would be an instance of `UIView`). You have to pass an instance of a view controller to this method.

_Is it possible to somehow login to iZettle trough other means that the presentSettingsFromViewController, perhaps trough simple API methods instead of a view?_
- All operations in the SDK will present the login screen (not only `presentSettingsFromViewController`). There is unfortunately no programmatically-only way to authenticate.

_And the same questions goes for setting up the device._
- Not sure what you mean, please elaborate.

We do not offer support for solutions like React Native, I can only help you out with questions related to our SDK. For questions regarding Objective-C or React Native, I must refer you to platforms like stackoverflow.

**Comment by borglind** [comment]
Alright, thanks for clearing that warning up for me :)

> And the same questions goes for setting up the device.

The settings view can be used to other stuff than log in (eg. choosing device) and i would obviously also like to know if those were accessible in a programmatically-only way (as you put it) which i can understand that it is not. 

The only reason i asked here was because that was what your support told me to do - i knew it was a long shot, but worth a try :)

It's a shame if we have to find another solution that iZettle though. It seems to work really well!

**Comment by mattiasjahnke** [comment]
Hi,

I'm still not following what you mean by choosing device. If you mean card readers, they are connected via bluetooth and doesn't have to be configured from the settings view at all.

You are very welcome to ask questions around the SDK here, so you've come to the right place for that ;)

**Comment by borglind** [comment]
Yes, i mean card readers. They have to be connected through bluetooth trough the iphone's settings, and then i have to select it trough the settings view *inside* the iZettle SDK example app.

So i need both to log in AND select the card reader inside my app.

**Comment by borglind** [comment]
Or maybe that's just an *overview* of the card readers, and if i've selected my card reader trough the iOS devices' bluetooth settings, iZettle will just know to use that?

If so, could i then use enforcedUserAccount to "auth" the charge, without auth from the settings view, and thereby completely bypass the settings view and still make charges?

**Comment by borglind** [comment]
Alright, so after some fiddling around i figured it out that chargeAmount also invokes the settings screen so presentSettingsFromViewController is not even needed :)

**Comment by borglind** [comment]
For anyone who might come here wondering how to setup iZettle with react native, i'll leave my findings here (hope that's ok)

Thanks to @shankiesan for the help.
I also managed to open the settings page without an amount with @shankiesan's method.

1. create a new Cocoa Touch Class (right click your project in Xcode -> New file. Call it "iZettleInterface"
2. edit iZettleInterface.h:
```
#import <Foundation/Foundation.h>
#import "React/RCTBridgeModule.h"
@interface iZettleInterface : NSObject <RCTBridgeModule>
@end
```
3. edit iZettleInterface.m:
```
#import "iZettleInterface.h"
#import "React/RCTLog.h"
@import iZettleSDK;
#import "AppDelegate.h"

@implementation iZettleInterface

RCT_EXPORT_MODULE();

//charge an amount. Params: amount (NSDecimalNumber), currency (NSString), reference (NSString)
RCT_EXPORT_METHOD(iZettleChargeWithAmount:(double)amount currency:(NSString *)currency reference:(NSString *)reference iZettleAccountEmail:(NSString *)iZettleAccountEmail
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  
  // get rootViewController
  AppDelegate *appDelegate = (AppDelegate *)[UIApplication sharedApplication].delegate;
  UIViewController *rootViewController = appDelegate.window.rootViewController;
  
  NSDecimalNumber *decimalAmount = [NSDecimalNumber decimalNumberWithDecimal:[NSNumber numberWithDouble:amount].decimalValue];
  
  [iZettleSDK shared].enforcedUserAccount = iZettleAccountEmail;
  
  [[iZettleSDK shared] chargeAmount:decimalAmount currency:currency reference:reference presentFromViewController:rootViewController completion:^(iZettleSDKPaymentInfo * _Nullable paymentInfo, NSError * _Nullable error) {
    if(paymentInfo){
      resolve(paymentInfo);
    } else {
      reject(@"card_declined_or_error", @"Card declined", error);
    }
  }];
  
}

// show settings page
RCT_EXPORT_METHOD(showSettings)
{
  // get rootViewController
  AppDelegate *appDelegate = (AppDelegate *)[UIApplication sharedApplication].delegate;
  UIViewController *rootViewController = appDelegate.window.rootViewController;
  
  [[iZettleSDK shared] presentSettingsFromViewController:rootViewController];
}

// run in main thread (needed)
- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}

@end
```

4. Create native module in js, eg.:
```
import { NativeModules } from 'react-native';

async function chargeAmount(amount, reference, enforcedUserAccount){
  try {
    const paymentInfo = await NativeModules.iZettleInterface.iZettleChargeWithAmount(parseFloat(amount), null, reference, enforcedUserAccount);
    console.log('success', paymentInfo);
  } catch(err){
    console.error(err);
  }
}
```
(check [the docs](https://facebook.github.io/react-native/docs/native-modules-ios.html) for more info on native modules)

**Comment by shankiesan** [comment]
Woop thanks @borglind . Happy for that to live here...!
