### ISSUE TITLE
Refunding transaction - not found

### ISSUE THREAD

**Issue by lasserg** [iZettle/sdk-ios#128]
Hi,

When trying to complete a refund in the SDK, regardless of which reference I use, it returns not found. Is this a known issue? I've tried different employee logins, and it does not work. As we use this app for several thousand transactions, I need to be able to refund a specific transaction. 

please respond asap.

Thanks.

**Comment by mattiasjahnke** [comment]
Hi,

The API expects you to pass the reference you provided to the `charge`-method. Can you confirm that this is what you are doing?

**Comment by lasserg** [comment]
Hi, 

No, actually, I used the ref returned by the charge method. Sorry about that.

Any plans of being able to find a transaction by ref no?

Lasse

**Comment by mansbernhardt** [comment]
In what way would that help?

**Comment by jeremangnr** [comment]
@mansbernhardt I wonder what is the reasoning behind this? you already have a value which identifies a transaction, why do you need another one? in our case we did not set the reference number previously, so all transactions done before that are non-refundable

**Comment by mansbernhardt** [comment]
@jeremangnr the reason to pass your own reference is that you have a way to get information about your payment if something goes wrong:
1) create own reference and persist.
2) call  `chargeAmount`/`refundAmount` to create or refund a payment. But what if something went wrong here such as network error, crash etc. This mean the app never got a reply back are at least not a successful one with a reference. Was the payment successful or not? We need a reference to pass into `retrievePaymentInfo`, and the only one we have is our own.
