### ISSUE TITLE
Refund Error. Insufficient funds in your iZettle account.

### ISSUE THREAD

**Issue by iabdullin** [iZettle/sdk-ios#129]
Hello Team,

     Updated SDK to version 1.4.2. After refund attempt, SDK shows the following error:
Refund Error. Insufficient funds in your iZettle account.
     What does it mean?

Best regards,
Ildar

**Comment by mattiasjahnke** [comment]
Hi,

Sorry for the late reply. Are you using a test account?

Regards,
Mattias

**Comment by jeremangnr** [comment]
@mattiasjahnke I am getting this too, using test account externaldemo@izettle.com. Is there any way I can test refunds?

**Comment by arikis** [comment]
@iabdullin  @jeremangnr: Demo accounts have auto revert function. That's means that you need to refund in the short time span before the money get's reverted back to your account. Auto reverting makes it a bit hard to test, but it is possible.
