### ISSUE TITLE
How can I determine status of user (logged or not logged) at account and what is example for type currency?

### ISSUE THREAD

**Issue by alychkouski** [iZettle/sdk-ios#13]
Hi guys!
In the previous version iZettle SDK was method "- (void)userInfoCompletion:(void (^)(NSDictionary *userInfo, NSError *error))completion;" which could return userInfo. I used this info for determining status of user.
Could you help me, how I can determine status of user in actual version iZettle SDK?

What is type of currency code I should to transfer to parameter currency? I wrote "USD" and tried "$" and result was - incorrect currency.

Best regards, Andrei.

**Comment by mansbernhardt** [comment]
Answer to question 1: We will consider to re-introduce something similar to the userInfo method again. Could you explain more in detail what you use it for?

Answer to question 2:  From the docs:
currency (optional): Only used for validation. If the value of this parameter doesn't match the users currency the user will be notified and then logged out. For a complete list of valid currency codes, see ISO 4217

Using USD will always fail as there is currently no way to have an iZettle user account with that currency (as iZettle are not yet on any market using USD).

**Comment by alychkouski** [comment]
Hello, @mansbernhardt. 

Q1: I should display status of iZettle account (Logged or not logged). And from it depends UI logic application.

Q2: "GBP" - Will be valid currency?

*Q3: Refund button hided for keyboard. Could you fix this issue? (for example move Refund button slightly above).

I would be very grateful if you could help me with these questions.

Best regards, Andrei.

**Comment by mansbernhardt** [comment]
Q2: "GBP" would work if the logged in user is registered in Great Britain.
Q3: What iOS device are you running on? Could you provide a screenshot?

**Comment by bartg** [comment]
I will join Q1: at my current company we are developing Point of Sale system so we have various payments options enabled there, including iZettle. We have a settings screen where you can enable iZettle but before you do, you had to be logged in which makes total sense, since we dont want our users to see iZettle during checkout, then tapping on it only to see "Please log in". Unfortunately now its not possible. 

Would be useful to get at least boolean value about state of being logged in.

**Comment by alychkouski** [comment]
Q3: on iPhone 5. I can send screenshot a little bit later.

**Comment by alychkouski** [comment]
Hi, guys!
Attach images for Q3:
![img_4951](https://cloud.githubusercontent.com/assets/13240124/9040007/e9d7dbe4-3a07-11e5-843f-301227133ab3.PNG)
![img_4952](https://cloud.githubusercontent.com/assets/13240124/9040008/e9ff02dc-3a07-11e5-908f-993bd36e875f.PNG)

**Comment by alychkouski** [comment]
Could you please add izettle account for user info, question 1 in this issue.

**Comment by mattiasjahnke** [comment]
@alychkouski we'll investigate Q3. As for the other questions, please refer to #16
