### ISSUE TITLE
Some Partial Refunds not available on website

### ISSUE THREAD

**Issue by nikkonikko** [iZettle/sdk-ios#130]
We did do some final real-life test with partial refund, yesterday 13.03 at 11:09, and this is the case:

1) Refunded -4.5 DKK with success:

2) Then afterwards refunded -16.65 DKK with success:

But we only see the -16.65 DKK but NOT the -4.5 DKK on website. 

We tried yesterday multiple partial refunds and it seems always one of the two partial refunds is not registered on the website afterwards.

Could you please check it. Thanks.

**Comment by renholm** [comment]
Hi @nikkonikko, what is your bundle ID?

**Comment by nikkonikko** [comment]
I did send an email to Mattias with detail informations yesterday - he should have forwarded it to the iOS team.

**Comment by renholm** [comment]
First of all, these two partial refunds where made on two different original payments? 

For the payment with the missing refund another partial refund was made before `-25,65` (out of the original `30,15` DKK). Then the `-4.5` was performed. There may be two reasons why it is missing, (1) the user of the same reference for both, (2) a support system does not handle SDK partial refunds correctly.

**Comment by nikkonikko** [comment]
I think yes. But it doesn't matter - if we do two partial refunds on the same original payment, the same problem.

I just did one payment with success: 43.15 DKK
Then I did two partial refunds on the same reference
First -10 DKK with success
Then afterwards -12 DKK with success

The -10 DKK is visible on the website immediately after. But the -12 DKK is still not visible.

When calling the charge method in iZettle , this is printed out, if that could be to any help:

Unbalanced calls to begin/end appearance transitions for <IZAccountListController: 0x1108d8f50>

**Comment by nikkonikko** [comment]
I just did this now: A purchase of 15 DKK, which was immediately visible on website.
Then I did on the same reference:
-5 DKK with success, then
-3 DKK with success, then
-7 DKK with success

For now only the -5 DKK is visible...

Can you just confirm that they all went "through" even they aren't visible?

(Mattias has my direct phone number if needed).

**Comment by renholm** [comment]
@nikkonikko Mattias is not available but I think we have quite a clear picture of the problem. Thank you for the more examples you sent. 

I can confirm that the refunds are executed correctly and money are returned. However, one backend service does not seem to support this type of operation for the SDK and hence the refund does not show up in the list on the portal. 

I have no information about when this can be fixed. You can however on your end keep a list of what transactions have been done in the meantime.

**Comment by nikkonikko** [comment]
Okay, thank you for your reply. It would be nice to know, when its fixed :)

**Comment by nikkonikko** [comment]
Just to avoid any misunderstandings, so we can use this release in reallife now, since all is executed correctly?

But all partial refunds will be available on website in the nearest future - after you do fix?

**Comment by renholm** [comment]
@nikkonikko I can't promise past partial refunds will be available. But after a fix the future ones will.
