### ISSUE TITLE
Transaction search retrieval API

### ISSUE THREAD

**Issue by nmodin** [iZettle/sdk-ios#131]
Hi,

I'm looking for a transaction query API for transactions made earlier with no reference available, but not sure if this is possible ?

Basically something along the lines of:

_open func retrievePaymentInfo(forTimeInterval TimeInterval, completion: @escaping iZettleSDK.iZettleSDKOperationCompletion)_

This would then just return a list of reference numbers for which you then could retrieve more detailed information if need be.

The ideal API would be to have the option to add a delegate / callback for transactions made in real time, or near real time though. :)

The scenario here would be to build a transaction monitoring system that can track transactions made from multiple terminals and/or geo-locations for business analysis purposes.

Cheers,
Niklas

**Comment by mattiasjahnke** [comment]
Hey Niklas,

This isn't something we have available today - but could definitely be something that opens up in the future.

Regards,
Mattias
