### ISSUE TITLE
Enforce user account question

### ISSUE THREAD

**Issue by patwhitehead1** [iZettle/sdk-ios#133]
We're looking into using the enforcedUserAccount property, and we have a question about creating new accounts. 

When I set the enforced user account, I'm not able to edit the email field on the login screen (expected), however I still see the option to sign up for a new account on that same screen. Is it possible that somebody could create a new account from that screen and then use that new account instead of the enforced account?

Since we're not located in a region where iZettle is available, we can't test this on our own. Any information would be appreciated, thanks.

**Comment by mansbernhardt** [comment]
Signing up for a new account should not affect the enforcedUserAccount account. But it might make sense to disable the create new account button if we have an enforcedUser. 

@adeemotu could you verify the above?

**Comment by adeemotu** [comment]
@patwhitehead1 , i tested with mentioned scenario. After setting enforce user and proceeding with new account process , newly created user is not signed in i.e. enforced user remained active. Let me know if it help in explaining your question.
