### ISSUE TITLE
[Code Enhancement Request] add BOOL isCancelled to iZettleSDKOperationCompletion 

### ISSUE THREAD

**Issue by hassanain-idris** [iZettle/sdk-ios#134]
This suggestion will better fit the charging and refunding amount where the user can cancel the transaction and dismiss the izettle VC. Which will allow us to detect the cancellation and adapt to it when it happens and avoid processing and displaying a generic (user friendly) error instead.

**Comment by mansbernhardt** [comment]
If the user cancels the request you should receive an error saying "Cancelled by user", but I'm not fully sure that if we can guarantee that (It seem we have two different error domains and codes mapping to this error text). One way would add an extension to NSError such as Bool izWasCancelledByUser. 

But as mentioned in the SDK readme:
 
### Errors

iZettle will display any errors that occur during an operation to the user, the NSError-object returned in the operation completion block is only intended to be used by developers for debugging, diagnostics and logging to be able to better communicate errors to iZettle. You should never present the returned errors to the end user.


So I'm not sure why you would need this, as the user should be aware what happened.

**Comment by hassanain-idris** [comment]
In our project whenever a transaction failed with an error we are displaying a localized generic error message to our end user. We are doing this since we can't rely on the error we got from your SDK. For the cancel state we don't want to present that generic error to our customers.
The problem arise from undocumented error code/domain/messages we can't just figure the cancel error on our own, and even if we did we can't depend on it not to changed in the future. Even yourself, you are not sure you can guarantee that.

This proposal will simplify the life of iZettle integrators, and it feels like it should be encapsulated in the SDK.

**Comment by svenmuennich** [comment]
We have the same issue and currently work around it comparing error domain and code to the ones we know correspond to a user cancellation. I think just documenting the user error codes and domains and maybe even providing error code constants in the SDK would solve this without having to change much in the SDK.

**Comment by svenmuennich** [comment]
What's the reason for closing this? Does that mean that it is already fixed and will shipped with the next release?
