### ISSUE TITLE
iZettle problem (SDK 1.4.2)

### ISSUE THREAD

**Issue by andriirogulin** [iZettle/sdk-ios#138]
The issue seems to be that at random times the iZettle terminal does not receive a call of  'chargeAmount:' func of iZettle SDK

1. iPad displays “Insert card” in iZettle SDK 
2. Terminal displays “Connected to iPad”
After inserting a credit card - nothing happens

It seems like the iZettle terminal is not connecting right with the SDK in the app.
The only fix I can find is restarting the iZettle terminal.

**Comment by mattiasjahnke** [comment]
@andriirogulin Do you have the iZettle app installed on the same device?
