### ISSUE TITLE
Payment error / Incorrect integration. Contact your app provider.

### ISSUE THREAD

**Issue by achyutrk** [iZettle/sdk-ios#14]
Hi Guys,

I have an issue with integration. When i used the demo api key with demo bundle identifier which is present into your example than its working but when i change to my API key with my bundle identifier then its created a issue with below error message. I have used the below key and bundle identifier.

bundel ID: com.hikepointofsale
Key: 7DF92FDD30A42E0ED1823875FD35066F

Error Domain=com.izettle.session.error Code=2 "Payment error / Incorrect integration. Contact your app provider." UserInfo=0x7ffd5173e9e0 {izTitle=Payment error, NSLocalizedDescription=Payment error / Incorrect integration. Contact your app provider., izMessage=Incorrect integration. Contact your app provider.}

Thank you !

Regards,
Achyut

**Comment by mattiasjahnke** [comment]
Hi @achyutrk 

I believe we've solved your issue outside of Github - closing this.

**Comment by Nadejde** [comment]
Hope you changed that key:)
