### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by LeMoumouGwoo** [iZettle/sdk-ios#140]
Hi,

I apologize for disturbing you, but I no longer have the ability to run iZettle on our application.

I get the message "Wrong payment - Incorrect integration. Contact your application provider" when I want to send a payment to the reader. The API key I use is always the same.

I have not changed anything in terms of the code or the integration of your framework. I'm on the latest version 1.4.2 (via Cocoapod)

An idea ?

thanks in advance

Regards,
Thomas

**Comment by arikis** [comment]
Hi, we're looking into the issue and will let you know as soon as we have more information.

**Comment by lagex-iztl** [comment]
Hi Thomas, could you please send us some more information like you `application_id` and `application_key` to this email address `payments-tls@izettle.com`?

**Comment by WoolsDev** [comment]
We also get this error and have not as yet been able to test a payment using our test account. Is there a general solution to this yet?
