### ISSUE TITLE
Thread1:EXC_BREAKPOINT encountered using Swift to call chargeAmount()

### ISSUE THREAD

**Issue by WoolsDev** [iZettle/sdk-ios#141]
I have written a small iOS test app using Swift to allow us to take a test payment on our account using our iZettle reader. Whenever I call the chargeAmount() function the app will stall and break in xcode with the line 'Thread 1: EXC_BREAKPOINT (code=1, subcode=0x10009b33c). I cannot find anything wrong with the code and the iZettle reader is paired OK with our iPad

![screen shot 2017-06-08 at 16 38 53](https://user-images.githubusercontent.com/29625521/27426634-385c8774-5734-11e7-9014-eaa7401f7231.png)

**Comment by mansbernhardt** [comment]
It most likely because of your forced cast (as!)
Try remove it and change the completion handler to take optional (?) info and error.

**Comment by WoolsDev** [comment]
Thanks for the reply, but it won't compile without the cast. 
<img width="1160" alt="screen shot 2017-06-26 at 15 41 14" src="https://user-images.githubusercontent.com/29625521/27545004-9fddc9f8-5a86-11e7-8613-ff9d9e68a5a0.png">

**Comment by mansbernhardt** [comment]
Try change NSError to just Error

/Måns

Sent from my iPhone

**Comment by WoolsDev** [comment]
Great. that worked. 

Thanks for your help.
Neil.
