### ISSUE TITLE
Payment process issues

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#142]
Hello,

We are having some issues with the payment process. Sometimes it works fine, but most of the times it fails with the following message: "An error as occurred, Card reader link time out". 

It used to work in our app without any issues but today we received a few complains from our customers. We also thought that we had a faulty card reader but it works on the ios iZettle app. 
Could you please advice us?

The following are some screenshots of the payment process:
<img src="https://user-images.githubusercontent.com/7304626/27438172-4a765886-575c-11e7-9a6f-17c72d79bb5d.png" width="480">
<img src="https://user-images.githubusercontent.com/7304626/27438175-4a7bb79a-575c-11e7-9ea6-9a6377b83a4f.png" width="480">
<img src="https://user-images.githubusercontent.com/7304626/27438173-4a7a2416-575c-11e7-8b2b-521b4f6221fc.png" width="480">

**Comment by asa47** [comment]
Hello,

We run a few test, and we have probably found the problem; we have recently included in our app the MultipeerConnectivity framework in order to communicate with nearby devices. 

As for now if we do not create any multipeer connection the iZettle SDK works correctly; however as soon as we instantiate a multipeer connection the iZettle SDK, we are having the issues.
Is it possible that the multipeer connection is interfering with the iZettle SDK?

**Comment by arikis** [comment]
Hi @asa47,

Yes, very possibly. As far as I understand `MultipeerConnectivity` makes use of bluetooth stack in iOS. Since the reader operates via Bluetooth, some functionality in the `MultipeerConnectivity` framework could interfere with it and invalidate some communication which would fail the transaction.

**Comment by asa47** [comment]
Hello @arikis,

Thanks for the reply, and yes we thought the same. As for now we disable any multipeer connection if our customer want to process payment through iZettle. 

Do you think it is something that can be fixed on your side? Or do you have any advice/routes that we should consider in order to fix the issue?

**Comment by arikis** [comment]
I guess that the best solution would be disabling multipeer connections before processing payment with iZettle. SDK doesn't have any accesss to those connections so it's almost impossible to anything about that from our side.

**Comment by GamerPixBoy** [comment]
Bro remove this images people are scaming through this hahahahaha
