### ISSUE TITLE
Question related to izettle sdk implementation

### ISSUE THREAD

**Issue by KeesRooijers** [iZettle/sdk-ios#149]
Good afternoon,

We are running a izettle IOS-sdk implementation pilot for a customer of ours, we already got a big part up and running but it seems we encountered a limitation in the SDK that is really an issue for us in a wide scale rollout.
When  we do the first request to the SDK we supply login information but at that time the Izettle login pane is opening and asking for the password again. We don’t want end-user involvement in the login proces, so we would prefer something like a token (perhaps even with credentials) that is granting excess to the payment module.

The background in this is that our application will be used by hundreds of part time workers on a daily bases for different projects. Within the projects different Clients with different Izettle accounts are involved and it’s undoable (and for sure not wished) that de part time workers are known with the passwords of different Clients of ours.

So is there any (un)documented feature that enables automated login for example by means of a Token or something similar.

**Comment by mattiasjahnke** [comment]
Hi @KeesRooijers 

This feature request has been discussed here before (for example in #124) and it's not something that we currently support.
