### ISSUE TITLE
Izettle crash

### ISSUE THREAD

**Issue by Jpmose9** [iZettle/sdk-ios#15]
When the app run that line of code

- (void)startWithAPIKey:(NSString *)apiKey;  

the app crash every time this issue started about 2 or 3 weeks ago and since then I'm not able to use the reader with the app I commented that line of code to be able to use the app.

**Comment by mansbernhardt** [comment]
Hi,

We would need some more info to be able to help you.

What kind of crash or you seeing, such as e.g. an exception?

What iOS version and iOS device are you running on?

Could you provide a call stack for the crash?

/Måns

**Comment by Jpmose9** [comment]
I'm using iOS 8.4and running it on the iphone 6 plus simulator
Before that the app was crashing using an iphone 4S We stopped using it and since i'm trying it on the simulator before testing it on the iphone 4

There is no exception actually the app just hang and I have on the simulator. On the actual devices it would close the app. 

I will attach screenshot from xcode.

![izettle_1](https://cloud.githubusercontent.com/assets/1054633/8937554/662b137c-3527-11e5-9a59-9421a3436471.png)
![izettle_2](https://cloud.githubusercontent.com/assets/1054633/8937555/66320038-3527-11e5-9589-1b713e241cbd.png)
![izettle_3](https://cloud.githubusercontent.com/assets/1054633/8937556/663678a2-3527-11e5-8c30-da0b6f47df34.png)

**Comment by mansbernhardt** [comment]
How you double checked the integration steps? https://github.com/iZettle/sdk-ios

This looks to be either to be the resource bundles that are missing or has been renamed or changed capitalization (step 2), or some of the linker flags that are missing (step 5).

/Måns

**Comment by Jpmose9** [comment]
After doing step 2 the app is not crashing on either the simulator or the the iphone 4. 
Thanks.
