### ISSUE TITLE
Upload to AppStore fails with ITMS-90596

### ISSUE THREAD

**Issue by sasjo** [iZettle/sdk-ios#152]
I get the following validation error when attempting to upload: 

```
ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 
'Payload/NN.app/Frameworks/iZettlePayments.framework/Assets.car' can't be read. 
Try rebuilding the app with a non-beta version of Xcode and submit it again."
```

I'm building with Xcode 7.3.1 (Swift 2.2). I haven't found any workaround yet and get the same results using Xcode, `xcodebuild` and `altool`. However, the error doesn't occur until the `ipa` is processed, hence a validation in Xcode will succeed. Running `altool --validate-app` does fail immediately.

I've tried using both v1.5.0 and v1.4.2 and get the same validation error.

**Comment by sasjo** [comment]
I gave it one more try and switched to iZettle v1.4.1 and it passed the validation. I can see that the `Assets.car` is smaller in this release compared to the more recent releases.

**Comment by arikis** [comment]
Hi @sasjo,

we're looking into this now. The possible problem could be that you're building from beta Xcode version, as it's stated in your error message output.

> `Try rebuilding the app with a non-beta version of Xcode and submit it again.`

If you have multiple versions of Xcode on your machine and you're building from command line, you can check which Xcode version is used for building with `xcode-select`.

**Comment by sasjo** [comment]
I've never had any Xcode betas on this machine, but I did have two Xcode installations. I was using `xcode-select` and eventually uninstalled everything and reinstalled only `Xcode 7.3.1`. I'm printing the SDK version with `xcode-select` first thing in my build scripts to ensure the right SDK is in use.

**Comment by arikis** [comment]
Do you have the same issue with only `Xcode 7.3.1` installed?

**Comment by sasjo** [comment]
Yes, with `Xcode 7.3.1` I still have the same issue. The only way I could get around the problem was to switch to `iZettle 1.4.1` frameworks. Changes introduced with `iZettle 1.4.2` seems to break the validation for me, at least with Xcode 7 and iOS SDK 9.3.

**Comment by arikis** [comment]
I will go through the change log and see if there were any changes that could result in this behavior. 

However, the fact that `1.4.2` doesn't work either could be a sign that there's something wrong with your development settings, since we had `1.4.2` and `1.5` in production for some time now, and we haven't had these sort of problems before.

I'll try building and submitting with Xcode 7 and see if I can find out something.

**Comment by arikis** [comment]
@sasjo have you managed to pass the validation? Nothing from our end suggest that there is something wrong with `1.4.2` or `1.5`. 

One possible reason might be that SDK (built in Xcode 8) has some artifacts which are unreadable to Xcode 7.

**Comment by sasjo** [comment]
We always pass the validation on 1.4.1. Since the bug was filed, we've migrated to Swift 3, Xcode 8 and iZettle 1.5. However, we still had validation issues when uploading to ITC. My colleague finally got it working when switching to a different network. I think he tried that after reading this thread: https://stackoverflow.com/questions/39566481/strange-errors-on-archive-validation

**Comment by arikis** [comment]
Great! Closing this one.
