### ISSUE TITLE
Firewall issues/information

### ISSUE THREAD

**Issue by JohanAhl** [iZettle/sdk-ios#155]
Hi,

We are on a closed secure network and I need to know the host and port information for the iZettle Reader? So that we can configure our network/firewall in order for the reader to be able to connect to iZettle.

Best regards
Johan

**Comment by mattiasjahnke** [comment]
Hi,

The iZettle Reader communicates with your app via Bluetooth, not WiFi.

Regards
Mattias

**Comment by mattiasjahnke** [comment]
Sorry read your question a little too fast.

The SDK will target endpoints `*.izettle.com` and `*.izettlepay.com` on port 443.

Does that answer your question?

**Comment by JohanAhl** [comment]
Yes that answers my question perfectly!=)
This is the same in UK, SE and DK or is host different between countries/regions?

**Comment by mattiasjahnke** [comment]
Great!

Yes, the subdomain might change but the host will be the same everywhere.

**Comment by JohanAhl** [comment]
Thats great! Thanks for very quick response!

**Comment by JohanAhl** [comment]
Hi again.

We have configured according to above but we can see that several other domains are called. We have opened all subdomains according the above so it must be some other domains as well?

Best regards
Johan

**Comment by mattiasjahnke** [comment]
Hmm,

Try `*.izettle.net` too!
