### ISSUE TITLE
Problems with the currency on the device 

### ISSUE THREAD

**Issue by jdejuanactionsdata** [iZettle/sdk-ios#157]
In my IBAction I invoke the payment with the parameter **currency: nil**
**On the screen I get the GBP**

```
- (IBAction)charge:(id)sender {
    NSString *amount = [NSString stringWithFormat:@"%f", 1.00];
    [[iZettleSDK shared] chargeAmount:[NSDecimalNumber decimalNumberWithString:amount]
                             currency:nill
                            reference:@"my reference"
            presentFromViewController:self
                           completion:^(iZettleSDKPaymentInfo * _Nullable paymentInfo, NSError * _Nullable error) {
                               NSLog(@"completion, payment info: %@   error: %@", paymentInfo, error);
                           }];
}

```
![gbp](https://user-images.githubusercontent.com/31509748/29967972-c1cba39c-8f19-11e7-8d2c-ad1fafc1eb5e.jpg)
**I need to charge in EURO currency from Spain**.
I change the currency by "EUR" according to ISO 4217 but the result is not the expected one.
How can i solve this?

```
- (IBAction)charge:(id)sender {
    NSString *amount = [NSString stringWithFormat:@"%f", 1.00];
    [[iZettleSDK shared] chargeAmount:[NSDecimalNumber decimalNumberWithString:amount]
                             currency:@"EUR"
                            reference:@"my reference"
            presentFromViewController:self
                           completion:^(iZettleSDKPaymentInfo * _Nullable paymentInfo, NSError * _Nullable error) {
                               NSLog(@"completion, payment info: %@   error: %@", paymentInfo, error);
                           }];

```

![spn](https://user-images.githubusercontent.com/31509748/29968192-ce71b6f8-8f1a-11e7-8936-66ac89549c25.jpg)

**Comment by mattiasjahnke** [comment]
The currency is decided by the logged in account. The account you're using is configured for GBP.

The `currency` parameter is there for validation - not to set the currency used for the payment.

Login with an account with EUR as currency (decided by country).

**Comment by jdejuanactionsdata** [comment]
In the account of sdk ios that you sent me I can not change any parameter.
This account must be in GBP but I can not change it.

 





My real account is jdejuan@actionsdata.com which is from the beginning in euro.
I can not request a new sdk key at jdejuan@actionsdata.com since your form appears Network ERROR.



 

Regards

cid:image001.gif@01CABBB4.832FDD60 

Jose Enrique de Juan | Director de I+D+i
Convertimos sus acciones de marketing en datos, y sus datos en activos para su empresa
Avda. de la Victoria, 50 · 28023 · La Florida · Madrid · Tel. 902 010 700 · Fax 902 876 575
 <http://www.actionsdata.com/> www.actionsdata.com · jdejuan@actionsdata.com

Antes de imprimir este mensaje, asegúrese de que es necesario. Protejamos el medio ambiente.

La información transmitida va dirigida únicamente a la persona o entidad que se muestra como destinatario y puede contener datos confidenciales o privilegiados. Toda revisión, retransmisión, diseminación u otro uso o acción al respecto por parte de personas o entidades distintas al destinatario está prohibida. Si recibe esto por error, por favor contacte con la persona que figura como remitente y elimine el material de cualquier ordenador.

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any Computer.

 

De: Mattias Jähnke [mailto:notifications@github.com] 
Enviado el: viernes, 01 de septiembre de 2017 15:37
Para: iZettle/sdk-ios
CC: jdejuanactionsdata; Author
Asunto: Re: [iZettle/sdk-ios] Problems with the currency on the device (#157)

 

The currency is decided by the logged in account. The account you're using is configured for GBP.

The currency parameter is there for validation - not to set the currency used for the payment.

Login with an account with EUR as currency (decided by country).

**Comment by mattiasjahnke** [comment]
Login with `jdejuan@actionsdata.com` to take payments with euro (if that account is configured for euro).

_"I can not request a new sdk key at jdejuan@actionsdata.com since your form appears Network ERROR."_
If you already have an API key, there's no need to request a new one.

**Comment by arikis** [comment]
@jdejuanactionsdata have you managed to resolve problem with your account?
