### ISSUE TITLE
[Feature request summary] Retrieve user information

### ISSUE THREAD

**Issue by mattiasjahnke** [iZettle/sdk-ios#16]
This is a round-up of several discussions regarding iZettle user account information from the issues posted on this Github repository. This thread can be used to discuss the matter in one single place.

_What's been said about user account information_
- Would be good to display a ui that reflects the current login status
- Either a method `- (void)userInfoCompletion:(..` that existed in the sdk beta or a simple boolean value that indicates if a user is logged in or not `- (BOOL)isUserLoggedIn;`.
- Return information about the iZettle user that made a payment/refund.

We are looking into this, please comment if you have any other feedback regarding this feature that can help us make it as useful as possible.

Closing issues #9 #10 #13

**Comment by skiddle** [comment]
It would be very valuable to be able to see the user info both before and after a sale. This way we can adjust our UI beforehand (it's not very obvious which user is linked when making payments), and also track this on our backend once a payment has occured.

**Comment by sam22200** [comment]
It would be awesome to have a method called :
-(BOOL)startWithAPIKey:(NSString*)apiKey username:(NSString*)user password:(NSString*)pass;
(or with a block callback instead of the BOOL returned value)

Indeed, it's very annoying to type manually the username and the password. Moreover, the calling app would be aware of the user status (logged with success or failed).

**Comment by skiddle** [comment]
Agreed. We would prefer a seperate call, as we only retreive the user's iZettle info at a later stage, but being able to log in the user would be so useful.

It's a risk for us currently that the user could login using an incorrect account

**Comment by mansbernhardt** [comment]
"It's a risk for us currently that the user could login using an incorrect account"

See enforcedUserAccount setting in docs:

- **enforcedUserAccount** _(optional)_: If set, operations will be restricted to only work for the specified iZettle username.

**Comment by skiddle** [comment]
Just been discussing this with Iskren at your end - one issue we currently face, is people using the app without an account, who are then being linked through to your generic signup page through the SDK.

We'd very much like to catch this and offer for them to signup using our bespoke iZettle landing page. To do this, we'd need to be able to detect their login status then link them to either the signup page, or alternatively push the settings view, which I presume would let them log in?

**Comment by leonid-s-usov** [comment]
Attaching #64 here, it seems relevant in this context
