### ISSUE TITLE
iOS 11 settings bug

### ISSUE THREAD

**Issue by nzroller** [iZettle/sdk-ios#163]
This came in via some feedback from a partner:

We found some bugs in your system that appear on iOS 11.

Steps to reproduce:
1. Go to the settings
2. Enter login and password
3. Go to the sections "Terms&Conditions" and "Acknowledgements" 
3. Close settings 
4. Go to the settings again

Actual result:
The settings screen does not scroll (screenshot # 1).
Check out sections  "Terms&Conditions" and "Acknowledgements":
The black arrow is superimposed on blue arrow(screenshots # 2, # 3)

Also, it would be great if we could see the status of the transaction.
For example to add current transaction state (refunded, paid etc.) to - (void) `retrievePaymentInfoForReference` method response? or get this information in some other way?

**Comment by arikis** [comment]
Thanks @nzroller, we'll take a look at it.

**Comment by arikis** [comment]
Fixed in latest release
