### ISSUE TITLE
Create additional Demo accounts

### ISSUE THREAD

**Issue by JohanAhl** [iZettle/sdk-ios#166]
Hi,

Is it possible to create/get several Demo accounts? Today we have 1 demo account set up with GBP but we have a need to use other currencies as well during test due to the fact that our customer is active in several countries. On short term we need at least 2 more currencies (3 in total including our existing GBP account).

Or can our existing account be configured to accept multiple currencies?

Best regards
Johan Ahl

**Comment by arikis** [comment]
Hi @JohanAhl,

that should be possible, please send us an email at `sdk@izettle.com`.

**Comment by JohanAhl** [comment]
E-mail sent!

/Johan
