### ISSUE TITLE
How can I get from the xcode SDK the serial number of the device?

### ISSUE THREAD

**Issue by jdejuanactionsdata** [iZettle/sdk-ios#167]
I need to programmatically get the serial number of the device but not the paymentInfo
`paymentInfo {
    AID = A0000000041010;
    TSI = F800;
    TVR = 0000048000;
    amount = 1;
    applicationName = MasterCard;
    authorizationCode = xfxfxfxfxf;
    cardBrand = MASTERCARD;
    entryMode = EMV;
    obfuscatedPan = "**** **** **** 2023";
    panHash = 1EE3022E9C8836C17FE7725FDD0;
    referenceNumber = C5E2XSJDJSJSJ;
}`

**Comment by arikis** [comment]
Hi @jdejuanactionsdata, which serial number you are referring to?

**Comment by jdejuanactionsdata** [comment]
Regards

cid:image001.gif@01CABBB4.832FDD60 

Jose Enrique de Juan | Director de I+D+i
Convertimos sus acciones de marketing en datos, y sus datos en activos para su empresa
Avda. de la Victoria, 50 · 28023 · La Florida · Madrid · Tel. 902 010 700 · Fax 902 876 575
 <http://www.actionsdata.com/> www.actionsdata.com · jdejuan@actionsdata.com

Antes de imprimir este mensaje, asegúrese de que es necesario. Protejamos el medio ambiente.

La información transmitida va dirigida únicamente a la persona o entidad que se muestra como destinatario y puede contener datos confidenciales o privilegiados. Toda revisión, retransmisión, diseminación u otro uso o acción al respecto por parte de personas o entidades distintas al destinatario está prohibida. Si recibe esto por error, por favor contacte con la persona que figura como remitente y elimine el material de cualquier ordenador.

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any Computer.

 

De: Said Sikira [mailto:notifications@github.com] 
Enviado el: martes, 03 de octubre de 2017 15:17
Para: iZettle/sdk-ios
CC: jdejuanactionsdata; Mention
Asunto: Re: [iZettle/sdk-ios] How can I get from the xcode SDK the serial number of the device? (#167)

 

Hi @jdejuanactionsdata <https://github.com/jdejuanactionsdata> , which serial number you are referring to?
