### ISSUE TITLE
Serial Number 

### ISSUE THREAD

**Issue by jdejuanactionsdata** [iZettle/sdk-ios#168]
Hi
In objective-c how can I get the serial number of the device that is printed on the box and on the back of the device.
Thank you

![sn](https://user-images.githubusercontent.com/31509748/31174160-bfe95046-a90a-11e7-963c-a0ac506ba5c8.png)

**Comment by arikis** [comment]
Hi @jdejuanactionsdata,

Unfortunately, it's not possible to retrieve that kind of info with iZettle SDK.
