### ISSUE TITLE
com.izettle.cardreader.error 12: "Card reader operation failed"

### ISSUE THREAD

**Issue by jeremangnr** [iZettle/sdk-ios#169]
Hi, we have a customer who is getting this error quite often when trying to run a transaction with their iZettle reader (I'm trying to get the model). When this happens they have to place through the transaction a second or third time until it finally comes through. Running version 1.5 of the SDK.

What does this error mean? I could not find any definition for that error in the SDK. Could this be solved by updating to 1.6.1?

Thanks!

**Comment by arikis** [comment]
Hi @jeremangnr, that particular error code is reserved for chip reading errors. So, in a case where reader cannot read the chip on the card, this error will be shown. This mostly happens with older cards with "worn out" chips. Sometimes, reader will actually manage to read it and you'll be able to continue with transaction.

I would suggest looking into:
- Is it always the same card?
- Is it always the same type of card?

Updating to 1.6.1 is also highly recommended. 

Let us know if you have some more questions.

**Comment by jeremangnr** [comment]
Hi @arikis, thanks for the info. We will update the SDK in our next release and see how this goes, closing for now.
