### ISSUE TITLE
35 memory leak issues

### ISSUE THREAD

**Issue by JuanPabloBoero** [iZettle/sdk-ios#173]
While debugging my app in Xcode 9, and the latest to date version of iZettle SDK, I noticed that as soon as I call startWithApiKey, the runtime issues navigator shows 35 new issues, while checking from where they come from, they all where initiated by the iZettle SDK.

Steps to reproduce, got to the target scheme, edit it and in the diagnostics part enable login for live allocations, also enable malloc scribble, then, hit pause in the debug navigator, then hit the memory graph debugger button, then go to the issues navigator and hit the runtime tab, there you have the leaks.

Recommended session where you can see how to see them right in Xcode: https://developer.apple.com/videos/play/wwdc2016/410/

**Comment by arikis** [comment]
Hi @JuanPabloBoero, many of these memory leaks are fixed as part of our next SDK release. We'll keep looking into them.

**Comment by jeremangnr** [comment]
Any update on this? It's already been 3 months and no news

**Comment by arikis** [comment]
Hello everyone, latest SDK releases fixed many of the memory leaks you've been experiencing, feel free to check them out.
