### ISSUE TITLE
Embarcadero

### ISSUE THREAD

**Issue by icukenvno** [iZettle/sdk-ios#175]
We have iOs application developed in Embarcadero Delphi. Now we need to add the iZettle cards payment functionality to it.  I couldn't manage to use ios SDK  with Embarcadero. could you give some advices on this subject or maybe there are APIs I can use without importing SDK?

                          Thank you

**Comment by arikis** [comment]
Hi @icukenvno, iZettle SDK unfortunately does not support Embarcadero Delphi environment since it's built as a native dynamic iOS framework.
