### ISSUE TITLE
iOS 11 Layout issue in the Header Bar

### ISSUE THREAD

**Issue by Lucconouche** [iZettle/sdk-ios#176]
Our app integrates with the iZettle SDK (v. 1.6.1) and since moving to iOS 11, our users are running into some layout issues while trying to use the iZettle integration.

Here's the header bar under iOS 11

![izettle sdk ios 11](https://user-images.githubusercontent.com/36194/33097162-3d92b3c4-ced7-11e7-9eec-b401edd8d149.jpeg)

Compared to iOS 10

![izettle sdk ios 10](https://user-images.githubusercontent.com/36194/33097180-4ab7a0aa-ced7-11e7-9aef-afce54eec39a.PNG)

**Comment by arikis** [comment]
Hi @Lucconouche, this issue is fixed and it'll be a part of our next SDK release.

**Comment by jeremangnr** [comment]
Hi @arikis, when is this expected to be released? We have been waiting for this new release for almost two months now, this issue is currently affecting some of our customers

**Comment by harryfos** [comment]
HI @arikis this is a significant issue for me as the same bug also seems to cause the status bar to change to white and no longer overlay the background. When is a the new SDK release due?

**Comment by arikis** [comment]
Hey @harryfos @jeremangnr, we have a release scheduled in two weeks

**Comment by harryfos** [comment]
Hi @arikis unfortunately the issue has not been fixed in v1.6.2. Any news on when this will be addressed?

**Comment by Arthus** [comment]
Any update on this issue?

**Comment by valkovsky** [comment]
Hi @Arthus! We are going to release a new version with a fix in this month.

**Comment by arikis** [comment]
All of these issues are now fixed as part of latest release.
