### ISSUE TITLE
UI freezing after successful transaction

### ISSUE THREAD

**Issue by paulgauer** [iZettle/sdk-ios#181]
Hi there, 

as discussed with Lisa from your support:

**Description:**
Our customer reports that, when using the iZettle payment option within our app (Inventorum, which accesses the iZettle SDK V 1.6.1), the App freezes directly after removing the debit/credit card from the terminal. The UI freezes on the Screen „Transaction successful/remove Card“ (the last Step before returning to our Apps own UI), so the customer has to restart the App. No Invoice is created, since the SDK seems to not return anything to our service

**Steps to reproduce:**
1. start transaction in INVENTORUM and choose payment option „iZettle“
2. iZettle UI overlays our app and asks to insert card
3. Customer inserts card and UI asks to enter the PIN
4. After successfully entering the PIN and confirming it with the blue button on the terminal the SDK processes the payment
5. iZettle UI signals a successful transaction and wants the user to remove the card

**expected result:** 
after removing the card, the SDK returns our service, that the payment was successful, including the last digits of the card used. The UI closes and the App moves to our „transaction successful“ screen.

**actual result:** 
after removing the card, the UI keeps showing „remove card“ and does nothing anymore: it basically freezes. Our App has to be restarted. The SDK also returned nothing to our services, so an invoice was not created, but the payment itself was successful and shows up in your Payment-Dashboard

**Notes:**
- The customer is using the iZettle Reader HW Ver. 03.00.00.00.
- The iPad is an iPad Air2 with iOS 11.2.1
- there are also a few other customers affected
- This Bug appears infrequently. here are three examples:

Pls see your support ticket# 01502043 for customer/account details.

For further details/questions, pls contact me or our support (support@inventorum.com) referring to ticket# 37433

**Comment by said-iz** [comment]
Closing since this has been fixed in the later SDK versions
