### ISSUE TITLE
No Cancel Button

### ISSUE THREAD

**Issue by SAM1812** [iZettle/sdk-ios#182]
Hi,

I have integrated iZettle SDK but have a problem. When the app goes to payment page (while waiting for a card to be presented), there is no cancel button. I have seen this cancel button in 
your SDK example, but on our app, there is no cancel button and the title which is “Card Payment” is missing.

Could you please let me know what should I do to have this cancel button there?

![img_0048](https://user-images.githubusercontent.com/35460968/34950862-49305bfe-fa0c-11e7-9016-bf20d2634d9b.PNG)

**Comment by arikis** [comment]
Hey @SAM1812,

Have you used Example app with same SDK version as your application? Also, it would be good to know which iOS and SDK version are you running so we can check more in house.
