### ISSUE TITLE
how unique is panHash?

### ISSUE THREAD

**Issue by Nadejde** [iZettle/sdk-ios#191]
Hi. Can you give me more details about panHash, please. How unique is it? Are you hashing the whole 16 digits or just the last 4? Is anything else going into the hash?
Thank you.
Regards,
Andrei N.

**Comment by elglogins** [comment]
Any updates?

**Comment by Shadowstyler** [comment]
As far as I know, it is randomly generated and PAN is not even taken into calculation.

**Comment by Nadejde** [comment]
@Shadowstyler this is definitely not so. The actual pan number on the card is definitely hashed so you get the same hash if the same card is used twice. However you get multiple cards with the same pan so this hash is not uniquie enought to identify different cards.

**Comment by Shadowstyler** [comment]
Not necessarily. Contrary to its name, the panHash can be calculated using Index tokens and pads instead of the PAN. However, if the PAN would be used it should be hashed in its entirety to comply with PCI DSS requirements.

**Comment by elglogins** [comment]
@Nadejde you mentioned, that multiple cards can get it. How big is the chance for it to happen? I'm slightly concerned now as well, because wanted to use panhash as an identifier of customer.

**Comment by Nadejde** [comment]
We've seen this happen a few times a month in a site that does 600 transactions per day. This is anecdotal as we can't know for sure exactly how often it happens unfortunately with the limited information we get. But we know for sure it can't be used as a unique key for differentiating cards.

**Comment by elglogins** [comment]
Hi @Nadejde ,

Thanks for response. Maybe you have some workaround?

**Comment by arikis** [comment]
Hey @Nadejde @elglogins @Shadowstyler, sorry for the delayed reply. Based on the implementation, the card hash is based on the masked PAN, plus other card details such as name, expiry date etc.

**Comment by elglogins** [comment]
Hi @arikis ,

Is there is any chance for improval on this? For my project it is a showstopper, if we cannot rely on uniqueness of panHash (or some other parameter to identify credit card).

**Comment by elglogins** [comment]
> > Based on the implementation, the card hash is based on the masked PAN, plus other card details such as name, expiry date etc.
> 
> Hi @arikis can you comment at what point this was added in? We know for sure this was not the case a year ago. What we ended up doing is ask for a customer name and used the hash + name to ensure uniqueness.

@arikis would be amazing if you could answer that question, as it is potential show stopper for my project.

**Comment by hey-kj** [comment]
> Hey @Nadejde @elglogins @Shadowstyler, sorry for the delayed reply. Based on the implementation, the card hash is based on the masked PAN, plus other card details such as name, expiry date etc.

This answer is still valid and I am unable to go in to more specific details on the implementation.
