### ISSUE TITLE
Refunds not working through the SDK (1.7.1)

### ISSUE THREAD

**Issue by Nadejde** [iZettle/sdk-ios#198]
# Expected Behavior

Refund to go through without error using the SDK, or a clear error message displaying the problem. Last week this was working fine so it seems to be a new development. 

# Current Behavior

The message "Refund Failed" is displayed without any extra details:
<img width="462" alt="refund failed" src="https://user-images.githubusercontent.com/11600081/39444136-98550960-4cae-11e8-9304-fd58d157534e.png">

The returned error form izettle.refund call is: 
```actualError	NSError	domain: "com.izettle.payment.error" - code: 9	0x000060000065ed80```

# Steps to Reproduce
This fails for any payments I put in and then try to refund. It seems to be a new thing as last week it was working fine.

## Context 

This is my refund code:
```
if
            let store_id = json["store_id"] as? Int,
            let order_id = json["order_id"] as? Int,
            let total_ammount = json["total_ammount"] as? Double,
            let successCallback = json["success"] as? String,
            let errorCallback = json["error"] as? String {
            
            let payment = "{'o':\(order_id),'s':\(store_id)}"
            
            iZettleSDK.shared().refund(
                amount: NSDecimalNumber(value: total_ammount),
                ofPayment: payment,
                withRefundReference: nil,
                presentFrom: self) { [weak weakSelf = self] (paymentInfo, error) in
                    if let actualError = error {
                        weakSelf?.webView.evaluateJavaScript("\(errorCallback)(\(order_id), '\(actualError.localizedDescription)');")
                    }
                    if let actualPaymentInfo = paymentInfo {
                        //var refNumber = actualPaymentInfo.referenceNumber
                        //var authorizationCode = actualPaymentInfo.authorizationCode
                        let jsCall = "\(successCallback)(\(order_id));"
                        weakSelf?.webView.evaluateJavaScript(jsCall)
                    }
            }
        }
```
Watch information:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/11600081/39444277-15db4fac-4caf-11e8-9264-a8ff2f2d03df.png">

The transaction is definitely valid:
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/11600081/39444355-548a38a8-4caf-11e8-8714-f4594c7a7c77.png">

Refunding works fine from your admin website.

* Operating Version: 11.3
* SDK version: 1.7.1

## Failure Logs

No logs are generated in the output. 

Please advise!

**Comment by steelzeh** [comment]
Also experiencing this.

**Comment by arikis** [comment]
Hi @Nadejde, @steelzeh, thank you for reporting this. 

The fix is being deployed on backend service. I will let you guys know as soon as it's done. There will be no need to update SDK.

**Comment by arikis** [comment]
Hi @Nadejde @steelzeh, the issue should be resolved now.
