### ISSUE TITLE
Remove unsupported keys from info.plist

### ISSUE THREAD

**Issue by iUtvikler** [iZettle/sdk-ios#20]
We can`t upload because these two  keys **CFBundleSupportedPlatform** and **CFBundleExecutable**, are not supported.

Deleting the keys from iZettleShared.bundle and iZettleStorePurchase.bundle seems to work.

Similar issue: [gmaps-api-issues](https://code.google.com/p/gmaps-api-issues/issues/detail?id=8568)

**Comment by pushpak** [comment]
any updates on this issue ?

**Comment by jensutbult** [comment]
This has been fixed in version 1.1.1.
