### ISSUE TITLE
When does refund return an error?

### ISSUE THREAD

**Issue by Levaced** [iZettle/sdk-ios#201]
Hi guys,

Currently most errors that I can think of during refundAmount: are shown to the user in the UI of iZettle. But the call can also return an error.

Could someone tell me in which cases this can happen?
I'd like to take appropriate actions if necessary.

**Comment by valkovsky** [comment]
Hi @Levaced,

We've seen your question and we'll come back soon to answer.

**Comment by troligtvis** [comment]
Hello @Levaced,

We return these errors during refund:
- Bad reference
- Cancelled by user
- No Internet

We have created a task to document all errors that might occur so in future SDK releases it will be public.

Thank you for patience and bringing this issue up.
