### ISSUE TITLE
Can't request API key for Payment SDK

### ISSUE THREAD

**Issue by fetzig** [iZettle/sdk-ios#202]
According to this projects README an API key is required to use this SDK.

Supplied link https://www.izettle.com/gb/developer leads to a button "Request API key for Payment SDK".

Submit of said form leads to a js error -> violation Content Security Policy

Can be reproduced with every browser that isn't ignoring Content Security Policy

Workaround

Use browser (add-on) that ignores Content Security Policy

**Comment by vorobievalex** [comment]
The same problem - I just see "Network error." on the form.

**Comment by jalet** [comment]
@fetzig We updated our CSP rules 15 days ago to include that API as well. I'm currently not able to reproduce the issue.

![image](https://user-images.githubusercontent.com/494633/41143361-4567652c-6af9-11e8-8943-8588a00ad16d.png)

@vorobievalex If you see `Network error` it can be anything really (it's a generic response from our backend). Might even be that the email address already is registered.

**Comment by vorobievalex** [comment]
Thank you, @jalet. Changing email resolved the problem.
