### ISSUE TITLE
Card reader not detected by SDK

### ISSUE THREAD

**Issue by mihird** [iZettle/sdk-ios#206]
I have a client trying to use our app (using iZettle SDK).

His card reader (iZettle 190 as appears in Bluetooth) is connected and he is able to use it with official iZettle app. But the reader is not detected by iZettle SDK. Despite many attempts, he continue to get the same error message - "No card reader connected". The client has tried unpairing and repairing the reader with no effect.

The app is using latest sdk, v1.7.1.

**Comment by arikis** [comment]
Hi @mihird,

using the SDK at the same time as iZettle application is not supported. This is because only one app can communicate with one bluetooth device at the same time. 

To be able to use the reader within SDK application, make sure to
* Close the iZettle application
* Have the reader connected in iOS Settings

**Comment by mihird** [comment]
The client already tried uninstalling iZettle Go application and repaired the Bluetooth device, still no luck.

**Comment by leonid-s-usov** [comment]
I am having the same issue after updating from version 1.5 to version 1.7.1 of the SDK. The list of connected devices is empty

**Comment by mihird** [comment]
No @arikis . I have had no luck. I am hoping iZettle will release an updated SDK. I can't think of anything else from my end.

**Comment by arikis** [comment]
@mihird: Which iOS version are you running? Some iOS versions like 11.2 are known to have bugs with EAAccessory framework which we use for bluetooth devices.

**Comment by mihird** [comment]
@arikis  The issue is faced by one of the app user, I will ask him about the iOS version.

Just curious, he is able to use the card reader with the iZettle Go without any issue. So this EAAccessory issue affects only SDK integration?

**Comment by valkovsky** [comment]
@mihird One thing that could help is to try to reset **Networking settings**: `Settings -> General -> Reset -> Reset Network Settings`. 
Note that this will reset all Wi-Fi and cellular settings too.

**Comment by mihird** [comment]
@arikis iOS version is 10.3.3
@valkovsky  I have asked them to reset network settings, will let you know if it solves the issue or not.

**Comment by mihird** [comment]
@valkovsky  The client tried resetting network settings, didn't work. This has put me in a weird position. I can't do anything to help them. I seriously hope somebody is working on the SDK update to resolve this issue asap.

**Comment by mihird** [comment]
@arikis  @valkovsky @izettle-ios-ci @niklas-izettle @xiaodong-izettle @matthew-lowe-izettle  
Please help

**Comment by arikis** [comment]
Hey @mihird, 

We have been unable to reproduce this issue, and we haven’t gotten reports of it happening in other integrators apps. 

Are you by any chance using MultipeerConnectivity framework? We have seen some problems with Bluetooth discovery when this framework is used. 

Other than that, have you tried running it on other device and seeing if the same issue occurs?

**Comment by mortensams** [comment]
@arikis 
Hi,
I am seeing the same issue running running on IOS 12.1 and iZettle SDK 1.7.1
A very basic app just trying to get connection to the card reader. The basic iZettle app works fine.
I have completed the initial step as described her:
https://github.com/iZettle/sdk-ios
- but bringing up the settings screen using 
open func presentSettings(from viewController: UIViewController)

Shows the the UI - but no card reader list - like the basic app.
It gives the option to buy one instead.

br,
Morten Sams
