### ISSUE TITLE
Allow logout via code

### ISSUE THREAD

**Issue by bensebborn** [iZettle/sdk-ios#208]
.

**Comment by bensebborn** [comment]
In previous versions, we could programatically log out the current iZettle user. This behaviour was removed in release and has serious ramifications.

Scenario:

We have a bespoke ePos system. We loan out equipment, which lets customers process orders via their iZettle account.

Equipment is setup at a new event, we log into their ePos account, but the same iZettle account is still logged in. Customers then start processing transactions, to the WRONG iZETTLE ACCOUNT (!)

This is very very hard to spot as nowhere does it show the account the money is flowing to.

As we can be processing £150,000 at a single event, this is a massive risk. Currently we have to ensure that a member of staff starts a transaction on each iPad, goes through and manually logs out of the iZettle account, before logging in with the new details.

It's very open to being missed, with massive ramifications as you can imagine

I realise there is an enforceUserAccount method, however, we don't know the user's izettle details, we ask them to log in directly to the app themselves. Asking them to enter this detail on our platform, then sending it down an API simply to log the current user out is an overkill. Also if it's wrong and needs changing it can't just be done in-situ, someone needs to log into our back end to change the account details which doesnt give a great user experience.

I'm unsure why you can't just provide a [clearUserCredentials] method - surely this is a very different use case to [enforeUserAccount] with a very valid reason for existing?

**Comment by arikis** [comment]
Hey @bensebborn,

thanks for the feedback, we understand the issue. We will look into this and let you know how we will address this.

**Comment by bensebborn** [comment]
Any update @arikis

**Comment by bensebborn** [comment]
Hi guys

This is a big issue for us. Not only does it cause a lot of stress for users to ensure the correct user is logged in, but it's also a data privacy issues

I would go as far as saying that not having the ability to log out a user on a shared system is a massive breach of GDPR regulations.

Is anyone interested in adding this very basic functionality?

**Comment by isabellr** [comment]
Hi @bensebborn ,

Thank you for giving us this feedback! We are actually working of improving our SDK and this feature is definitely high up on our priority list. 
Now that I have you in this thread, is there anything else besides programmatic login/logout that you believe could improve our SDK?

Best,
Isabell

**Comment by arikis** [comment]
Hello @bensebborn, this functionality will be part of the next SDK release which will be released in the next few weeks.
