### ISSUE TITLE
incorrect integration Error

### ISSUE THREAD

**Issue by Repair-Desk** [iZettle/sdk-ios#209]
peyment Error 

# Current Behavior
When attempting to integrate the iZettle SDK in our app, the “Incorrect integration” error appears after using iZettle’s login form provided by the SDK. The issue appears both on the iOS Simulator as well as on our test device, an iPAD  running iOS 11.3..

The Bundle ID of the app is one we submitted to your team earlier.

At launch of the app, in the App Delegate, we use the startWithAPIKey method as follows:

iZettleSDK.shared().start(with: "our-key-as-provided-by-iZettle")

**Comment by troligtvis** [comment]
Hello. Could you please double check if you are using the same `bundle id` in the app which you also submitted in the request for token. [Requirements](https://github.com/iZettle/sdk-ios#requirements)

**Comment by Repair-Desk** [comment]
one more thing  I tried to charge 2 EUR  it shows up integration error .
I have checked that could you please confirm . here is my bundle id "com.rd.RepairDeskiPad" please confirm that on your end .

**Comment by Repair-Desk** [comment]
Moreover the client was trying to charge 2 EUR however it throw integration error.

**Comment by schmee** [comment]
@Repair-Desk I've checked and that is not the same bundle id that you are currently registered with in our system. As stated in the README it is crucial that the bundle id provided in the SDK application matches the one actually used. Please go to https://www.izettle.com/gb/developer and make a new SDK application with "com.rd.RepairDeskiPad" as "Bundle ID" and we'll take it from there.

**Comment by Repair-Desk** [comment]
Thanks for your response. I've tried filling up this form however it throws below error:

![create and innovate with izettle](https://user-images.githubusercontent.com/21986026/43968931-08098172-9ce2-11e8-9fbb-990f2ea2e9cc.png)

**Comment by Repair-Desk** [comment]
An update will be greatly appreciated

**Comment by jakobhenriksson** [comment]
@Repair-Desk From what I can see, applications from SDK keys work as expected. If you haven't, could you please try again and let us know if it still doesn't work.

**Comment by jakobhenriksson** [comment]
Also, @Repair-Desk, if you have tried and it worked, then please re-submit a request with valid details and it will be approved from our side. Thanks!

**Comment by Repair-Desk** [comment]
@jakobhenriksson Thanks for your kind response. We will try to test it again with our customer and see how it goes.

Also i'm trying to fill up this form using Chrome on Mac however it keeps throwing **"network error"**. See below:

![43968931-08098172-9ce2-11e8-9fbb-990f2ea2e9cc](https://user-images.githubusercontent.com/21986026/44076932-697150da-9fbb-11e8-9a69-aec233b4b7fc.png)

Do I need to be in Europe to fill up this form or Is there a way i can email across these details?

I appreciate your help

**Comment by jakobhenriksson** [comment]
@Repair-Desk Thanks for trying again, and sorry it didn't work. We have emailed you, to take the conversation there, because I'm thinking that will be more fruitful. 

Thanks!

**Comment by Repair-Desk** [comment]
@jakobhenriksson thanks for an update 
  we have tried it again with same key which you sent us before . @schmee was saying that our bundle id is wrong , if it is, should we create new one  or you'll update it on your side ?

**Comment by arikis** [comment]
@Repair-Desk did you manage to solve the issue? If so, I'd like to close this issue due to inactivity. Thanks!
