### ISSUE TITLE
Using iZettle SDK on tvOS

### ISSUE THREAD

**Issue by vladmazur** [iZettle/sdk-ios#212]
Hi,

Is it possible to use this SDK on Apple TV?

Since you don't have Android SDK it's much cheaper to buy Apple TV and integrate it with iZettle, rather than buying iPhones for all our stationary vending machines.

**Comment by arikis** [comment]
Hello @vladmazur,

iZettle SDK is currently only supported on iOS devices. We'll update this ticket when there are updates on tvOS support.
