### ISSUE TITLE
Is refund supported outside iOS SDK?

### ISSUE THREAD

**Issue by mobonapps-arunas** [iZettle/sdk-ios#213]
I wanted to ask you what options do you provide to void or refund payments not with iOS SDK but via REST api?

In our use case we are integrating with 3rd party tills and in some cases order can not be fulfilled. We know if that  occurs shortly after order submission (when payment is processed already) and we would like to void such payments quickly.

What is recommended way to handle such case when using iZettle SDKs?

**Comment by arikis** [comment]
Hi @mobonapps-arunas,

Currently, it is not possible to refund a payment outside of iZettle SDK. Usual way of doing it would be through SDK [`refundAmount`](https://github.com/iZettle/sdk-ios#refunding) method.

Thank you for the feedback, we'll take this request into consideration for future.

**Comment by mindaugaspelanis** [comment]
Hello,

any update on this? Maybe the future is already here and you've got that implemented?
