### ISSUE TITLE
Refund asks password each time

### ISSUE THREAD

**Issue by mnerijus** [iZettle/sdk-ios#214]
# Context
I am Nerijus from BPL Digital - we do have self-service ordering Kiosk solution (customer orders food from iPad Kiosk instead of cashier). http://www.bpl-digital.com/kiosk
We have implemented integration with iZettle (so the customer can use Kiosk with iZettle)  iZettle really looks great next to our Kiosk solution! 

However - there is a challenge/problem: 

# Current Behavior
when we try to do an automated refund (customer would get back the money they have paid) - iOS SDK requires enter iZettle password for each refund operation. This is really inconvenient as sometimes we get 20-60 refund operations a day. It means someone should add the password all the time.

# Expected Behavior
We need a setting in your SDK to make this easier. For example - enable to refund without asking a password;

**Comment by arikis** [comment]
Hi @mnerijus, 

Currently, it is not possible to refund a payment without providing a password each time. 

Thank you for the question and the feedback, we'll definitely take this request into consideration for future.
