### ISSUE TITLE
iZettleTransport.framework not loading correctly via cocoapods

### ISSUE THREAD

**Issue by davidhole** [iZettle/sdk-ios#218]
# Current Behavior
App crashes on startup due to iZettleTransport.framework not be found when loading.

# Steps to Reproduce

Run app with iZettleSDK 2.0 installed via CocoaPods

## Context 

It would appear that the podspec is incomplete:

s.vendored_frameworks = 'iZettleSDK/iZettleSDK.framework', 'iZettleSDK/iZettleShared.framework', 'iZettleSDK/iZettlePayments.framework'

should be

s.vendored_frameworks = 'iZettleSDK/iZettleSDK.framework', 'iZettleSDK/iZettleShared.framework', 'iZettleSDK/iZettlePayments.framework', 'iZettleSDK/iZettleTransport.framework'

* Operating Version: 12
* SDK version: 2.0

**Comment by arikis** [comment]
Will update this PR as soon as the new podspec is published

**Comment by arikis** [comment]
Hey @davidhole @EddyVerbruggen, new release containing the fix has just been published to Cocoapods. Thanks for raising the issue!

**Comment by EddyVerbruggen** [comment]
Thank you!

**Comment by davidhole** [comment]
Thanks everyone, that's brilliant :)
