### ISSUE TITLE
Landscape mode unsupported

### ISSUE THREAD

**Issue by meurig** [iZettle/sdk-ios#222]
# Expected Behavior

The iZettle SDK to match the device orientation - ie if the device is in landscape mode when our app calls chargeAmount() then the screen which launches should also be in landscape mode.

# Current Behavior

All iZettle screens are launching in portrait mode, regardless of the orientation of the device.

# Steps to Reproduce

Hold the device horizontally (in landscape mode), then call chargeAmount(), the displayed screen will show on it's side.

## Context 

* Device: iPhone 6 Plus
* Operating Version: iOS 12.0.1
* SDK version: 1.7.1

**Comment by meurig** [comment]
This doesn't seem to be an issue with an iPad mini 1

**Comment by troligtvis** [comment]
Hello, we only support device orientation on iPad.

**Comment by obur-app** [comment]
My iPad keeps rotating to portrait every time the iZettle view pops up. How do I force it to maintain the correct orientation?

Really irritating. Further, after a payment the 'success' modal doesn't disappear so blocks the rest of my app from working...
