### ISSUE TITLE
Password not stored

### ISSUE THREAD

**Issue by nallaperumal** [iZettle/sdk-ios#225]
When the iZettle login is launched, the password is not stored. Everytime user has to enter the password.

We are using the enforceUseraccount feature to set the mail id of the iZettle account. However, the password has to be entered every time by the user, which is annoying user experience.

**Comment by nallaperumal** [comment]
![credentials](https://user-images.githubusercontent.com/4082215/49009040-75963700-f195-11e8-831e-55ff394e1033.PNG)

**Comment by arikis** [comment]
Hello @nallaperumal,

are you by any chance using email that starts with capitalised letter like `Test@test.com`? If that is the case, this is a bug in the SDK which we'll fix shortly, and push out a new release.

Thanks,
Said

**Comment by arikis** [comment]
Hello @nallaperumal, this issue should be fixed now as part of SDK 2.0.2 release!

**Comment by nallaperumal** [comment]
I am not able to install the latest sdk version 2.0.2 through pod. pod is installing only 1.6.2. Why is the pod not installing the latest version?

**Comment by nallaperumal** [comment]
We used two methods to install pod
#(as specified in the readme)
pod 'iZettleSDK'  
and also tried
pod 'iZettleSDK', '2.0.2'

**Comment by nallaperumal** [comment]
Hi team, I am still waiting for the response. Please let me know if you need any further information in it.

**Comment by arikis** [comment]
Hey @nallaperumal,

I just tried running `pod update` with following spec, and it installed the correct version:


```ruby
platform :ios, '8.0'

target 'SDK Sample' do
    pod 'iZettleSDK'
end
```

```bash
$ pod update

Analyzing dependencies
Downloading dependencies
Installing iZettleSDK (2.0.3)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `SDK Sample.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

Not sure what is the issue in your environment – can you try running `pod update` to see if it will fetch latest version?
