### ISSUE TITLE
How to expedite the application process

### ISSUE THREAD

**Issue by mindbrix** [iZettle/sdk-ios#226]
Hi. We have a deadline in 4 days, and we currently have a iZettle API Access request in the works. The turnaround for this is currently 24-48 hours. Is there any way to speed this up?

Many thank.

**Comment by attila-izettle** [comment]
Hi,

Your SDK application has just been approved and you should have got an email. Please let us know if you have any question.

**Comment by mindbrix** [comment]
Many thanks. Can you confirm the email address you used is mcaswelldaniels3@sapient.com? My colleague has not received the message.
