### ISSUE TITLE
https://www.izettle.com/gb/developer - the request an SDK key form gives "Network error'

### ISSUE THREAD

**Issue by mindbrix** [iZettle/sdk-ios#227]
![untitled](https://user-images.githubusercontent.com/177889/49023926-31ecfe80-f190-11e8-9c56-05afcfb1728b.jpeg)

**Comment by isabellr** [comment]
Hi @mindbrix ,

Thanks for reporting this issue. While we look into what the cause of the error is, could you please send your information (the same that you provide in the form) to sdk@izettle.com ? Then we could create an SDK key manually in the meantime.

Best,
Isabell

**Comment by mindbrix** [comment]
Thanks for the reply. I have already followed your suggestion, and we have the necessary credentials.

Best,
      Nigel
