### ISSUE TITLE
Concerning ENABLE_BITCODE

### ISSUE THREAD

**Issue by nikkonikko** [iZettle/sdk-ios#23]
It seems the current framework does not support BITCODE as expected in Xcode 7.0.
Is it possible for you to add it soon?

Thanks in advance.

**Comment by jensutbult** [comment]
The current version (1.1.1) is built with Xcode 6.4 which doesn't support bitcode. The next major release of the SDK will be built with Xcode 7 and if we don't find any issues with bitcode it will be enabled.

**Comment by imrangnit** [comment]
Hi Team,
When you guys are planning to release new framework with bitcode issue fix?

**Comment by mansbernhardt** [comment]
We aim to support bit code in our next major release. We have no current release date for that release, but my current estimate is about a month from now.

**Comment by imrangnit** [comment]
Hi Team,

May i know when you guys are planning to release new SDK to fix BITCODE issue?

**Comment by jensutbult** [comment]
Fixed in version 1.2.1.
