### ISSUE TITLE
SIGABRT crash with abortOperation: after timeout

### ISSUE THREAD

**Issue by mindbrix** [iZettle/sdk-ios#230]
# Expected Behavior

No crash

# Current Behavior

Crash

# Steps to Reproduce

Call `chargeAmount:` and then wait for enough time for it to time out. Call `abortOperation:`

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* iOS 10.2.1
* iZettle SDK 2.0.1

## Failure Logs

Please include any relevant log snippets or files here.

`Assertion failed: (!_completion), function -[IZTask setCompletion:], file /Users/ios/TeamCity/buildAgent/work/e2e4d70b49e0232c/iZettle/Shared/iZettleShared/IZFuture.m, line 110.`

**Comment by mindbrix** [comment]
Thanks. Yes, I have tried 2.0.3 - no change.

All we need to be able to do is to safely abort a payment as we're implementing a Christmas charity donation kiosk which uses an iPhone in headless mode to route payment requests from a server. This is outside the standard use case, so we need some help.

**Comment by valkovsky** [comment]
Hello!
I've tried to reproduce this problem but without any success. Could you specify how exactly you call  methods?

**Comment by mindbrix** [comment]
Hi! I was calling `chargeAmount:` with `[UIViewController new]` to work in pure headless mode. The iPhone will be locked away in a box, with only the iZettle on display. This was a failed guess on my part. I'm now presenting the view controller in the standard way and the system is stable.

Many thanks for your help. You have a great little product.
