### ISSUE TITLE
Card reader 2.0 in-app pairing

### ISSUE THREAD

**Issue by SunSha** [iZettle/sdk-ios#232]
Question:

How to detect if a card reader is connected/paired or not? If not paired then show settings to launch, in-app pair for card reader 2.0. 

If we call chargeAmount without having a card reader connected, there is window shown mentioning 'No card reader connected ' and 2 buttons to buy card reader or get help. I was expecting that it will also show an option to pair a new card reader as well.

Didn't find anything relevant in SDK or docs. Is there any better way?

**Comment by troligtvis** [comment]
Yes for now the only way to know if a reader is connected is by presenting the payment flow. If no reader is connected then as you mention the ''No card reader connected" will be presented. Other way is to go in to settings of the SDK and see the list there.

**Comment by SunSha** [comment]
Thanks for the reply. Do you know how to handle card not connected error, when chargeAmount is called? I am not getting into completion callback but suddenly "no card reader" screen is presented.

 "No card reader connected"dialogue has no options to pair. If I can handle that error then I can show settings. I think it would have been better if there was a method to check the connected card reader and then show accordingly the pair screen.

**Comment by troligtvis** [comment]
Unfortunately that is not possible at the moment. 
We are working on a better solution for this kind of error handling.

**Comment by SunSha** [comment]
Okay, is iZettle card reader 2.0 identifiable using scanForPeripheralsWithServices method ? If yes which service I can look for. I am thinking to get a list of paired Bluetooth devices and show settings accordingly.

**Comment by valkovsky** [comment]
Hi!
We're investigating what can be done to fix the issue and will get back to you soon.

Best,
Andrei Valkovskii

**Comment by arikis** [comment]
Hey @SunSha, the fix has now been released as part of SDK release v2.0.4
