### ISSUE TITLE
iZettle Login Page UI

### ISSUE THREAD

**Issue by PaterB** [iZettle/sdk-ios#233]
Upon updating to SDK 2.0, the UI for login looks like this with the black background. 

(https://user-images.githubusercontent.com/2101808/49699143-8b314500-fc08-11e8-8a35-90a4837afd16.png)

Is this intended? 
I tried running the sample app, but it shows as per normal.

Thanks team.

**Comment by valkovsky** [comment]
Hi!
This is not intended and we're not seeing this issue. Could you please specify iOS version that you use?

Best,
Andrei Valkovskii

**Comment by PaterB** [comment]
Hi Andrei, 
I tried running in simulator and actual device, both giving me the same result. 
They are running iOS 12, compiled using Xcode 9. 
We are upgrading from the older iZettle SDK, so we just replaced the iZettlePayments, iZettleSDK, iZettleShared and added iZettleTransport.

**Comment by troligtvis** [comment]
Hello @PaterB are you by any chance using [UIAppearance](https://developer.apple.com/documentation/uikit/uiappearance) in your app? This might cause this issue.

**Comment by PaterB** [comment]
We probably had set barTintColor for certain view, but not globally. 
Do you think that will affect?

**Comment by arikis** [comment]
Hello @PaterB, did you manage to solve the issue?

**Comment by PaterB** [comment]
Hi Arikis, sorry we didn't manage to fix this.

**Comment by hey-kj** [comment]
We have not seen this before and no new issues regarding this have been reported. I will be closing this for now and hopefully you were able to solve it somehow!
