### ISSUE TITLE
Tokenize card for later charge

### ISSUE THREAD

**Issue by mortensams** [iZettle/sdk-ios#236]
# Expected Behavior
To be able to use i iZettle cardreader to obtain a PAN hash or some other unique identifier to the card. This I would like to use to support checkin/checkout use cases much like when in a car park. Check in is done while swiping the first time. Payment is done when swiping the second time - checkiing out. 

# Current Behavior
As far as I have seen using the SDK, I can only interact with the card reader while charging a payment.

# Steps to Reproduce
THis is not a defect - more a feature request or a clarification.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

IOS SDK version: 2.0.4

**Comment by arikis** [comment]
Hello @mortensams,

currently we don't have support for card tokenization. However, thank you for the feedback—we'll definitely take in consideration for future developments.

Thanks,
Said

**Comment by elglogins** [comment]
Hello,

Maybe there are any updates on particular issue?

**Comment by hey-kj** [comment]
Hello, as of now we still do not have any future plans regarding this feature.

**Comment by NathHorrigan** [comment]
@hey-kj

Is it possible to send a £0.00 charge to the reader to achieve reading the panHash?

This is a killer feature that no services seem to advertise yet developers desperately want it?

Many Thanks!

**Comment by hey-kj** [comment]
@NathHorrigan 

Theoretically it would be possible to do, but we do not have any future plans for developing that kind of feature. 

But we will keep this in mind, thanks for reaching out :)

**Comment by NathHorrigan** [comment]
That's a real shame :(

Looks like I'll have to move to a different service.

I'd highly recommend prioritising such features. Thanks Anyway!

**Comment by StefanKnorn** [comment]
@NathHorrigan , could you outline the value of such a functionality? E.g. the problems it would solve. 
(If you prefer a private discussion, please send us an email on sdk@zettle.com)

**Comment by NathHorrigan** [comment]
Hi @StefanKnorn ,

I've sent an email to sdk@zettle.com from nathhorrigan@gmail.com

Thanks!
