### ISSUE TITLE
ERROR ITMS-90542 and ITMS-90535

### ISSUE THREAD

**Issue by nick671** [iZettle/sdk-ios#24]
I'm trying to submit my application to the app store and got the following errors :
![untitled](https://cloud.githubusercontent.com/assets/1170169/10177737/01f95240-66fc-11e5-97c7-7339a9d244d0.png)

I'm using XCode 7.0

Do you have any way to fix that ?

Thanks

**Comment by jensutbult** [comment]
Which version of the SDK are you using?

**Comment by nick671** [comment]
Sorry it was 1.1.0. I've just upgraded to the 1.1.1 and the issue is fixed.

Thanks
