### ISSUE TITLE
Update 2.0.4 - 2.0.5

### ISSUE THREAD

**Issue by Shadowstyler** [iZettle/sdk-ios#240]
# Carthage
Carthage lists version 2.0.5 but this seems to be missing from changelog. Is this truly 2.0.4.1?

# CocoaPods
CocoaPods still has 2.0.4 from Dec 2018, can this be updated to the latest?

**Comment by sofierPoS** [comment]
I experience the same thing. Have to point to a specific commit to get the 2.0.5 pod

**Comment by arikis** [comment]
Hello @Shadowstyler @sofierPoS, v2.0.5 should be up on CocoaPods now.
