### ISSUE TITLE
Q: Concerning Password & Parring

### ISSUE THREAD

**Issue by nikkonikko** [iZettle/sdk-ios#241]
Hi, 
Could you please add similar to this:

/// If set only an iZettle user with this account will be allowed to be logged in.
@property (nonatomic, copy, nullable) NSString *enforcedUserAccount;

but just for the password, so all employees doesn't have to remember the password?

Also - similar to above - if we could provide the terminal's number, so the parring could be simplified.

**Comment by valkovsky** [comment]
Hi @nikkonikko!

We're aware of the issue and investigating ways to solve it. We will keep this issue open until it's resolved

**Comment by hey-kj** [comment]
As of now we still do not have any plans to implement this feature, but we'll take this in consideration for future developments.
