### ISSUE TITLE
iZettle SDK crash

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#242]
## Context 

We have received a few crash reports, could you please help us investigating the issues?

* Operating Version: iOS 12.2
* SDK version: v2.0.4

## Failure Logs

* Crash Log:
Location: [NSException raise:format:arguments:]
Exception: NSInternalInconsistencyException
Message: Invalid parameter not satisfying: characteristic != nil
Thread: iZettlePayments 

* Crash Log:
Location: [NSException raise:format:]
Exception: NSRangeException
Message: *** -[NSConcreteData subdataWithRange:]: range {8, 60551} exceeds data length 48
Thread: iZettleTransport

**Comment by arikis** [comment]
Hey @asa47, thank you for reporting the crashes. We'll investigate and see what would be the best way to fix them.

**Comment by arikis** [comment]
Hello @asa47,

The fix for the first crash has been delivered as part of the v2.0.5 SDK, so you should be able to update and that crash will be gone.

The second crash will be fixed in near future with a new SDK release.

Thanks,
Said
