### ISSUE TITLE
FEATURE REQUEST : remove Sign Out option when Enforced Account is set

### ISSUE THREAD

**Issue by philatkin** [iZettle/sdk-ios#245]
When Enforced Account is not NULL, the system can be made much more idiot-proof and secure by ensuring that the enforced account cannot be left, as well as ensuring that another account may not be used. 

This way the attendant for the unit will never not need to have access to the password. Once logged in at the start of the day by an approved user, the relatively unskilled operator need simply keep an eye on the unit. 

Please describe the behavior you are expecting.

When Enforce Account is set, the SDK should provide no means for that account to changed, or to be signed out, until Enforced Account is nulled again.

What is the current behavior?

If Enforced Account is set, I can still sign out of the enforced account. 

# Steps to Reproduce

Trigger a call into charge() - Hit CARD, and I see the (i) option at the top right. This presents the Enforced Account name, which quite rightly cannot be edited. HOWEVER - SIgn Out is still presented in red at the top right. I would like that option to be hidden if Enforced Account is not NULL. 

## Context 

I am intending my app to be used in churches, museums, installations where typically the volunteers are old, and are not digitally-skilled. They are not familiar with iPads and passwords, but are perfectly happy with keeping an eye on a piece of equipment in a facility, and spotting potentially malicious behavior. 

I would like to ensure that my app be 100% bulletproof, and there not be any way to sign out, so that these old-school supervisors do not have to know the password, and do not have to be trained on how to log the enforced account back in. Also, from a security perspective, I want as few people as possible to have access to the password, as that could potentially lead to a misdirection of payment in the wrong hands. 

* Operating Version:

iOS 12.2 / iOS 12.3

* SDK version:
Latest

## Failure Logs

Not a failure log, but a feature request for security.

**Comment by arikis** [comment]
Hello @philatkin, thanks for opening up a feature request!

This is something that has been requested previously by some of our SDK integrators, and it doesn't seem like it would be hard to implement from our side. So, this is definitely something we can implement in some of the next SDK releases. I'll update this ticket with new information about the development of this feature request.

Thanks,
Said

**Comment by philatkin** [comment]
Is there an ETA for this update?

**Comment by hey-kj** [comment]
@philatkin 

As of now we do not have any plans to implement this feature, but we'll take this in consideration for future developments.
