### ISSUE TITLE
Crash -[NSConcreteValue iz_isGreaterThan:]:

### ISSUE THREAD

**Issue by kamifernandez** [iZettle/sdk-ios#248]
# Expected Behavior

The App crash in this function  iZettleSDK.shared().charge

# Current Behavior

When I call iZettleSDK.shared().charge in Swift, get this crash

# Steps to Reproduce

Clic on Button with this 

iZettleSDK.shared().charge(amount: amount, enableTipping: self.tippingSwitch.isOn, reference: referenceIdentifier, presentFrom: self, completion:  {(paymentInfo, error) in
            
        })

* Operating Version: 12.1
* SDK version: 

## Failure Logs

2019-06-12 11:38:10.550951-0500 iZettle[6631:1690727] -[NSConcreteValue iz_isGreaterThan:]: unrecognized selector sent to instance 0x2838e4520
2019-06-12 11:38:13.454773-0500 iZettle[6631:1690727] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue iz_isGreaterThan:]: unrecognized selector sent to instance 0x2838e4520'
*** First throw call stack:
(0x22f3faf2c 0x22e5f8284 0x22f3101d0 0x22f400998 0x22f402700 0x1049b67b8 0x1049b6620 0x1054782d0 0x105477c78 0x105477bac 0x105476aa4 0x1054777ec 0x10547823c 0x1049b6330 0x1049b5dac 0x1049b5b7c 0x104a1b9b8 0x1053f67e0 0x1053f564c 0x104a1cb84 0x1054782d0 0x105477c78 0x105477bac 0x105476aa4 0x1054777ec 0x10547823c 0x104a1c584 0x1054939c8 0x105493c9c 0x104a1c2a4 0x10545c874 0x104a1c0e8 0x1053f5338 0x1053f66a8 0x1053f5a64 0x1043b3990 0x1043b3c50 0x22e5f3900 0x25cf93e08 0x25c9faa34 0x25c9fad68 0x25c9f9d08 0x25cfcf680 0x25cfd08e0 0x25cfaed80 0x25d0802a4 0x25d082d5c 0x25d07b69c 0x22f3896a0 0x22f38961c 0x22f388ed4 0x22f383bb4 0x22f383494 0x231636be8 0x25cf9268c 0x1043b54b4 0x22ee39050)

**Comment by getninjaN** [comment]
I had this problem and in my case I managed to fix it by converting my `amount` to a `NSDecimalNumber` with a function like this:
```
func decimal(with string: String) -> NSDecimalNumber {
    let formatter = NumberFormatter()
    formatter.generatesDecimalNumbers = true
    
    return formatter.number(from: string) as? NSDecimalNumber ?? 0
}
```

and then
```
iZettleSDK.shared().charge(amount: decimal(amount), enableTipping: enableTipping, reference: reference, presentFrom: self, completion: { paymentinfo, error in
})
```

Hope this helps or at least gets you on the right path. :)

**Comment by kamifernandez** [comment]
@getninjaN Amazing!, was useful for my, mani thanks

Blessings
