### ISSUE TITLE
Add documentation for possible error codes and error domains upon transaction failure.

### ISSUE THREAD

**Issue by mortenbekditlevsen** [iZettle/sdk-ios#249]
# Feature request

# Expected Behavior
In our app we would like to distinguish between different categories of errors.
For instance we would like to create a concept like 'failed' transactions for errors like invalid pincode - while errors like missing internet should result in a transaction at all.

We would expect some level of documentation about NSError domains and error codes in order to be able to make the most informed choices.

# Current Behavior
By trial and error we currently have some idea about a number of domains and error codes from the SDK, but this is a bit error prone.

# Steps to Reproduce

Lack of documentation for these errors can be seen in the documentation.

# Other comments
I can see that issue #29 also deals with this, but the creator of that issue did not provide a use case. By stating our use case I think that we have a more complete issue.

**Comment by saidsikira** [comment]
Hello @mortenbekditlevsen!

Yes, this is something that we are working on, and that we hope to release some time in the future in form of documentation.

Thanks for the feedback,
Said

**Comment by hey-kj** [comment]
We have defined some of the [errors](https://github.com/iZettle/sdk-ios/blob/master/iZettleSDK/iZettleSDK.xcframework/ios-arm64_x86_64-simulator/iZettleSDK.framework/Headers/iZettleSDK.h#L13-L27) and are continuously working towards improving in this field.

**Comment by mortenbekditlevsen** [comment]
Thank you for the update! ❤️
