### ISSUE TITLE
use_frameworks!

### ISSUE THREAD

**Issue by rasmusth** [iZettle/sdk-ios#25]
Hi.

Integrating with your SDK, we've attempted adding it as a dependency to our private pod handling credit card terminal interaction. This isn't possible due to the fact that your pod doesn't support dynamic frameworks.

In an attempt to circumvent this issue we've added iZettleSDK.framework along with the two bundles, manually to our private pod. Unfortunately the compiled framework attempts to access the bundles from the main bundle, unable to due to the fact that the private pod is a dynamic framework.

We have a client wishing to use this during the weekend, do you have a nightly branch or similar? We do not see tampering with the main application, adding the resource bundles there, as an option.

Hope to hear from you quickly.

**Comment by mansbernhardt** [comment]
We are looking at a potential solution, could a send you an update to rasmus@hummelmose.dk?

**Comment by rasmusth** [comment]
Yes



(null)

**Comment by rasmusth** [comment]
Resolved using experimental build.
