### ISSUE TITLE
SDK v2.2 not picked up by pod update

### ISSUE THREAD

**Issue by sofierPoS** [iZettle/sdk-ios#252]
# Expected Behavior
running pod update on pod file with 
    pod 'iZettleSDK'

should upgrade to latest sdk version 2.2
Please describe the behavior you are expecting.

# Current Behavior
No upgrade is taking place:

    Using iZettleSDK (2.1)

Using latest pod 1.7.4 running on latest MacOS 10.14.5 and latest xcode 10.2.1

**Comment by EddyVerbruggen** [comment]
I was going to be a smartass and say "run `pod repo update`", but it doesn't seem to be published on cocoapods yet: https://cocoapods.org/pods/iZettleSDK, and indeed the latest Podspec is 2.1 as can be seen here: https://github.com/CocoaPods/Specs/tree/master/Specs/b/0/3/iZettleSDK

**Comment by sofierPoS** [comment]
Now it works.
Closing.
