### ISSUE TITLE
Carthage not updated for 2.2

### ISSUE THREAD

**Issue by steelzeh** [iZettle/sdk-ios#254]
https://raw.githubusercontent.com/iZettle/sdk-ios/master/Carthage/iZettleSDK.json

Does not include the updated 2.2 framework.

**Comment by valkovsky** [comment]
Hi @steelzeh!
Thanks for reporting that! We have created a PR with the fix https://github.com/iZettle/sdk-ios/pull/255

**Comment by steelzeh** [comment]
Thanks @valkovsky
