### ISSUE TITLE
Compile SDK for macOS?

### ISSUE THREAD

**Issue by andreasfichtner** [iZettle/sdk-ios#256]
Hi, in XCode 11, Apple makes it possible to compile iOS apps for macOS, do you think you could make your SDK available for macOS this way?

**Comment by saidsikira** [comment]
Hello @retterdesapok, 

Thanks for the question! This is something that we will investigate in the coming months, but no release plans have been made yet.

I'll keep this issue updated to provide more information as soon as we have it.

**Comment by hey-kj** [comment]
I will be closing this issue due to no future plans to implement this functionality.
