### ISSUE TITLE
Warnings from iOS 13 testing

### ISSUE THREAD

**Issue by lieanquintos** [iZettle/sdk-ios#257]
## Context 

After running our app in iOS 13 to test, we got the following logs:

CoreData: warning: Property 'payload' on Entity 'Product' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'productBeforeEditJson' on Entity 'Product' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'payload' on Entity 'TransactionReceiptDetails' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'payload' on Entity 'ZReport2' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'baseURL' on Entity 'Account' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'baseURLs' on Entity 'Account' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'cardPaymentConfig' on Entity 'Account' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'payload' on Entity 'Account' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'sessionCacheJSON' on Entity 'Account' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'tokensForDisplayedInformation' on Entity 'Account' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'backendLayout' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'baseURL' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'baseURLs' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'cardPaymentConfig' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'invoiceConfigurationJson' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'invoiceCustomersPayload' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'invoiceSettingsJson' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'libraryEventLogUuid' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'openCashRegisterJSON' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'payload' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'remoteAppEventsJson' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'sessionCacheJSON' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'suggestedOptionsJson' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'tokensForDisplayedInformation' on Entity 'StoreAccount' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

* Operating Version: 13
* SDK version: 13

**Comment by troligtvis** [comment]
Hi, thank you. We are aware of it but are not going to release any fixes during iOS 13 betas. Fixes will be done in GM of iOS13.
