### ISSUE TITLE
iZettle's view controller hides status bar

### ISSUE THREAD

**Issue by rhummelmose** [iZettle/sdk-ios#26]
When the iZettle SDK presents its modal view controller, it hides the status bar causing the remaining application layout to jump. Is this necessary behavior?

**Comment by mattiasjahnke** [comment]
Hi @rasmusth thank you for your feedback!

We'll look into how we handle the status bar in the next release of the SDK.

**Comment by rasmusth** [comment]
Thank you. Include returns by amount while you're at it 😎

**Comment by mattiasjahnke** [comment]
Hah, yeah it's basically the same code context and all ;)

But improvments to refunds (like a given amount) is definetly in our backlog!

**Comment by mattiasjahnke** [comment]
Picking up on this one @rasmusth - do you still experience a problem with this? The status bar should be visible again when the iZettle UI is dismissed.

**Comment by rasmusth** [comment]
This is a problem because it is visually disturbing for the user when the layout jumps because of the status bar. Why not just let be up to the implementer whether or not it should be there?
