### ISSUE TITLE
IPA processing failed in Xcode 11

### ISSUE THREAD

**Issue by gektron** [iZettle/sdk-ios#262]
Using the latest iZettle SDK version 2.2 and Xcode 11. The project will build and archive. However when attempting to distribute the archive using the enterprise distribution option, the process fails with an "IPA processing failed" error message.

The enterprise distribution works with the previous version of Xcode 10.3, and also works if I remove all references to the iZettle SDK (using Xcode 11).

**Comment by valkovsky** [comment]
Hi @gektron,
Thanks for reporting this. We're taking a look at the problem and trying to reproduce it on our side.

**Comment by valkovsky** [comment]
Hi @gektron,

I think the problem you see is because we distribute the framework as a fat binary file that contains multiple architectures. Did you add `strip frameworks run script` in your app’s target’s “Build Phases?
```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/iZettleSDK.framework/strip-frameworks.sh"
```
More info in Readme.md:
 https://github.com/iZettle/sdk-ios#installation

**Comment by gektron** [comment]
Fixed this now. The strip frameworks script was causing an error because it could not find the embedded iZettle frameworks. I realised I needed to rearrange the order of the build phases so that the embed frameworks phase ran before the run scripts phase.
