### ISSUE TITLE
"Something went wrong" after upgrading to iPadOS13 / XCode 11

### ISSUE THREAD

**Issue by sofierPoS** [iZettle/sdk-ios#265]
# Expected Behavior
Payment popup connects to terminal and start payment

Please describe the behavior you are expecting.

# Current Behavior

What is the current behavior?
iZettle payment popup windows says ""Something went wrong" 
terminal says "Please wait", so clearly connected.
Tried to forget and re-connect terminal, restart App etc. Nothing helps.

# Steps to Reproduce
Start payment 
Please provide detailed steps for reproducing the issue.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version:iPadOS13.1.2
* SDK version:2,2

## Failure Logs

Nothing is logged

**Comment by saidsikira** [comment]
Hello @sofierPoS, 

We are currently investigating this behaviour on iOS 13. I'll update this ticket as soon as we have more information.

Thanks,
Said

**Comment by joshgare** [comment]
@saidsikira do you have any updates on this issue? The iZettle SDK is not functioning for us on iOS 13 and the iZettle iOS SDK is business critical to us.

**Comment by said-iz** [comment]
Fixed in the subsequent SDK releases
