### ISSUE TITLE
'import iZettleSDK' fails after upgrading from 2.2.0 to 2.3.1

### ISSUE THREAD

**Issue by mortenbekditlevsen** [iZettle/sdk-ios#266]
# Expected Behavior

I expected to update from iZettleSDK 2.2.0 to 2.3.1 without any code changes - with just a change in my Cartfile

# Current Behavior

I get a "No such module 'iZettleSDK'" error after updating - whenever I try importing iZettleSDK from Swift.
When reverting to version 2.2.0, the import statement works again.
We are including all 4 binary frameworks from the binary bundle that is downloaded through carthage.

# Steps to Reproduce

Update to iZettleSDK version 2.3.1 through carthage.
Try importing 'iZettleSDK' from Swift code.

## Context 

Xcode 10.3

* Operating Version:
* SDK version: 2.3.1

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by saidsikira** [comment]
Hello @mortenbekditlevsen,

We'll look into this immediately, thanks for reporting this.

**Comment by JulzPolz** [comment]
We are also seeing this using the manual approach.

**Comment by salomo** [comment]
The headers are missing from the framework.
