### ISSUE TITLE
Concerning retrievePaymentInfoForReference method

### ISSUE THREAD

**Issue by nikkonikko** [iZettle/sdk-ios#27]
The method "retrievePaymentInfoForReference" never return (never call the completion block), if nobody is logged in. (It works fine, when logged in)

Also an older version had the method "presentLoginFromViewController:" implemented, so we could force the user to login first - and be sure, the user was logged in - before calling any iZettle operations.

Is it possible for you to add the method again or maybe just add a callback to the method 'presentSettingsFromViewController'?

**Comment by mansbernhardt** [comment]
Thanks for reporting this. This is something we also found out recently, and in our next major release of the SDK "retrievePaymentInfoForReference" has been updated to:

/*! Query iZettle for payment information of a payment with a given reference. */
- (void)retrievePaymentInfoForReference:(NSString *)reference
              presentFromViewController:(UIViewController *)viewController
                             completion:(iZettleSDKOperationCompletion)completion;

**Comment by nikkonikko** [comment]
Perfect. Looking forward to the next release.

**Comment by jensutbult** [comment]
Fixed in 1.2.1.
