### ISSUE TITLE
iOS 13 set isModalInPresentation to TRUE

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#271]
# Expected Behavior

The view controller has been changed in [iOS 13.0+](https://developer.apple.com/documentation/uikit/uiviewcontroller/3229894-ismodalinpresentation). As for now, it is possible to dismiss the iZettle modal by swiping view controller. 

Is there a way to stop this from happening? 
Or to access the view controller and set the `isModalInPresentation` to `TRUE`? 
Or to handle the dismiss event in the iZettle `completion handler`?

# Steps to Reproduce

Trigger the iZettle modal and swipe (pull down the view controller) to dismiss the modal.

## Context 

* Operating Version: iOS 13.0+
* SDK version: v2.3.2

**Comment by saidsikira** [comment]
Hey @asa47, thanks for reporting this; we'll look into this right now.

**Comment by troligtvis** [comment]
@asa47 We've resolved this problem in [2.5.0](https://github.com/iZettle/sdk-ios/releases/tag/2.5.0) release. Now the view controllers `isModalInPresentation` property is set to true.

Please try to update SDK to get the fix.
