### ISSUE TITLE
NSError-object - Try another card

### ISSUE THREAD

**Issue by unkempt** [iZettle/sdk-ios#273]
Hello iZettle team

I would like to capture if a user needs to 'try another card' in my app. Is this possible? Will the reader send this information via NSError?

Hopefully not too tricky. I'm using the ObjectiveC example app at the moment.

Thanks in advance
B

**Comment by saidsikira** [comment]
Hello @unkempt, 

We will investigate what kind of reporting is possible for this use case and get back to you.

Thanks for the question,
Said

**Comment by hey-kj** [comment]
As of now we do not have any plans to implement this feature, but we'll take this in consideration for future developments.
