### ISSUE TITLE
Bluetooth pairing not working on iPadOS 13.x

### ISSUE THREAD

**Issue by MinuteCode** [iZettle/sdk-ios#275]
# Expected Behavior

When trying to pair a card reader 2, the modal should be searching for available card readers

# Current Behavior

When trying to pair a card reader 2, the modal displays that my internet connection is unavailable even though it is or that the bluetooth is of even when it is activated

[![IMG-C6-FD363-D9-C9-D-1.jpg](https://i.postimg.cc/634t4hw4/IMG-C6-FD363-D9-C9-D-1.jpg)](https://postimg.cc/7G4pp05q)

[![IMG-0060.png](https://i.postimg.cc/c4mFqgtV/IMG-0060.png)](https://postimg.cc/jLDHPjXX)

# Steps to Reproduce

1. Open iZettle modal
2. Connect to your account
3. Tap connect card reader
4. Tap on iZettle card reader 2
5. The screenshots above are shown

## Context 

We tried on iPad on iOS 12.2 and everything was working fine, when we updated the iPad to iPadOS 13.x, the connection dialog was not working anymore.

* Operating Version: iPadOS 13.x
* SDK version: 2.3.2

## Failure Logs

No logs

**Comment by valkovsky** [comment]
Hi @MinuteCode,
Thanks for reporting the issue. We've resolved this problem in (2.5.0)[https://github.com/iZettle/sdk-ios/releases/tag/2.5.0] release. Please try to update SDK to get the fix.

Best regards

**Comment by MinuteCode** [comment]
Hi,

Thanks for the fix !
