### ISSUE TITLE
The reader stops displaying the payment value after payment accepted.

### ISSUE THREAD

**Issue by maciejtrybilo** [iZettle/sdk-ios#277]
# Expected Behavior

1. Payment is requested
2. The SDK displays a sheet with with the payment value.
3. The reader displays the transaction value awaiting the card.

# Current Behavior

From one day to another after everything working fine our client reports the following:

1. Payment is requested
2. The SDK displays a sheet with with the payment value.
3. The reader keeps displaying "Hello" or "Connected to iPad..."

The expected behaviour continues on the iZettle app however, just not on our app.

# Steps to Reproduce

Cannot reproduce. A one-off situation.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: 12.2
* SDK version: 2.3.2

## Failure Logs

N/A

**Comment by valkovsky** [comment]
Hello @maciejtrybilo,

Thank you for reporting the issue. The behaviour is strange and not something that we see.
We need more info to figure out what could be the problem:
- As I understand you have problems with iZettle Reader One (the one with blue ribbon)?
- Could you provide bundle identifier of the application that integrates iZettle SDK? It will allow us to trace some logs of back-end requests which could help to clarify the situation.
- Is iZettle Go app installed at the same device with the app that integrates iZettle SDK?

Also we've made great improvements related to iZettle Reader One connectivity in our latest SDK: [2.5](https://github.com/iZettle/sdk-ios/releases/tag/2.5.0). You could try to update the SDK and see if the problem still occurs

**Comment by maciejtrybilo** [comment]
Thank you for quick response!

- It is the  iZettle Reader One. 
- The bundle identifier is com.skipq.staff. 
- The iZettle Go app is installed as it needs to be in order to connect with the One.

The issue seems to be with this particular iPad. We have since managed to connect and process transactions through two different iPhones running our app without any issues to the same reader.

We will get hold of the problematic iPad soon and will be able to dump the logs if that would be helpful. I could also then test with v2.5.

**Comment by valkovsky** [comment]
Thanks for the info! We're going to investigate the problem.

>We will get hold of the problematic iPad soon and will be able to dump the logs if that would be helpful. I could also then test with v2.5.
It would be really helpful. The more information the better :)

>The iZettle Go app is installed as it needs to be in order to connect with the One
It would be interesting to know if there is some kind of interference that is caused by GoApp launched at the same time. It may keep connection to the reader for some time. I may assume to try to kill the GoApp from task manager after it is used to pair a reader.

**Comment by said-iz** [comment]
Hey @maciejtrybilo, are you still experiencing the same issue?

**Comment by maciejtrybilo** [comment]
It's fine now. I guess it was some bluetooth issue caused by the customer playing music from the iPad at the same time. Thank you!
