### ISSUE TITLE
Carthage issue

### ISSUE THREAD

**Issue by steelzeh** [iZettle/sdk-ios#278]
# Expected Behavior

Expected to update my dependencies through Carthage

# Current Behavior

Cannot update my dependencies. Carthage cannot complete updating, because there is some fault with iZettle SDK.

A shell task (/usr/bin/xcrun dwarfdump --uuid /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments) failed with exit code 1:

error: /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments: No such file or directory

# Steps to Reproduce

Try to run this command on Carthage:
carthage update iZettleSDK --platform iOS

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: Mac 10.15.1 / Carthage: 0.34
* SDK version: 2.5.0

## Failure Logs

A shell task (/usr/bin/xcrun dwarfdump --uuid /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments) failed with exit code 1:

error: /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments: No such file or directory

**Comment by saidsikira** [comment]
Hello @steelzeh, thanks for reporting this, I'm looking into it now.

Thanks,
Said

**Comment by steelzeh** [comment]
Thank you for looking into this @saidsikira 

I'm currently getting this error:
A shell task (/usr/bin/xcrun dwarfdump --uuid /Users/.../..../Carthage/Build/iOS/iZettleTransport.framework/iZettleTransport) failed with exit code 1:
error: /Users/.../..../Carthage/Build/iOS/iZettleTransport.framework/iZettleTransport: Invalid data was encountered while parsing the file

**Comment by pisarm** [comment]
I am seeing the same error when doing either `carthage update` or `carthage build`.

Running the 
`/usr/bin/xcrun dwarfdump --uuid /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments`
command on its own produces the following without error:

`
UUID: 2BDACF70-1A3D-3CA5-A276-7A43E251891A (armv7) /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments
UUID: EFACA4A5-09E0-35C9-8E9E-69FF30FC1FAC (arm64) /Users/.../Carthage/Build/iOS/iZettlePayments.framework/iZettlePayments
`

Using
macOS 10.14.6
Carthage 0.34.0
Xcode 11.2.1

**Comment by saidsikira** [comment]
Hello @steelzeh, @pisarm. We've now updated the binaries and the Carthage flow should work correctly now. 

You might still need to clean local Carthage cache by running `m -rf ~/Library/Caches/org.carthage.CarthageKit` which will solve any additional issues you might have.
