### ISSUE TITLE
iZettle SDK overrides UIPageControl tint colors using appearance proxy

### ISSUE THREAD

**Issue by vtim** [iZettle/sdk-ios#279]
After updating the iZettle SDK from v2.3.2 to 2.5.0 we noticed that all UIPageControl instances in our app have the `currentPageIndicatorTintColor` set to the iZettle purple color.

See this screenshot of Xcode's View Debugger:
![Screenshot 2020-01-10 at 16 34 59](https://user-images.githubusercontent.com/357846/72165202-596c4e00-33c7-11ea-9946-e59b669a63bf.png)

Can you confirm if the iZettle SDK is indeed using appearance proxy to style UIPageControl (and possibly other controls), and if so provide an update with a solution?

## Context 

* Operating Version: iOS 13.3, probably any version
* SDK version: 2.5.0

**Comment by saidsikira** [comment]
Hello @vtim,

Thanks for reporting this. It's possible that we are doing this, but it shouldn't be hard to fix. I'll keep this ticket updated with information about new SDK version that will fix this bug.

Thanks,
Said

**Comment by saidsikira** [comment]
Hello @vtim, we've fixed the issue internally and we'll release a patch soon.

**Comment by vtim** [comment]
Thanks @saidsikira, we're eagerly awaiting the patch! Do you have any indication of an ETA?

**Comment by saidsikira** [comment]
Hey! The patch will be released in the next few hours today!

**Comment by saidsikira** [comment]
Hey @vtim! Fix for the issue is now released in SDK v2.5.1!

Thanks for reporting the issue and let us know if you experience other ones.
Said

**Comment by vtim** [comment]
Thanks for the quick turnaround @saidsikira. I confirm the issue is fixed, so I'm closing this issue.
