### ISSUE TITLE
Where can i find libiZettleSDK.a?

### ISSUE THREAD

**Issue by carlosdioxinet** [iZettle/sdk-ios#28]
I'm setting up an application that uses iZettle, but i cannot find libiZettleSDK.a file that docs marks as dependency.

**Comment by mansbernhardt** [comment]
Start with

### 2. Include the following framework and bundles in your project

    iZettleSDK.framework
    iZettleShared.bundle
    iZettleStorePurchase.bundle

Make sure that the bundles are included in the “Copy Bundle Resources” build phase.


Then libiZettleSDK.a should show up in your "Link Binary With Libraries"

**Comment by mattiasjahnke** [comment]
@carlosdioxinet the libiZettleSDK.a is part of iZettleSDK.framework - the docs are a bit misleading. Get back to us if you encounter any problem during your integration.
