### ISSUE TITLE
Our app regularly crashes with iZettle SDK 2.5.2

### ISSUE THREAD

**Issue by sanidaloco** [iZettle/sdk-ios#285]
# Expected Behavior

No crash happens.

# Current Behavior

The app crashes very often since the update to 2.5.2 SDK. A lot of the crashes happen after initializing the iZettle SDK. See attached image of stacktrace.

# Steps to Reproduce

Not consistently reproducable on our end.

## Context 

We see this crash happening for most of our customer multiple times a day. This crash started happening after our latest App release. This release contained an update to the latest iZettle SDK release 2.5.2.

* Operating Version: iOS 12 / iOS 13
* SDK version: 2.5.2

## Failure Logs

<img width="1007" alt="Screenshot 2020-02-14 at 15 09 01" src="https://user-images.githubusercontent.com/43786937/74538578-cfbb1d80-4f3c-11ea-80a5-ba1f6bb18267.png">

**Comment by joarwilk** [comment]
Im getting the same thing

**Comment by valkovsky** [comment]
Hi! We're checking out what is the problem. Based on the screenshot it is hard to know what is the reason since it is not symbolicated. If it is possible, could you provide crash logs, please? We'll try to re-symbolicate them and see exactly what code causes crashes.

Thanks!

**Comment by said-iz** [comment]
Hello @sanidaloco, @joarwilk!

We've now fixed the issue and the new release will be out today.
