### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by beninabox** [iZettle/sdk-ios#287]
# Expected Behavior

Upon going to 'Connect card reader', the screen should have either Dark Mode supported (therefore UI is adjusted to suit dark mode) or light mode should be forced.

# Current Behavior

Upon going to 'Connect card reader', the cells which display the card reader type have a dark background whereas the rest of the screen does not. Similarly, the 'iZettle Reader 2' screen has a dark background when the rest of the flow is not designed accordingly.

# Steps to Reproduce

Ensure the user is on iOS 13, launch the settings screen with dark mode turned on
Tap 'Connect card reader', observe.

## Context 

Dark mode must be on.

* Operating Version: iOS 13.3.1
* SDK version: v2.5.2

## Failure Logs

See screenshots
![IMG_0596](https://user-images.githubusercontent.com/35425808/76096534-2bb61680-5fbe-11ea-8c8e-7bf9270c29ad.PNG)
![IMG_0595](https://user-images.githubusercontent.com/35425808/76096569-3a043280-5fbe-11ea-81f1-d48981c2f13b.PNG)

**Comment by said-iz** [comment]
Hello @beninabox, we'll try to fix this issue soon by enforcing the light mode, thanks for reporting it!

**Comment by beninabox** [comment]
@said-iz That would be great, thanks for addressing :)

**Comment by beninabox** [comment]
@said-iz Any progress? It's been three months since I reported this.

**Comment by said-iz** [comment]
Hey @beninabox! The fix for this issue will be rolled out in our SDK 3.0 release that's coming out in the first week of July.

**Comment by beninabox** [comment]
Super! Very excited :)

**Comment by said-iz** [comment]
Fixed in SDK 3.0 :)
