### ISSUE TITLE
Blank screen from AccountList

### ISSUE THREAD

**Issue by steelzeh** [iZettle/sdk-ios#288]
# Expected Behavior

One of our customers is trying to do a payment via the iZettle SDK, but for some reason he has been logged out. And sees the Account List, but when he presses on the account, the SDK just shows a blank screen.

![2020030710471680292511](https://user-images.githubusercontent.com/7465835/76141164-f531d780-6061-11ea-936d-e193c8570be5.jpg)

Multiple users are also experiencing the UI stuck on "Configuring Terminal"

<img width="1258" alt="Screenshot 2020-03-07 at 11 31 57" src="https://user-images.githubusercontent.com/7465835/76141839-2c0aec00-6068-11ea-8cab-231859f3dc48.png">

# Current Behavior

Blank screen after pressing on an account.

# Steps to Reproduce

Don't really know how this happened, but when the SDK presented the view, he was logged out and when he presses on the account it just shows a blank screen.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: iOS 13.3.1
* SDK version: 2.5.3

**Comment by said-iz** [comment]
Hello @steelzeh ,

We're currently investigating this and we'll update the ticket with more information soon. Are the customers still experiencing the issue? I see that some of the linked accounts are taking payments right now.

Thanks,
Said

**Comment by steelzeh** [comment]
@said-iz I have updated the original Ticket on Jira Service Desk. Could you look into it?

**Comment by said-iz** [comment]
Hey @steelzeh, this should be now fixed in the SDK 3.0 release
