### ISSUE TITLE
Login Issues 

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#289]
# Expected Behavior

To be able to login successfully.

# Current Behavior

One of our customers is having login issues. They keep getting an error message every time they login and when they continue they get kicked back to the login.

![iZettle issue](https://user-images.githubusercontent.com/7304626/76513823-c98e6300-644e-11ea-9533-d419e4c7e970.jpg)

# Steps to Reproduce

Login from the iZettle SDK

## Context 

* Operating Version: iOS 13
* SDK version: v2.5.3

**Comment by said-iz** [comment]
Hello @asa47, I'm looking into this right now—it seems that this specific error is thrown by `URLSession` object. Do you have any custom networking setup on this device?

**Comment by said-iz** [comment]
@asa47 could you try using different network that you're currently using on that specific device and try it out again?

**Comment by asa47** [comment]
@said-iz Thanks for looking into it! The have changed the network and everything is working fine.
I will close the issue.
