### ISSUE TITLE
Concerning Error codes

### ISSUE THREAD

**Issue by nikkonikko** [iZettle/sdk-ios#29]
Is it possible to get a list of version 1.1.1 error codes for Error Domain=com.izettle.payment.error?

Thanks.

**Comment by mansbernhardt** [comment]
We have no intention to maintain a documentation list of all different error and codes. Any particular reason why you would need that?

From the documentation:

### Errors

iZettle will display any errors that occur during an operation to the user, the NSError-object returned in the operation completion block is only intended to be used by developers for debugging, diagnostics and logging to be able to better communicate errors to iZettle. You should never present the returned errors to the end user.
