### ISSUE TITLE
SIGABRT on iOS 13.3.1

### ISSUE THREAD

**Issue by jozefferko** [iZettle/sdk-ios#290]
Our app implements the iZettle SDK and it used to work just fine, but now when I try to launch it in XCode (11.3.1) on an iPad (13.3.1) it crashes with the following message. 
<img width="767" alt="Screenshot 2020-03-16 at 20 45 37" src="https://user-images.githubusercontent.com/20824772/76794469-65a9c880-67c7-11ea-8432-89aee3eec85c.png">

The app works just fine in simulator. I tried creating a new app with just the SDK installed and still get the same error. Just to make sure I tried installing with both Carthage and pods and iZettle versions 2.3.2 and 2.5.2, no luck.

# Steps to Reproduce
Try to run an app with the iZettle SDK installed on an iOS 13.3.1 device

Sidenote: I read about a similar issue on iOS 13.3.1 that would only appear when using a personal provisioning profile. therefore a personal provisioning profile might be required to reproduce the error, but I cant confirm as I dont have a corporate profile to test on.

**Comment by flawlessBadger** [comment]
Update: works fine with a corporate account
