### ISSUE TITLE
Crash: key cannot be nil 

### ISSUE THREAD

**Issue by sofierPoS** [iZettle/sdk-ios#291]
# Expected Behavior

Settings and payment can be done

# Current Behavior

When iZettle settings or payment is done, the App crashes

# Steps to Reproduce
The terminal is still at customer site, so I only have App log.

e.g. show settings:
iZettleSDK.shared().presentSettings(from: presenter)

## Context 

* Operating Version:13.4.1
* SDK version: iZettleSDK (2.5.2)

## Failure Logs
> 1 <2020-04-23 10:29:27> [FATAL]*** ******* APP CRASH: *** -[__NSDictionaryM setObject:forKey:]: key cannot be nil
> 1 <2020-04-23 10:29:27> [FATAL]*** Stack Trace: (
> 0 CoreFoundation 0x00000001a5b37604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148
> 1 libobjc.A.dylib 0x00000001a5859bcc objc_exception_throw + 56
> 2 CoreFoundation 0x00000001a5b8d0cc 409609CD-8410-38E1-BA5D-BDED609D2018 + 1573068
> 3 CoreFoundation 0x00000001a5b966e0 409609CD-8410-38E1-BA5D-BDED609D2018 + 1611488
> 4 CoreFoundation 0x00000001a5a13f80 409609CD-8410-38E1-BA5D-BDED609D2018 + 28544
> 5 iZettlePayments 0x00000001026df688 -[IZBGTaskManager registerTaskWithName:forKey:expirationHandler:] + 560
> 6 iZettlePayments 0x00000001026df444 -[IZBGTaskManager registerTaskWithName:forKey:] + 64
> 7 iZettlePayments 0x00000001026c8bac __43-[DatecsReader updateConfigurationIfNeeded]_block_invoke + 536
> 8 iZettleShared 0x0000000102921550 __31-[IZFuture(Utilities) onResult]_block_invoke_2 + 20
> 9 iZettleShared 0x0000000102939ca4 __28-[IZFuture(Operations) then]_block_invoke_2 + 64
> 10 iZettleShared 0x00000001029396a0 __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 88
> 11 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 12 iZettleShared 0x000000010293864c -[IZTask setCompletion:] + 272
> 13 iZettleShared 0x0000000102939284 -[IZFuture(Operations) thenComplete:] + 508
> 14 iZettleShared 0x0000000102939c2c __28-[IZFuture(Operations) then]_block_invoke + 120
> 15 iZettleShared 0x0000000102921500 __31-[IZFuture(Utilities) onResult]_block_invoke + 140
> 16 iZettlePayments 0x00000001026c88f8 -[DatecsReader updateConfigurationIfNeeded] + 292
> 17 iZettlePayments 0x00000001026a1cc8 -[IZCardReader connect] + 76
> 18 iZettlePayments 0x00000001026c9c20 __23-[DatecsReader connect]_block_invoke_3 + 104
> 19 iZettleShared 0x0000000102939ca4 __28-[IZFuture(Operations) then]_block_invoke_2 + 64
> 20 iZettleShared 0x00000001029396a0 __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 88
> 21 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 22 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 23 iZettleShared 0x00000001029399c8 __37-[IZFuture(Operations) thenComplete:]_block_invoke.136 + 108
> 24 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 25 iZettleShared 0x00000001029399c8 __37-[IZFuture(Operations) thenComplete:]_block_invoke.136 + 108
> 26 iZettleShared 0x000000010293864c -[IZTask setCompletion:] + 272
> 27 iZettleShared 0x00000001029397b4 __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 364
> 28 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 29 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 30 iZettleShared 0x000000010293986c __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 548
> 31 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 32 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 33 iZettleShared 0x000000010293986c __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 548
> 34 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 35 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 36 iZettleShared 0x0000000102921134 -[IZTask(Utilities) complete:orAbort:onQueue:] + 160
> 37 iZettleShared 0x000000010290eca4 __32-[IZFutureQueue executeNextItem]_block_invoke.65 + 164
> 38 iZettleShared 0x000000010292183c __38-[IZFuture(Utilities) onResultOrError]_block_invoke_2 + 56
> 39 iZettleShared 0x0000000102939f90 __35-[IZFuture(Operations) thenOrCatch]_block_invoke_2 + 56
> 40 iZettleShared 0x00000001029396a0 __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 88
> 41 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 42 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 43 iZettleShared 0x000000010293a414 __31-[IZFuture(Operations) always:]_block_invoke_3 + 120
> 44 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 45 iZettleShared 0x00000001029399c8 __37-[IZFuture(Operations) thenComplete:]_block_invoke.136 + 108
> 46 iZettleShared 0x000000010293864c -[IZTask setCompletion:] + 272
> 47 iZettleShared 0x00000001029397b4 __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 364
> 48 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 49 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 50 iZettleShared 0x000000010293986c __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 548
> 51 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 52 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 53 iZettleShared 0x000000010293986c __37-[IZFuture(Operations) thenComplete:]_block_invoke_2 + 548
> 54 iZettleShared 0x00000001029395d4 __37-[IZFuture(Operations) thenComplete:]_block_invoke.134 + 328
> 55 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 56 iZettleShared 0x000000010293c014 __28+[IZFuture(Operations) any:]_block_invoke_4 + 408
> 57 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 58 iZettleShared 0x000000010293a414 __31-[IZFuture(Operations) always:]_block_invoke_3 + 120
> 59 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 60 iZettleShared 0x00000001029399c8 __37-[IZFuture(Operations) thenComplete:]_block_invoke.136 + 108
> 61 iZettleShared 0x0000000102938ebc -[IZTask complete:orAbort:onScheduler:] + 388
> 62 iZettleShared 0x0000000102921134 -[IZTask(Utilities) complete:orAbort:onQueue:] + 160
> 63 iZettlePayments 0x00000001026c7f1c -[DatecsReader _receiveData:] + 608
> 64 iZettlePayments 0x00000001026d3edc -[IZCoreBluetoothLink didReceiveData:] + 84
> 65 iZettlePayments 0x00000001026cc89c __41-[DatecsBLE didUpdateReadCharacteristic:]_block_invoke + 244
> 66 libdispatch.dylib 0x00000001a57fc9a8 5A83D0CF-8FB9-3727-8A32-012D20A47EC8 + 371112
> 67 libdispatch.dylib 0x00000001a57fd524 5A83D0CF-8FB9-3727-8A32-012D20A47EC8 + 374052
> 68 libdispatch.dylib 0x00000001a57af5b4 5A83D0CF-8FB9-3727-8A32-012D20A47EC8 + 54708
> 69 CoreFoundation 0x00000001a5ab5748 409609CD-8410-38E1-BA5D-BDED609D2018 + 689992
> 70 CoreFoundation 0x00000001a5ab061c 409609CD-8410-38E1-BA5D-BDED609D2018 + 669212
> 71 CoreFoundation 0x00000001a5aafc34 CFRunLoopRunSpecific + 424
> 72 GraphicsServices 0x00000001afbf938c GSEventRunModal + 160
> 73 UIKitCore 0x00000001a9be222c UIApplicationMain + 1932
> 74 Sofier-iPad 0x0000000100a6bdac main + 88
> 75 libdyld.dylib 0x00000001a5937800 876FB49A-BFBA-37BF-AD37-6FFC90F7F981 + 6144
> )

**Comment by valkovsky** [comment]
Hi! 
This crash was fixed in [2.5.3](https://github.com/iZettle/sdk-ios/releases/tag/2.5.3). Please update the SDK to pick up the fix.

**Comment by sofierPoS** [comment]
thanks.
