### ISSUE TITLE
Background task not cleaned up

### ISSUE THREAD

**Issue by marc-index** [iZettle/sdk-ios#295]
# Expected Behavior
When sending our app to the background it should not being killed due a background task.
When reopening the app after a while it should continue working.

# Current Behavior
When sending our app to the background it is being killed after a timeout. This results in that the app is being restarted and our users can't continue straightaway.
This occurs a lot within a business day.

# Steps to Reproduce
- Send an app with the SDK integrated to the background.
- Wait for at least 3 minutes. (This is the time limit the OS allows the app to end it's background tasks)
- Send the app back to the foreground.

The app is now being restarted.

## Context 

Our users started experiencing these restarts when we upgraded the SDK to version 2.5.2.
When upgrading to SDK version 2.5.3 it still occurs while testing.
No restart problems where experienced while using the older version of the SDK (version 2.2).

It's not reproducible when attached to the debugger.

* Operating Version: iOS 12.x and iOS 13.x (Older iOS versions not confirmed)
* SDK version: SDK 2.5.2 and SDK 2.5.3

## Failure Logs

The crashlogs indicates an '0x8badf00d' stacktrace.
See attached logfiles for the start and end of the background tasks.
The message 'No active background tasks to stop' is related to our own background tasks.
It indicated that the task started by the iZettle SDK is not ended within the timelimit or an identifier with value 0 is given.

[log1.log](https://github.com/iZettle/sdk-ios/files/4778894/log1.log)
[log2.log](https://github.com/iZettle/sdk-ios/files/4778895/log2.log)
[log3.log](https://github.com/iZettle/sdk-ios/files/4778896/log3.log)

**Comment by dmilovanovi** [comment]
Hello,

Thank you for informing us and apologies for the inconvenience this has caused.

We have managed to find the source of the issue and are actively working on a fix.

Will keep you updated.

Best,

Dejan

**Comment by dmilovanovi** [comment]
Hello again,

Please make sure to update the SDK to the latest version 3.0 which is scheduled to be released in the first week of July.

This update will among other things include a fix to the issue you have reported and will prevent the app from being "killed" in the background.

Please let me know if you need any further assistance.

Best,

Dejan

**Comment by marc-index** [comment]
Hi Dejan,

Thanks for the quick response and update.
Will close this issue once I updated to version 3.0.

Best regards,
Marc

**Comment by dmilovanovi** [comment]
Hi again,

SDK 3.0 has been released and is now available at https://github.com/iZettle/sdk-ios/releases/tag/3.0.0.

Please have a look and let me know if you need any assistance.

Regards,
Dejan

**Comment by marc-index** [comment]
Hi Dejan,

Thanks for the update.
In my tests SDK version 3.0 resolves our problem.

Best regards,
Marc
