### ISSUE TITLE
App crash after calling the chargeAmount

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#297]
# Expected Behavior

Process a transaction with the chargeAmount method.

# Current Behavior

After calling the chargeAmount method the app crash, and it seems to only affecting the customers with the new iZettle reader V2.
 
# Steps to Reproduce

It's a strange one to replicate, this issue does not appear when using the iZettle reader V1.
But when we used the iZettle reader V2 the app crash after calling the charge amount.

I was able to replicate on our side, but after changing the settings on the reader (master reset, fm update etc..), it seems to be fixed.

It is currently affecting 9 of our customers, but I cant figure out how to resolve it. Any suggestions?

## Context 

* Operating Version: I was able to replicate it on iOS 12.4.1 and iOS 13.4.1
* SDK version: v2.5.3

## Failure Logs

In Xcode I received the following message before the crash:
`Unbalanced calls to begin/end appearance transitions for <IZAccountListController>`

In our app bug monitor, we received the following:
`Exception: NSInvalidArgumentException`
`Message: *** -[__NSDictionaryM setObject:forKey:]: key cannot be nil`
`Crash Location Method: chargeAmount`
`Last Interaction: Display IZPaymentViewController or Display IZTemplateViewController`

Let me know if you need additional informations.
Thanks!

**Comment by dmilovanovi** [comment]
Hi,

We apologize for the inconvenience and thank you for reporting this.

A fix to this issue is coming with the SDK 3.0 update which is scheduled to be released later today or tomorrow latest.

I will inform you with further steps as soon as the update becomes available.

Regards,
Dejan

**Comment by dmilovanovi** [comment]
Hi again @asa47 ,

SDK 3.0 has just been released and can be found at https://github.com/iZettle/sdk-ios/releases/tag/3.0.0.

Please have a look and let me know if you have any questions.

Regards,
Dejan

**Comment by asa47** [comment]
Hello @dmilovanovi, thanks for releasing the new SDK.
I am currently trying to implement the new changes, and I have one question.

In the [developer iZettle page](https://developer.izettle.com/), under the SDK for iOS, it says that the redirect URI is optional.
Does it mean that we dont have to implement the OAuth2 flow on our server? Or is something that we need to do in order to use the SDK?

Regards,
Russ

**Comment by dmilovanovi** [comment]
Hello @asa47,
Apologies for the confusion, redirect URI is mandatory in this case.
Please have a look [here.](https://github.com/iZettle/sdk-ios/blob/master/Migration%20Guide/sdk-3.0-migration-guide.md#get-started-with-new-developer-portal).

Let me know if you have any other questions.

Regards,
Dejan

**Comment by asa47** [comment]
@dmilovanovi Thanks for the quick reply, and yes everything works!
