### ISSUE TITLE
iPhone app and iZettle reader bluetooth connectivity loosing

### ISSUE THREAD

**Issue by alok1upadhyay** [iZettle/sdk-ios#3]
Earlier I was doing some testing with the iPhone app and iZettle and the reader was connected to my phone via Bluetooth but everytime I touched 'Pay' and 'Credit Card' it said no device connected. I then removed the device and re-paired it, but it still had the issue.

After a 2nd time of removing the device and re-pairing it worked. Any ideas?

**Comment by mattiasjahnke** [comment]
Do you have the iZettle app installed on the device or any other app that is also communicating with the card reader (i.e iZettle SDK sample project)?

Make sure there is only one app running that's using the card reader.
