### ISSUE TITLE
Failing compilation Xcode 

### ISSUE THREAD

**Issue by sammcewan** [iZettle/sdk-ios#300]
# Expected Behavior

Project can compile with iZettle 3.0.0 updated.

# Current Behavior

Project fails to compile when targeting device or simulator with iZettle 3.0.0.

Getting error `failed to load module 'iZettleSDK'` and `no such module 'iZettlePayments'`
![image](https://user-images.githubusercontent.com/892149/86984950-14916a80-c1e4-11ea-86a8-8b7a68d98eb6.png)

# Steps to Reproduce

1. Adding iZettle to project using cocopods or manually.
2. Compile. 
3. Compilation fails with shown error.

## Context 

Also tried using Xcode 12 and iOS 14.0 error provided is 

* Operating Version: 13.5 and 14.0
* SDK version: 3.0.0

## Failure Logs

```
/Users/x/Build/Products/Debug-iphonesimulator/iZettleSDK.framework/Modules/iZettleSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:6:8: error: no such module 'iZettlePayments'
import iZettlePayments
       ^
<unknown>:0: error: failed to load module 'iZettleSDK'
```

**Comment by said-iz** [comment]
Hey @sammcewan!

We've found the source of the issue and we'll have a fix in the next few hours. It seems to be an [issue with the Swift compiler itself](https://developer.apple.com/forums/thread/123253) since it cannot differentiate between modules and classes that have the same name. 

I'll update this ticket as soon as we merge the fix.

Thanks,
Said

**Comment by sammcewan** [comment]
Wicked thanks heaps @said-iz!

**Comment by said-iz** [comment]
Hey @sammcewan, we've now pushed a fix for this issue. However, you'll need to delete the CocoaPods cache and re-install the pod again if you use CocoaPods distribution. You can do that by running:

```
cd project
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod install
```

You might also need to delete Derived Data in case you still see compilation errors. 

Manual installation should now work too once you download the latest binaries from the sdk-ios repo.

Thanks and let us know if run into any issues,
Said

**Comment by steelzeh** [comment]
I'm still experiencing this issue, I've just updated to 3.0.0, and i have also tried clearing cocoapods cache. And I'm getting a:

`No such module 'iZettleSDK`

 I've tried creating a new project and integrating iZettleSDK with cocoapods and I'm getting

```
ld: framework not found iZettlePayments.xcframework
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Downgrading to 2.5.3 fixes all issues.

**Comment by valkovsky** [comment]
Hey @steelzeh, 
I'm sorry for inconvenience. I'm not sure why Cocoapods integration is failing.
Could you please share failing sample project? Also could you specify the Cocoapods version you use?

**Comment by steelzeh** [comment]
I've been using 1.9.2, updated to 1.9.3 but does not help. But updating to the 1.10.0.beta.1 fixed my issue?

**Comment by valkovsky** [comment]
I'm not that familiar with cocoapods but I can see that https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.1 version fixed some bugs around `XCFramework`. Maybe one of them affected your integration 🤷

**Comment by steelzeh** [comment]
Alright, no problem, sorry for taking up your time. You can close it again :)

**Comment by valkovsky** [comment]
No worries, sorry for inconvenience :)
