### ISSUE TITLE
Parameter redirect_uri contains URI that is not allowed

### ISSUE THREAD

**Issue by newbiepub** [iZettle/sdk-ios#302]
# Expected Behavior
- Authenticate iZettle user

# Current Behavior
- I got an error about "Parameter redirect_url contains an URI that is not allowed"

# Steps to Reproduce
- A popup opened when I proceed presentSetting func in SDK
<img width="328" alt="Screen Shot 2020-07-12 at 00 53 34" src="https://user-images.githubusercontent.com/14126738/87230432-4b30d600-c3da-11ea-8e95-d058eef93104.png">

## Context 
- I added clientID and callbackURL but I still get that issue

* Operating Version: 13.0
* SDK version: 3.0.0

## Failure Logs

N/A

Thank you and looking forward to your response.

**Comment by said-iz** [comment]
Hello @newbiepub, have you registered your callback url in the [iZettle Developer Portal](https://developer.izettle.com/login?continue=%2F)? More information about this step can be found in our [Migration Guide](https://github.com/iZettle/sdk-ios/blob/master/Migration%20Guide/sdk-3.0-migration-guide.md#get-started-with-new-developer-portal).

Thanks,
Said

**Comment by newbiepub** [comment]
Thank you for your supporting
