### ISSUE TITLE
Missing required architecture x86_64 in file (after upgrading to SDK v3.0.0)

### ISSUE THREAD

**Issue by beninabox** [iZettle/sdk-ios#303]
Hi all, after upgrading to the v3.0.0 SDK, I am unable to build the project at all. I have previously, and will continue to manage the dependency with Cocoapods. This happens for simulator devices only.

# Expected Behavior

I should be able to build the project successfully, albeit with some code changes, as I did with SDK v2.5.3.

# Current Behavior

Unable to build the project.
`ld: warning: ignoring file /Users/username/Projects/ProjectName/Pods/iZettleSDK/iZettleSDK/iZettleSDK.xcframework/ios-armv7_arm64/iZettleSDK.framework/iZettleSDK, missing required architecture x86_64 in file /Users/username/Projects/ProjectName/Pods/iZettleSDK/iZettleSDK/iZettleSDK.xcframework/ios-armv7_arm64/iZettleSDK.framework/iZettleSDK (2 slices)`

# Steps to Reproduce

Have an existing project, managing dependencies with Cocoapods, with iZettle SDK v2.5.3. Then upgrade to the v3.0.0 version as per the migration guide https://github.com/iZettle/sdk-ios/blob/master/Migration%20Guide/sdk-3.0-migration-guide.md

## Context 

* SDK version: v3.0.0

I have tried to integrate the framework with a fresh project, and that builds successfully. 

I can tell from the warning is that it is trying to load the iZettleSDK.framework inside of the armv7_arm64 folder, which is not the correct folder for the simulator. It should be ios-i386_x86_64-simulator folder. 

This is an existing project which already had SDK v2.5.3 integrated and working properly. I'm guessing there are some build settings that are not correctly configured in my project. Any ideas?

**Comment by valkovsky** [comment]
Hi @beninabox,

We've pushed the fix for https://github.com/iZettle/sdk-ios/issues/300 recently without bumping the SDK version and just moved the `3.0.0` tag to the latest commit to include the fix. The reason could be that CocoaPods' cache contains the broken version and CocoaPods cannot fetch the fix since SDK version didn't change. Could you try to clear the cache, update pods again and see if it helps? 
```bash
cd project
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod install
```

**Comment by beninabox** [comment]
Hey @valkovsky - thanks for the prompt reply.

I've executed those commands but still seem to be getting the same result when building.

Please excuse my naivety with XCFrameworks, as I have not used them before. As far as I can tell, we should be linking the .xcframework directly, and not the .framework found within the sub folders? Or should Xcode be figuring out which one to link?

Any other ideas?

<img width="1201" alt="Screenshot 2020-07-15 at 17 29 02" src="https://user-images.githubusercontent.com/35425808/87571988-c5a37380-c6c2-11ea-8130-193a4f596824.png">

**Comment by valkovsky** [comment]
> Please excuse my naivety with XCFrameworks, as I have not used them before. As far as I can tell, we should be linking the .xcframework directly, and not the .framework found within the sub folders? Or should Xcode be figuring out which one to link?

@beninabox That is correct. We should link the `.xcframework` directly and Xcode figuring out what particular framework to link.

>Any other ideas?

I've tried to integrate the SDK using cocoapods with an empty project and it worked fine 🤔. I've used `cocoapods` version 1.9.3 and here is the example of `Podfile`

```ruby
platform :ios, '9.0'

use_frameworks!

target 'PodIntegrationTest' do
    pod 'iZettleSDK'
end
```
 
Could you please check what `cocoapods` version you use? I think, `cocoapods` implemented XCFramework support in 1.9 so the version should be 1.9 or higher.
Also a problem could be in the way a project is set up. Do you use a similar `Podfile` to the one pasted above?

**Comment by beninabox** [comment]
Hey @valkovsky 

Thanks for the reply. 

Likewise, I have also tried to create a brand new project and it integrates nicely without any problem.

I'm using Cocoapods 1.9.3, and have a pod file just like you mentioned there.

Looking at it, it is probably a configuration problem within my project. I'll see if I can track it down and get back to you.

Cheers :)

**Comment by beninabox** [comment]
Okay, so I've got a bit further with it, but still unsure quite why it is not working properly.

For a bit more context, I have a Payments Framework within my workspace which links the iZettle Framework (as does the main the app for the purpose of calling to the configuring in app delegate).

I have recreated the same thing in a new workspace (a framework that links the iZettle framework). That builds and runs absolutely fine. In the framework settings, if I disable the Mac device in the 'Deployment Target' section of the build target, it no longer builds and comes up with the above error. If I reenable it, (or do a git reset --hard) then it still fails to build, even after derived data is cleared.

It seems like odd behaviour, but I am stumped as to why this happens. Maybe the iZettle framework is not supposed to be linked to another framework, but it definitely worked fine in iZettle 2.5.3.

Seen as I can build the framework without this dependency, and my main app target builds fine with the dependency, I might make it call back down to the app via an injected class and make the main app do the work.

It's not ideal, so I was wondering if you might be able to replicate the same thing?

Thanks :)

**Comment by valkovsky** [comment]
It is really odd behaviour :)
I'll try to re-create the project that imports the framework that import the iZettleSDK framework. Maybe I'll be able to reproduce the issue.
Could you also tell which Xcode version you use?

**Comment by beninabox** [comment]
Thanks for trying to replicate it.
I'm currently using Xcode 11.6 (11E708)

**Comment by beninabox** [comment]
Hi @valkovsky . I was reading the latest comments on issue #300, and thought I'd try updating to Cocoapods 1.10.0.beta.1. This seems to have fixed the issue. I'm not sure quite why this fixes it, but I did notice it makes some changes with XCFrameworks. Anyway, all seems good now. :)

**Comment by beninabox** [comment]
Closing as now resolved.
