### ISSUE TITLE
Keyboard behaving erratically

### ISSUE THREAD

**Issue by sammcewan** [iZettle/sdk-ios#304]
# Expected Behavior

Keyboard should be full width and be usable.

# Current Behavior

- Keyboard width is equivalent to the width of the iPad being in portrait rather than landscape.
- Our app is landscape only.
- *The keyboard from this point is unusable within our app, no characters can be entered and we cannot proceed past login due to this nor enter any other text in any other field. The only solution is to reboot the app. Therefore for our users with this device there is no way to login to iZettle.*
- These are not specific to any accounts, it's specific to certain devices in this case an 11 inch iPad Pro in landscape.

# Steps to Reproduce

1. Run on device - Simulator seems okay?
2. Authorise bringing up the login web view.
3. Tap password.
4. Keyboard comes up occupying only some of the screen.

![IMG_3075](https://user-images.githubusercontent.com/892149/87621338-b2e97700-c774-11ea-8f4f-9648e9a448e6.jpg)

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version:
13.5.1
* SDK version:
13.5.1
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Frankatvend** [comment]
The issue is gone after upgrading iPads to iOS13.6

**Comment by sammcewan** [comment]
As @Frankatvend this issue was reproducible on iPads less than iOS 13.6, specifically we were seeing it on iOS 13.5.1. After doing multiple upgrade tests we're satisfied this is resolved in 13.6 and iOS 14.0.
