### ISSUE TITLE
Repeat payment

### ISSUE THREAD

**Issue by newbiepub** [iZettle/sdk-ios#305]
# Expected Behavior
- Keeping charge screen not close after specific time
# Current Behavior
- Close after specific time
What is the current behavior?
- I called func charge then the SDK show the payment screen but it closed in specific time
Please provide detailed steps for reproducing the issue.

## Context 
N/A

* Operating Version: iOS 13+
* SDK version: v3.0.0

## Failure Logs

N/A

**Comment by said-iz** [comment]
Hey @newbiepub! 

Are you referring to the [Repeat Payments feature](https://www.izettle.com/gb/help/articles/2941215-repeat-payments) that is found in the Go app or are you referring to the the card payment timeout? What is the use case that you're trying to solve?

**Comment by newbiepub** [comment]
Hi @said-iz !

I'm referring to the Repeat Payment feature that found in the iZettle Go app. Could I do the same with the iZettle iOS SDK ?

**Comment by saidsikira** [comment]
Currently we don't support the Repeat Payments feature in our SDK since the integrating POS apps need to process the payment results and decide what to do with the receipt. However, it should be fairly easy to implement this yourself by calling `iZettleSDK.charge` method recursively after handling the payment result in your POS app. For example, a super trivial implementation could look something like this:

```swift
func charge(amount: Decimal)
  iZettleSDK.shared.charge(amount: amount, ....) { paymentInfo, error in 
    // Handle payment info and error
    // Call charge method again if error is not user cancellation
   self.charge(amount: amount)
```

Thanks for the feedback! We'll discuss this more internally in the team.

**Comment by newbiepub** [comment]
Thank you very much for your support @saidsikira !
By the way, I have problem in login with staff account. I've login with owner account and accept the permission then when I login with staff account the SDK throw an error

![1c2046f4-5e61-49ac-b667-734bed71bdc8](https://user-images.githubusercontent.com/14126738/89185183-04429480-d5c4-11ea-9d33-62678ac10491.png)

Could you help me with this, please? 

Thank you for your supporting !

**Comment by said-iz** [comment]
@newbiepub we're working on fixing that as we speak! Could you send us the account email to `sdk@izettle.com`?

**Comment by newbiepub** [comment]
Hi @said-iz 
I've sent you the account email. Please have a look at it
Thank you and looking forward to your supporting !

**Comment by dmilovanovi** [comment]
Hi @newbiepub 

The issue with staff accounts not being able to log in has just been fixed.

Please try to log into the SDK using a staff account and let me know if it works for you now.

Thanks

**Comment by newbiepub** [comment]
Hi @dmilovanovi !
Thank you so much for your supporting !
