### ISSUE TITLE
iZettle SDK already started exception

### ISSUE THREAD

**Issue by fweakytad** [iZettle/sdk-ios#306]
# Expected Behavior
Apologies if this might seem like a newbie question but i seem to be stuck in the authentication step of sdk integration on IOS. I would expect the sdk to get authenticated once the app loads and then i should be able to use the authenticated instance to perform other sdk operations like charging etc

# Current Behavior

Currently, whenever the app launches i get a 'com.izettle.payments-sdk-ios.exception' thrown saying 'iZettle SDK already started'

# Steps to Reproduce
I currently attempt authentication in the ViewController's viewDidLoad() function like so:

          do {
            let authenticationProvider = try iZettleSDKAuthorization(
                clientID: "49674ddd-7a42-4d8d-a532-d9cb65bfaa9d",
                callbackURL: URL(string: "iOSmasjidDonationApp://")!)
                iZettleSDK.shared().start(with: authenticationProvider)       
         } catch {
           // Inspect error if any, e.g. callback URL not registered in the Xcode project
           print(error)
         }

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: Xcode Version 11.3.1 (11C504)
* SDK version: v3.0.0

## Failure Logs

2020-07-20 15:57:27.282671+0100 DonationPoint[80658:9501968] IAPDHasLaunched: kIAPAvailableNotification iapdAvailableState 0 -> 0
2020-07-20 15:57:27.282946+0100 DonationPoint[80658:9501968] IAP2DHasLaunched: kIAP2AvailableNotification iap2dAvailableState 0 -> 0
2020-07-20 15:57:27.617266+0100 DonationPoint[80658:9501968] *** Terminating app due to uncaught exception 'com.izettle.payments-sdk-ios.exception', reason: 'iZettle SDK already started'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   iZettleSDK                          0x00000001067318a3 -[iZettleSDK translationDataSource] + 0
	3   iZettleSDK                          0x000000010673083f -[iZettleSDK startWithAuthorizationProvider:] + 61
	4   DonationPoint                       0x00000001063eba90 $s13DonationPoint14ViewControllerC11viewDidLoadyyF + 8656
	5   DonationPoint                       0x00000001063ec3ab $s13DonationPoint14ViewControllerC11viewDidLoadyyFTo + 43
	6   UIKitCore                           0x00007fff47a0ef01 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
	7   UIKitCore                           0x00007fff47a13e5a -[UIViewController loadViewIfRequired] + 1084
	8   UIKitCore                           0x00007fff479781e4 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 160
	9   UIKitCore                           0x00007fff479784e8 -[UINavigationController _startTransition:fromViewController:toViewController:] + 144
	10  UIKitCore                           0x00007fff479793b6 -[UINavigationController _startDeferredTransitionIfNeeded:] + 868
	11  UIKitCore                           0x00007fff4797a721 -[UINavigationController __viewWillLayoutSubviews] + 150
	12  UIKitCore                           0x00007fff4795b553 -[UILayoutContainerView layoutSubviews] + 217
	13  UIKitCore                           0x00007fff4809be5b _runAfterCACommitDeferredBlocks + 352
	14  UIKitCore                           0x00007fff4808c7b4 _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
	15  UIKitCore                           0x00007fff480aa583 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 95
	16  CoreFoundation                      0x00007fff23bd429c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	17  CoreFoundation                      0x00007fff23bd3a08 __CFRunLoopDoBlocks + 312
	18  CoreFoundation                      0x00007fff23bce894 __CFRunLoopRun + 1284
	19  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	20  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	21  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	22  DonationPoint                       0x00000001063f0dbb main + 75
	23  libdyld.dylib                       0x00007fff5227ec25 start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by said-iz** [comment]
Hey @fweakytad!

`iZettleSDK.shared().start(_:)` method should only be called once, preferably after your app finishes launching. If this method is called more than once, it will throw the `iZettle SDK already started` exception that you see here. Usually, we advise calling this method from your AppDelegate's `application(_,  didFinishLaunchingWithOptions:_)` method instead calling it from view controller lifecycle methods like `viewDidLoad`.

Thanks,
Said
