### ISSUE TITLE
Repeat Payment Feature?

### ISSUE THREAD

**Issue by innovationben** [iZettle/sdk-ios#307]
# Expected Behavior

There is no option to activate "repeat payment"?

# Current Behavior

None available

## Context 

Trying to utilise repeat payment feature.

* Operating Version:
* SDK version: 3.0

## Failure Logs

N/A

**Comment by said-iz** [comment]
Hey @innovationben,

We don't support Repeat Payments in our iZettle SDK at the moment. However, it could be implemented fairly easily by calling `iZettleSDK.charge` method recursively as a workaround.

Thanks,
Said
