### ISSUE TITLE
Retrieving payment info doesn't return the gratuityAmount

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#310]
# Expected Behavior

When retrieving a transaction through the SDK, the `gratuityAmount` should have the amount that was inserted as a tips/gratuity.

# Current Behavior

When retrieving a transaction through the SDK, the `gratuityAmount` is uqual to zero:

# Steps to Reproduce

Process a £1 transaction and add £0.10 as tips/gratuity.
Retrieve the transaction with the transaction reference.
It will return the following:
```
{
  "amount":"1.1",
  "gratuityAmount":"0"
}
```

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: iOS 13.5.1
* SDK version: iZettle SDK v3.0.0

**Comment by said-iz** [comment]
Hey @asa47, 

Could you email us the details of the transaction you're referring to to our `sdk@izettle.com` email? In the meantime, I'll try to reproduce this myself and try to see what went wrong.

Thanks,
Said

**Comment by said-iz** [comment]
Hey @asa47, we've found the underlying issue and we'll release the fix for it some time next week.

Thanks,
Said
