### ISSUE TITLE
"Log in" button gets truncated when there is an error message

### ISSUE THREAD

**Issue by Frankatvend** [iZettle/sdk-ios#311]
# Expected Behavior

The "Log in" button is still full visible.

# Current Behavior

The "Log in" button got truncated.
![IMG_0279](https://user-images.githubusercontent.com/44758757/88238809-ce093900-ccd6-11ea-8db5-cd8bf3d1482c.PNG)

# Steps to Reproduce

1. Bring up the login view
2. Input an incorrect password.
3. Tap on "Log in"
4. Wait for the login to fail and the error message occurs 

## Context 

* Operating Version:
13.6
* SDK version:
13.6

## Failure Logs

N/A

**Comment by said-iz** [comment]
Hello @Frankatvend!

Thanks for reporting this issue, I'll forward it to our authentication team and get back to you!

**Comment by said-iz** [comment]
Hello @Frankatvend, the fix for this issue has been released on backend last week 👍
