### ISSUE TITLE
Cannot create account on Loyverse POS

### ISSUE THREAD

**Issue by ritacupaila** [iZettle/sdk-ios#312]
# Expected Behavior
Loyverse user able to sign to iZettle account on Loyverse POS
Please describe the behavior you are expecting.

# Current Behavior
Loyverse user not able to sign to iZettle account on Loyverse POS
What is the current behavior?

# Steps to Reproduce
User follow instruction to use iZettle integration with Loyverse POS according instruction https://help.loyverse.com/help/credit-cards-izettle. 
When adding new account, user adds the email and password and click sign in.
Page reload and remain on the same screen without password. 
User not logged in to iZettle account

Please provide detailed steps for reproducing the issue.

## Context 

User from France, first time try to use Loyverse and Izettle integraton
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: 13.6
* SDK version: 2.5.3

## Failure Logs

Please include any relevant log snippets or files here.
This is code, which starts the payment process. If the customer is not authorized, then authorization occurs (password and email):
[[iZettleSDK shared] chargeAmount:amount
                    enableTipping:NO
                        reference:transaction.refID
        presentFromViewController:parentController
                       completion:^(iZettleSDKPaymentInfo *paymentInfo, NSError *error)
 {
     [self onTransactionComplete:paymentInfo error:error];
 }];
![image](https://user-images.githubusercontent.com/69003398/88940763-d5a97e80-d290-11ea-9da9-215acb7dd6aa.png)

**Comment by said-iz** [comment]
Hey @ritacupaila!

We have revamped our whole authentication process as part of our newest SDK 3.0 release which should fix the issue you're seeing. In the meantime, could you send us the account in question to our `sdk@izettle.com` email so that we can check what's happening behind the scenes?

Thanks,
Said

**Comment by ritacupaila** [comment]
This issue with account details were sent to sdk@izettle.com 30 of July. Can you find my email there?

**Comment by hey-kj** [comment]
I will close this issue and forward this to whom it may concern and hopefully you already has got an answer.
