### ISSUE TITLE
Remove restriction on staffs account

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#314]
# Expected Behavior

In the previous SDK, it was possible to login with a staff account, and to take payments.

# Current Behavior

In the new SDK (3.0.0), it looks like there is a restriction for the staffs account. If a staffs accounts tries to login, it shows the following error message: 
```
code: 403
message: "User not allowed to consent"
```
Would it be possible to remove the restrictions, or to add a setting to allow this feature? 

# Steps to Reproduce

1) Create a staff account.
2) Use the staff credentials to login.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: 13.5.1
* SDK version: 3.0.0

## Failure Logs

<img width="545" alt="Screenshot 2020-08-03 at 17 53 41" src="https://user-images.githubusercontent.com/7304626/89207348-7f02b400-d5b2-11ea-92ab-629c77d90f3e.png">

**Comment by said-iz** [comment]
Hey @asa47, we're working on fixing this right now, I'll update the ticket as soon as we release the fix.

Thanks,
Said

**Comment by said-iz** [comment]
Hey @asa47, this issue should now be fixed, please let us know if you see any issues 👍

**Comment by asa47** [comment]
Hello @said-iz, thanks for the quick response.

I have retested it, but I am receiving the following error message: "You are not an owner of your organisation and cannot approve authorisations. Please use an owner account instead."

Is there anything that we can do to allow it?

**Comment by dmilovanovi** [comment]
Hi @asa47 

Please try to log in with the main account first and after accepting permissions, you'll be able to log in using staff account(s) as well.

Could you try this again and let us know if it works for you now?

Thanks.

**Comment by asa47** [comment]
@dmilovanovi @said-iz Thank you guys! It works!
