### ISSUE TITLE
Change enforced account after calling start()

### ISSUE THREAD

**Issue by uddinr** [iZettle/sdk-ios#315]
Is there any way to set/change the enforcedUserAccount after calling:

` iZettleSDK.shared().start(with: authenticationProvider)` 

Users can set up multiple payment types and each payment type can be associated with a different email account, we want to be able to switch between accounts, but use enforcedUserAccount to restrict logging in using any other account.

We achieved this in the previous version of the SDK but has since changed in version 3.0.0

In this version the enforcedUserAccount is passed on calling start(), but since the SDK can only be started once we cannot change the account.

Any ideas on how we can achieve this?

**Comment by said-iz** [comment]
Hey @uddinr!

The enforced account property of the `iZettleSDKAuthorization` object is now defined through a closure in which you can return an email of the account you want to enforce. To change the enforced account, you must call `logout()` method on the `iZettleSDK` object, which will re-evaluate enforced account passed to the `iZettleSDKAuthorization` object.

For example:

```swift
var enforcedAccount: () -> String = { 
  // define which account to enforce
  return "name@izettle.com"
}

let authenticationProvider = try iZettleSDKAuthorization(
    clientID: "xxx-xxx-xxx-xxx",
    callbackURL: URL(string: "<callback-url>")!,
    enforcedAccount: enforcedAccount)

iZettleSDK.shared().start(with: authenticationProvider)
```

Then, if you want to re-evaluate the enforced account, you need to call:

```swift
iZettleSDK.shared.logout()
```

Alternatively, you can roll your own implementation that will provide SDK with access token of the account you want to use/enforce. There's more documentation about the new APIs [here](https://github.com/iZettle/sdk-ios/blob/master/Migration%20Guide/sdk-3.0-migration-guide.md#new-public-apis), and there's also code examples in the Sample app.

**Comment by uddinr** [comment]
perfect! that works! thank you
