### ISSUE TITLE
Set callback url on developer portal

### ISSUE THREAD

**Issue by nikhilhikeup** [iZettle/sdk-ios#317]
Hi,

I have created a new developer account and added an app with bundle id.
But couldn't find where to add a callback URL.

So anyone can show me where to add callback URL with some screens. That would be very helpful. 

right now when I run the app it gives me an error,
"Parameter redirect_uri contains URI that is not allowed"

<img width="373" alt="1" src="https://user-images.githubusercontent.com/54926001/90756436-0150df00-e2fa-11ea-9b69-fa5b993a79eb.png">

Thanks in advance.

**Comment by isabellr** [comment]
Hi!

When you add your app details in iZettle's Developer Portal, you inform your "App URL". That one needs to match the one you're using in this case. 

Let me know if you need further assistance!

**Comment by said-iz** [comment]
Hey @nikhilhikeup, you can also find more information in our [migration guide](https://github.com/iZettle/sdk-ios/blob/master/Migration%20Guide/sdk-3.0-migration-guide.md#get-started-with-new-developer-portal).

As @isabellr said, you can define Oauth Redirect URL/callback url in the Developer Portal flow when you create new iOS SDK integration. 
<img width="1085" alt="Screenshot 2020-08-20 at 14 23 32" src="https://user-images.githubusercontent.com/60747263/90769676-e88ffb80-e2f0-11ea-8129-869dd11ad484.png">

**Comment by nikhilhikeup** [comment]
Hi @isabellr @said-iz 
I have tried to add in both "Add Url" and "Oauth Redirect URL" one by one but couldn't save for either after adding.
I want to add "izettlepaymentdemo" as a callback URL scheme.

**Comment by said-iz** [comment]
The callback URL should be a valid url, for example `my-app://login.callback`, and it unfortunately cannot start with `izettle` since that is reserved keyword.

**Comment by nikhilhikeup** [comment]
Hi,

I have tried "hikeup://login.callback" & "hike-up://login.callback".
but none of them worked.

**Comment by said-iz** [comment]
Hey @nikhilhikeup, I am able to change OAuth Redirect URL in the `OAuth Redirect URI (optional)` field. Can you verify that you're making this change in the same field?

<img width="422" alt="Screenshot 2020-08-20 at 17 55 13" src="https://user-images.githubusercontent.com/60747263/90795547-76c6aa80-e30e-11ea-9942-512b44a9211c.png">

**Comment by nikhilhikeup** [comment]
Hi @said-iz ,

Yes, it worked this time. Now, I can log in with the iZettle account. Thanks a lot...
Just a quick question what should I do if I need to log in using PayPal account.


Thanks.

**Comment by JoseLuisDavila** [comment]
i have same problem , return this error
<img width="518" alt="Captura de Pantalla 2020-08-20 a la(s) 16 20 20" src="https://user-images.githubusercontent.com/57163113/90827029-1bda8680-e301-11ea-9978-68b3aefa570b.png">

**Comment by nikhilhikeup** [comment]
Hi @said-iz @isabellr 

I have one more question regarding size of newly added frameworks.

I am updating the iZettle SDK in the Xamarin application.

But after successful integration, the size of the .ipa files is around 120mb which was previously 80mb.

So, after upgrading to SDK 3.0. build size incremented from 80mb to 120mb.

Can we do anything about this?

Thanks in advance.

**Comment by said-iz** [comment]
> i have same problem , return this error
> <img alt="Captura de Pantalla 2020-08-20 a la(s) 16 20 20" width="518" src="https://user-images.githubusercontent.com/57163113/90827029-1bda8680-e301-11ea-9978-68b3aefa570b.png">

Hey @JoseLuisDavila, that error indicates that you need to add location keys to your Info.plist app. You can see more documentation on how to fix it [here](https://github.com/iZettle/sdk-ios#23-edit-plist)

**Comment by said-iz** [comment]
> Hi @said-iz @isabellr
> 
> I have one more question regarding size of newly added frameworks.
> 
> I am updating the iZettle SDK in the Xamarin application.
> 
> But after successful integration, the size of the .ipa files is around 120mb which was previously 80mb.
> 
> So, after upgrading to SDK 3.0. build size incremented from 80mb to 120mb.
> 
> Can we do anything about this?
> 
> Thanks in advance.

Hey @nikhilhikeup, I think that the IPA size will be smaller once it's sliced for AppStore. We unfortunately haven't tested how this process works using Xamarin, but we can investigate a bit.
