### ISSUE TITLE
How to conforms iZettleSDKAuthorizationProvider protocol in Xamarin 

### ISSUE THREAD

**Issue by nikhilhikeup** [iZettle/sdk-ios#318]
Hi,

I am implementing iZettle SDK in Xamarin. I have created binding libraries and all converted header files to ApiDefintions.
I am stuck at conforming iZettleSDKAuthorizationProvider protocol in Xamarin.

In short, I want Xamarin ios equivalent of the following code;

 id<iZettleSDKAuthorizationProvider> authorizationProvider = [[iZettleSDKAuthorization alloc]
                                                                 initWithClientID:clientId
                                                                 callbackURL:[NSURL URLWithString:callbackURL]
                                                                 error:&error
                                                                 enforcedUserAccount:^NSString * _Nullable{
        return [AccountManager shared].enforcedUserAccount;
    }];

So anyone can help me then it would be great. 

Thanks.

**Comment by Ankitvaghasiya44** [comment]
Hey Nikhil,

Have you done it?

Thanks
