### ISSUE TITLE
Detect Invalid Currency/Region via SDK

### ISSUE THREAD

**Issue by simonrice** [iZettle/sdk-ios#32]
I'm working on an app is to be used by small businesses around the world, including in countries that iZettle currently doesn't support.

Is there any way to detect that iZettle doesn't support the user's currency or location via the SDK?  This way I can hide the option of taking payment via iZettle from the UI.

**Comment by mattiasjahnke** [comment]
Hi @simonrice 

Currently there is no feature like the one you described, but we'll discuss the possibility to add something like this in the future.
