### ISSUE TITLE
Unable to login with demo credentials received on mail.

### ISSUE THREAD

**Issue by nikhilhikeup** [iZettle/sdk-ios#320]
Hi,
@said-iz 
I have created an app on the portal.
I have received demo account credentials to test payment.
But when I have tried to log in using those credentials it gave me a "Sign-In Failed" msg every time.

![1](https://user-images.githubusercontent.com/54926001/91930730-419f5c80-ecff-11ea-8626-e3638bc80630.png)

Please help me with this as I am not able to test my iZettle integration in application.
Thanks in advance.

**Comment by stagor** [comment]
Hi @nikhilhikeup 
This error appears when an enforced account is set that does not match the account you are signing in with. If you did not change the pre-filled account during sign in, please check letter casing when setting the enforced account because it is case sensitive. Case sensitivity will be removed in future release.

**Comment by nikhilhikeup** [comment]
Hi @stagor 
I haven't used any enforced account.
I have passed an empty string for an enforced account.

**Comment by stagor** [comment]
In the current version any value, including empty string, is treated as a set enforced account. It will be possible to use empty string in future releases, until then it must be set to `nil`.
`iZettleSDKAuthorization(clientID: <clientID>, callbackURL: <url>, enforcedUserAccount: nil)`

**Comment by nikhilhikeup** [comment]
Hi @stagor ,

So you mean to say if I pass the null string it will not consider an enforced account.

Let me try that also.

**Comment by nikhilhikeup** [comment]
Hi,
It worked after setting enforcedAccount to null.
Thanks for the help @stagor

**Comment by ddaddy** [comment]
@nikhilhikeup How long after signing up on the dev portal did you receive your demo account details?

**Comment by nikhilhikeup** [comment]
@ddaddy Actually that's the thing;

I have created multiple apps as I was not able to log in.
But got only one mail with demo credentials.
Other mails didn't come. I have waited for some time.

But I was able to use credentials thatI've got in the mail for any of the apps.

**Comment by ddaddy** [comment]
Thanks.
I haven't had any email with demo account and no response to emailing them. It's not great when you want to crack on with a project.
