### ISSUE TITLE
Hide charging popup

### ISSUE THREAD

**Issue by newbiepub** [iZettle/sdk-ios#322]
Hello,
# Expected Behavior
Hide Charging popup

I have an branding screen for card tapping but iZettle SDK show a popup which left my branding screen behind. Is there any way that I can hide that ?
# Current Behavior

What is the current behavior?

# Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: iOS 12.4.8
* SDK version: SDK 3.0.1

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by hey-kj** [comment]
Hello, 

Short answer is no, there is no way currently to hide any view in the SDK. 

We'll take this in consideration for future developments.
