### ISSUE TITLE
NSKeyedUnarchiveFromData should not be used to for un-archiving and will be removed in a future release

### ISSUE THREAD

**Issue by ddaddy** [iZettle/sdk-ios#323]
Xcode 12 shows several warnings 
```'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release```
which seem to be coming from the iZettle SDK.

<img width="1402" alt="Screenshot 2020-09-29 at 11 43 32" src="https://user-images.githubusercontent.com/1425808/94548720-0bdf8c00-0249-11eb-83a8-850625b1bc41.png">

**Comment by stagor** [comment]
Hi @ddaddy!
Thank you for bringing this up. We are looking into it and will address it in a future release.
// Stanislav
