### ISSUE TITLE
UIWebview Usage

### ISSUE THREAD

**Issue by ArEnSc** [iZettle/sdk-ios#324]
Hey guys, I was wondering, at any-point in your SDK did you guys utilize a UIWebview and if so did you guys deprecate it and replace it with the WKWebview?
Please let me know since, our product depends on yours

**Comment by said-iz** [comment]
Hey @ArEnSc!

The latest versions of the SDK are not using `UIWebView` APIs.

Thanks,
Said

**Comment by ArEnSc** [comment]
Thanks were the previous versions using UIWebView APIs ? Thanks! @said-iz
