### ISSUE TITLE
Crashed: NSPersistentStoreCoordinator

### ISSUE THREAD

**Issue by nikhilpatel7** [iZettle/sdk-ios#327]
# Expected Behavior
Application should not crash.

# Current Behavior
Application crashes on launch.

## Context 
I am using iZettleSDK in iOS application and it crashes MyApp on application launch(not all the time).
as per stack trace it I found that `[[iZettleSDK shared] startWithAPIKey:KEY];` is where it crashes.
Hope you guys will be able to help me out. Thanks

* Operating Version: 13.7.0 (17H35)
* SDK version: 2.1

## Failure Logs
Crashed: NSPersistentStoreCoordinator 0x282755880
0  libdyld.dylib                  0x1b0bc6f40 invocation function for block in dyld3::MachOLoaded::getSlide() const + 118
1  libdyld.dylib                  0x1b0bc4be4 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 160
2  libdyld.dylib                  0x1b0bc6914 dyld3::MachOLoaded::getSlide() const + 120
3  libdyld.dylib                  0x1b0bc7590 invocation function for block in dyld3::MachOLoaded::findSectionContent(char const*, char const*, unsigned long long&) const + 80
4  libdyld.dylib                  0x1b0bc5904 invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 536
5  libdyld.dylib                  0x1b0bc4be4 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 160
6  libdyld.dylib                  0x1b0bc56a4 dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 164
7  libdyld.dylib                  0x1b0bc7518 dyld3::MachOLoaded::findSectionContent(char const*, char const*, unsigned long long&) const + 104
8  libdyld.dylib                  0x1b0bc07f8 dyld3::_dyld_find_unwind_sections(void*, dyld_unwind_sections*) + 120
9  libunwind.dylib                0x1e6c9e92c libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::setInfoBasedOnIPRegister(bool) + 88
10 libunwind.dylib                0x1e6c9e470 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step() + 716
11 libunwind.dylib                0x1e6ca1c1c unwind_phase2 + 188
12 libunwind.dylib                0x1e6ca1b3c _Unwind_RaiseException + 440
13 libc++abi.dylib                0x1b0b7ab90 __cxa_throw + 116
14 libobjc.A.dylib                0x1b0ad1cf8 _objc_exception_destructor(void*) + 354
15 CoreData                       0x1b5715364 -[NSSQLCore initWithPersistentStoreCoordinator:configurationName:URL:options:] + 5464
16 CoreData                       0x1b582b184 __91-[NSPersistentStoreCoordinator addPersistentStoreWithType:configuration:URL:options:error:]_block_invoke + 1476
17 CoreData                       0x1b58378d4 gutsOfBlockToNSPersistentStoreCoordinatorPerform + 200
18 libdispatch.dylib              0x1b0a75524 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1b0a280b0 _dispatch_lane_barrier_sync_invoke_and_complete + 56
20 CoreData                       0x1b5828750 _perform + 184
21 CoreData                       0x1b56cc62c -[NSPersistentStoreCoordinator addPersistentStoreWithType:configuration:URL:options:error:] + 380
22 iZettlePayments                0x108b29f00 -[IZDatabaseManager persistentStoreCoordinator] + 432
23 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
24 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
25 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
26 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
27 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
28 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
29 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
30 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
31 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
32 iZettlePayments                0x108b29fb4 -[IZDatabaseManager persistentStoreCoordinator] + 612
33 iZettlePayments                0x108ad5bf0 +[IZAccount currentAccount] + 204
34 iZettlePayments                0x108ad6204 __29+[IZAccount initiateAccounts]_block_invoke + 64
35 libdispatch.dylib              0x1b0a75524 _dispatch_client_callout + 16
36 libdispatch.dylib              0x1b0a1cdc8 _dispatch_once_callout + 28
37 iZettlePayments                0x108ad617c +[IZAccount initiateAccounts] + 596
38 iZettleSDK                     0x10881ce00 -**[iZettleSDK startWithAPIKey:]** + 868
39 MyApp                        0x104e72c58 -[AppDelegate application:didFinishLaunchingWithOptions:] + 78 (AppDelegate.m:78)
40 UIKitCore                      0x1b4e59c14 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 356
41 UIKitCore                      0x1b4e5b9a0 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 5048
42 UIKitCore                      0x1b4e6123c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1244
43 UIKitCore                      0x1b4605a28 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 148
44 UIKitCore                      0x1b4ab61e8 _UIScenePerformActionsWithLifecycleActionMask + 100
45 UIKitCore                      0x1b460650c __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 196
46 UIKitCore                      0x1b4606014 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 468
47 UIKitCore                      0x1b4606338 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 740
48 UIKitCore                      0x1b4605bf8 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 336
49 UIKitCore                      0x1b460a094 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 188
50 UIKitCore                      0x1b49da2ac +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 812
51 UIKitCore                      0x1b4acf62c _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
52 UIKitCore                      0x1b4609df0 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 140
53 UIKitCore                      0x1b4acf528 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 100
54 UIKitCore                      0x1b4609c58 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 376
55 UIKitCore                      0x1b4479e2c __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 636
56 UIKitCore                      0x1b44789cc -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
57 UIKitCore                      0x1b4479b64 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 220
58 UIKitCore                      0x1b4e5f488 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 540
59 UIKitCore                      0x1b49ff598 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 360
60 FrontBoardServices             0x1b5f3661c -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 424
61 FrontBoardServices             0x1b5f5b194 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 100
62 FrontBoardServices             0x1b5f40bfc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
63 FrontBoardServices             0x1b5f5ae50 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 312
64 libdispatch.dylib              0x1b0a75524 _dispatch_client_callout + 16
65 libdispatch.dylib              0x1b0a1e434 _dispatch_block_invoke_direct$VARIANT$mp + 224
66 FrontBoardServices             0x1b5f7f850 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
67 FrontBoardServices             0x1b5f7f51c -[FBSSerialQueue _queue_performNextIfPossible] + 404
68 FrontBoardServices             0x1b5f7fa44 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
69 CoreFoundation                 0x1b0d2dad8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
70 CoreFoundation                 0x1b0d2da30 __CFRunLoopDoSource0 + 80
71 CoreFoundation                 0x1b0d2d1b8 __CFRunLoopDoSources0 + 184
72 CoreFoundation                 0x1b0d281e8 __CFRunLoopRun + 788
73 CoreFoundation                 0x1b0d27ba8 CFRunLoopRunSpecific + 424
74 GraphicsServices               0x1bae9e344 GSEventRunModal + 160
75 UIKitCore                      0x1b4e633e4 UIApplicationMain + 1932
76 MyApp                      0x105158b78 main + 15 (main.m:15)
77 libdyld.dylib                  0x1b0baf8f0 start + 4

**Comment by hey-kj** [comment]
We have fixed a lot of issues and additional improvements since this version 

Please update to our latest sdk version [3.1.1](https://github.com/iZettle/sdk-ios/releases/tag/3.1.1)
