### ISSUE TITLE
use of undeclared identifier 'iZettleSDKAuthorization'

### ISSUE THREAD

**Issue by johnstan** [iZettle/sdk-ios#328]
# Expected Behavior
Able to compile and run using the "out of the box" authorization solution from iZettle

# Current Behavior
Compile fails, saying that 'iZettleSDKAuthorization' is undeclared - looking inside the framework for iZettleSDK, there is indeed no sign of it in the headers.

# Steps to Reproduce
Follow the example code - cannot compile as this object doesn't exist

## Context 
Compiling as a module under Appcelerator Titanium

* Operating Version: OSX Catalina
* SDK version: 3.0.2

## Failure Logs

N/A

**Comment by nikhilpatel7** [comment]
Have you tried importing library ? Like this 
#import <iZettleSDK/iZettleSDK.h>

**Comment by sammcewan** [comment]
Easily reproducible with Example app on M1 processor. Can we please get this resolved. It's blocking our team from being able to work on our new machines.

**Comment by stagor** [comment]
Hi @johnstan 
I suppose you are able to build a native project but the problem is with compilation of Appcelerator Titanium module?
It might have been a compatibility issue with XCFrameworks, have you tried using the latest version of Titanium, did it solve the compile issue?

**Comment by stagor** [comment]
Hi @sammcewan 
We are currently looking Ito compatibility with M1 Macs and expect to resolve the issue in the coming SDK releasee, meanwhile are you able to build and run on an actual iOS device as opposed to simulator?

**Comment by sammcewan** [comment]
@stagor Correct, excellent. Do you have an ETA for this at all? Thank you.

**Comment by stagor** [comment]
@sammcewan I can unfortunately not provide a time estimate, but we are looking into solving it as soon as possible.
