### ISSUE TITLE
Incompatible Swift Versions

### ISSUE THREAD

**Issue by AngeloMateus** [iZettle/sdk-ios#329]
When building in release scheme I get the following error

### failed to build module 'iZettleSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
import iZettleSDK

Is there something I'm missing?

**Comment by valkovsky** [comment]
Hey @AngeloMateus!

The reason you see the error is that `iZettleSDK` was built using swift version 5.2.4 and your project uses more recent version of swift (`5.3`). We're planning to release a version soon that is going to be built using latest swift compiler bundled with Xcode.
Meanwhile you can try to switch back to swift `5.2.4` if that's possible with your project configuration.

Sorry for inconvenience!

**Comment by AngeloMateus** [comment]
Ok thanks downloading Xcode 11.5.
Any chance you could let me know when the new version comes out?

**Comment by valkovsky** [comment]
You can watch this repository and you'll get notified when the new version is posted :)
