### ISSUE TITLE
EnforcedUserAccount not really enforced

### ISSUE THREAD

**Issue by Ceroce** [iZettle/sdk-ios#330]
Hi,

I'm late to the party, but I've update to the SDK version 3 and thanks to the migration guide, it was almost seamless. Thank you!

However, I don't think the EnforcedUserAccount option works as intended anymore.

# Expected Behaviour

When a EnforcedUserAccount is provided, the SDK should only allow login in with this account.
(I think it's the way it used to work in the v2 of the SDK).

# Current Behaviour

Although the EnforcedUserAccount e-mail address does show in the login field, a "Change" button is shown next to it, allowing to use an other e-mail address.

# Steps to Reproduce

Provide an enforcedUserAccount closure to the 
-[iZettleSDKAuthorization initWithClientID:callbackURL:error:enforcedUserAccount:] method.

## Context 

* Operating Version: iOS 14.2 (French)
* SDK version: 3.0.2

## Failure Logs

Not applicable.

**Comment by stagor** [comment]
Hi Renaud!

Happy to hear that migration was, almost, seamless! If you feel that anything is missing in the migration guide or in the documentation to make it even more seamless - we are happy to hear about it and will do our best to improve.

Regard the `change` button, even though it is there if `enforced account` is used - if a user changes the account and log in with a different account he or she will be prompted with an error saying that wrong credentials were used and prevented from logging in. So in the end the user will only be able to login with `enforced account`.

There are plans to improve upon `enforced account` in the future, to prevented user from changing the email in the first place to reduce confusion.

**Comment by Ceroce** [comment]
I see. I had the experience you describe; although confusing, I consider the behaviour sufficient for our needs. I'm closing the issue.

> If you feel that anything is missing in the migration guide or in the documentation to make it even more seamless - we are happy to hear about it and will do our best to improve
I will.
