### ISSUE TITLE
Send receipt to email via SDK

### ISSUE THREAD

**Issue by matthiasnagel** [iZettle/sdk-ios#332]
Is there a way to send out customer receipts via email like in the regular iZettle app?

**Comment by stagor** [comment]
Hi!
The SDK provides all the necessary information to create a receipt that can, among other things, be sent by email, but the SDK does not provide `send` functionality itself.

**Comment by matthiasnagel** [comment]
Thanks @stagor, currently we are rendering our own PDF receipt from the transaction information. Are there any future plans to offer a send functionality? (I really like the layout of the iZettle receipt)

**Comment by stagor** [comment]
I see, happy to hear that you like it! The idea is considered, but there are no near term plans to do so.
Have a nice weekend!
// Stanislav
