### ISSUE TITLE
AppStore rejects app with reason "UIWebView deprecated" with iZettle version 3.0.1

### ISSUE THREAD

**Issue by nikhilpatel7** [iZettle/sdk-ios#334]
# Expected Behavior
AppStore should not reject app using iZettle 3.0.1 

# Current Behavior
AppStore rejects app with reason "UIWebView deprecated" with iZettle version 3.0.1

# Steps to Reproduce
Add iZettle to pods and do pod install and try to publish app to AppStore.

- To check which library causes issue of "UIWebView deprecated" using below script I found its "iZettle Payments" & "iZettleSDK" : [https://stackoverflow.com/a/57730461/5821989](https://stackoverflow.com/a/57730461/5821989)

Result after running script as proof:

![image](https://user-images.githubusercontent.com/14245315/108589522-a66d7280-7384-11eb-840a-499b605caa38.png)

## Context 
Here is my pod file just for reference : 
![image](https://user-images.githubusercontent.com/14245315/108589381-0b749880-7384-11eb-9686-93fd96d5426a.png)

* Operating Version: 
* SDK version: 3.0.1 (latest)

I am not sure why this is happening and solution to this... Can you guys help me with this or provide a specific version which can work and resolve my issue ? any help would be appreciated. Thanks

**Comment by nikhilpatel7** [comment]
I have also checked after upgrading to 3.0.2 version but same issue. I am not sure if iZettle is ever upgraded with WKWebView changes as UIWebView is deprecated.

**Comment by hey-kj** [comment]
Hello @nikhilpatel7, I have searched through our releases down to [version 1.6](https://github.com/iZettle/sdk-ios/releases/tag/1.6) and was unable to find any references to `UIWebView`. 

But doing further investigation from the pods you are using it seems that `ZBarSDK` might be the culprit of still using `UIWebView`, there is an open ticket at [ZBar repo](https://github.com/ZBar/ZBar/pull/21).

**Comment by nikhilpatel7** [comment]
I had that issue with `ZbarSDK`, So after bit of investigation I found a branch with WKWebView changes to a specific commit which you can see in the pod file. @hey-kj  What you are suggesting is not the case.

This might or might not be the issue with iZettle. Can you guide me about anything that can help?

**Comment by hey-kj** [comment]
@nikhilpatel7 I see! Well with my previous experiences with cocoapods there could be some kind of caching problem. What you could try to do is to remove `pod iZettleSDK` and do `pod install` (to remove) then again add it. Or perhaps specify which version you'd like to use.
