### ISSUE TITLE
Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)

### ISSUE THREAD

**Issue by sanchyanchakraborty** [iZettle/sdk-ios#338]
Hi,

New iZettle SDK works perfect with ios 14 Devices.
But when I start my app in below ios 14 Devices, I tried on ios 13 & ios 12 Devices
In appDelegate didFinishLaunchingWithOptions method
iZettle Provider Code is throwing this error and stops.

`Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)`
I used this code, and it's working perfect on ios 14 Devices.

```
id<iZettleSDKAuthorizationProvider> authorizationProvider = [self makeAuthorizationProvider];
        [[iZettleSDK shared] startWithAuthorizationProvider:authorizationProvider];
```

![Screenshot 2021-03-28 at 10 14 36 AM](https://user-images.githubusercontent.com/52530756/112742703-5058a400-8fae-11eb-8006-45146a4c7817.png)

**Comment by sanchyanchakraborty** [comment]
Hi,

New iZettle SDK works perfect with ios 14 Devices.
But when I start my app in below ios 14 Devices, I tried on ios 13 & ios 12 Devices
In appDelegate didFinishLaunchingWithOptions method 
iZettle Provider Code is throwing this error and stops.

`Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)`

I used this code, and it's working perfect on ios 14 Devices.

```
id<iZettleSDKAuthorizationProvider> authorizationProvider = [self makeAuthorizationProvider];
        [[iZettleSDK shared] startWithAuthorizationProvider:authorizationProvider];
```

![Screenshot 2021-03-28 at 10 07 48 AM](https://user-images.githubusercontent.com/52530756/112742581-5e59f500-8fad-11eb-91b6-17ead48ebdfd.png)

**Comment by valkovsky** [comment]
Hi,

We've checked the new version 3.1 on different devices including iOS 12 and iOS 13 and we didn't encounter any issues. Could you please provide a sample Xcode project that reproduces the issue you have?

**Comment by valkovsky** [comment]
Also are you using simulators or real devices?

**Comment by avalkovskii-pp** [comment]
Hey! This issue is fixed by https://github.com/iZettle/sdk-ios/releases/tag/3.3.1.
