### ISSUE TITLE
Invalid CFBundleSupportedPlatforms value

### ISSUE THREAD

**Issue by Andrenalin** [iZettle/sdk-ios#34]
We got an error back from the iTunes Connect Upload.

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/***.app/iZettleShared.bundle' contains an invalid value '( "iPhoneSimulator" )'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Please can you fix this issue. It is happened with the version 1.2.0.

Thank you
Andre

**Comment by mansbernhardt** [comment]
Ok thanks for reporting. It seems that the fix for 1.1.1 for some reason has found its way back. We will fix this the first thing in the morning and release an update.

Ping @jensutbult

**Comment by Andrenalin** [comment]
Thanks,
Andre

**Comment by jensutbult** [comment]
Fixed in 1.2.1.
