### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by tarun1April** [iZettle/sdk-ios#351]
Not able to login if signout from izettle settings using method
[[iZettleSDK shared] presentSettingsFromViewController:self]

If I signout from zettle setting then invoke the method name presentSettingsFromViewController:, after that sign-in loader keeps loading and screen stucks. Please help us in this regard.

**Comment by hey-kj** [comment]
Hello @tarun1April 

Could you please fill in the provided template in order for us to know more about the issue and be able to help you with your issue.

--- 

# Expected Behavior

Please describe the behavior you are expecting.

# Current Behavior

What is the current behavior?

# Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version:
* SDK version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by tarun1April** [comment]
Expected Behavior

1. Before calling the method [[iZettleSDK shared]
presentSettingsFromViewController:self]  to open the iZettle setting view,
there should be an option to check whether the user login or a login screen
should be open as also followed by other methods of iZettleSDK i.e, charge
amount or refund amount.

2. In case if loader keeps loading with sign-in,  then it automatically
timeout after few seconds.
Current Behavior
1. Sign-in loader keeps loading, after sign-out from the iZettle Setting
view.
2. Loader should have time out, so that loader automatically canceled after
few seconds because it hangs on our screen.
3. In this case, there is no other way to handle this situation, only the
way is, we have to kill the app, which is not good.

Please check the screenshot for reference.
[image: Step4.png]
Steps To Reproduce

1. Using the iZettleSDK method to present iZettle settings in my POS App.
[[iZettleSDK shared] presentSettingsFromViewController:self]

2. After this iZettle Settings view controller is presented in my POS App.

3. Then I press the option sign out from iZettle Setting view.

4. Now the status is logged out.

5. After this I again called the method [[iZettleSDK shared]
presentSettingsFromViewController:self].

6. Now a loader is shown loading with sign-in text and not able to cancel
that loader. To cancel the loader I have to kill the POS App, which is not
correct.

7. After signout from the iZettle setting view, there is no option to log
in. In the case of log out, the login screen should be open or there should
be an option to check whether the user is login or logout.

As you can see in the screenshot for reference.

1.
[image: Step1.png]


2.
[image: Step2.png]

3.
[image: Step3.png]

4.
[image: Step4.png]


Context

   - Operating Version:  iPad iOS v 12.5
   - SDK version: 3.0.2

**Comment by hey-kj** [comment]
@tarun1April 

Thank you for the details. I will try this out and get back to you 👍

**Comment by hey-kj** [comment]
@tarun1April 

Hello again, we are unable to reproduce this with the instructions you gave us. 

Could you try to update the SDK to the latest, which is `3.1.1`.
Also make sure that you handle the `iZettleSDKOperationCompletion` result from the SDK api calls. 

I will keep the issue open for the time being and wait for your response.

**Comment by hey-kj** [comment]
@tarun1April 

Can I assume this issue has been solved due to other issues you have opened which has a prerequisite of being logged in?
#352 #353

**Comment by tarun1April** [comment]
This is a different issue from #352 and #353. This issue occurs because my
present *viewcontroller* is not using *navigationcontroller*. Here, login
uses  SFSafari called with *navigationcontroller.*

**Comment by hey-kj** [comment]
@tarun1April 

It is hard to figure out the reason for your issue based on your answer. Do you have a code snipper or sample project we could look at?

**Comment by tarun1April** [comment]
In this case, please use the **ViewController** without using **navigationController** and then call the method **[[iZettleSDK shared]
presentSettingsFromViewController:self]**. With this, you can replicate the issue.

**Comment by hey-kj** [comment]
@tarun1April 

I am still unable to reproduce your issue, even though I try with your latest example.

I am presenting the sdk settings from an UIViewController which is not embedded in an UINavigationController, everything is working as expected.

Could you perhaps upload some images or video on the issue? Or a sample project.

**Comment by tarun1April** [comment]
I create a demo App to create the same scenario to replicate the issue and later I found that this is an App-specific issue, not an SDK-related issue. I solved this issue in my App. Thanks for your help. Please close the issue.

**Comment by tarun1April** [comment]
And please help us to reply #353

**Comment by tarun1April** [comment]
#351. Please close this issue.
