### ISSUE TITLE
Refund not working.

### ISSUE THREAD

**Issue by tarun1April** [iZettle/sdk-ios#352]
# Expected Behavior

1. As we know, we have to use iZettleSDK method -(void)refundAmount to refund the payment. But Refund is not working, after press the confirm button from Refund view open by the iZettleSDK.
 2. Atleast provide any kind of logs or error or exception or response, so that we can abort if any kind of failure happened.

# Current Behavior

1. Refund not working, it stucks the POS App.
2. Not able to cancel the Refund view.
3. Not getting any kind of response/error/exception/log after invoking the izettleSDK method for refund i.e., -(void)refundAmount:

# Steps to Reproduce

1. After calling the refundAmount method of iZettleSDK, Refund view is open with webview. 
2. Correct details are visible in Refund view.
3. Press the confirm button in Refund view.
4. Then a progress indicator line visible in webview, which is behind the refund view provided by iZettleSDK.
5. After this we are waiting for an hour and nothing happens. Not getting any kind of response from -(void)refundAmount:
6. Here, our POS App stuck and we have to kill the app.

Please provide detailed steps for reproducing the issue.

## Context 

* Operating Version:  iPad iOS v 12.5
* SDK version: 3.0.2

## Failure Logs
not able to get any logs or response using iZettleSDK method -(void)refundAmount: and that's the main problem for us.

**Comment by hey-kj** [comment]
@tarun1April 

Thank you for the details, I will try this out and get back to you 👍

**Comment by hey-kj** [comment]
@tarun1April 

Hello again, we are unable to reproduce this with the instructions you gave us. 

Could you try to update the SDK to the latest, which is `3.1.1`.
Also make sure that you handle the `iZettleSDKOperationCompletion` result from the SDK api calls. 

I will keep the issue open for the time being and wait for your response.

**Comment by tarun1April** [comment]
Not possible to install SDK v 3.1.1 using pod because when we use 'pod install', then it installed version 3.0.2

**Comment by tarun1April** [comment]
Now I manually drag & drop the framework v 3.1.1.
But when I am going to refund from my POS App, a crash occurred.

Please check the crash logs and help us in this concern:

 **iZettlePayments was compiled with optimization - stepping may behave oddly; variables may not be available.
/Users/salesvu/Library/Developer/Xcode/DerivedData/SalesVu-eezwsdjltndvogexidxaqugrxdbv/Build/Products/Debug-iphoneos/SalesVu.app/Frameworks/iZettlePayments.framework/iZettlePayments: Cannot load Swift type information; error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/Payments-akjmrumdnzlatxcuiuaxjqxspekz/Build/Intermediates.noindex/ArchiveIntermediates/iZettleSDK/IntermediateBuildFilesPath/iZettlePayments.build/Release-iphoneos/iZettlePayments.build/all-product-headers.yaml' not found**

**Comment by tarun1April** [comment]
Please help us in this concern.

**Comment by hey-kj** [comment]
@tarun1April 

Hello again, this is the first time I see this error and it has not been reported before. By googling there might just be a simple way to solve this issue by cleaning the `DerivedData` folder. 

Also make sure you fulfill our [requirements](https://github.com/iZettle/sdk-ios#requirements)

And to solve your cocoapod issue, try specify the `3.1.1` version or do `pod update`.

**Comment by tarun1April** [comment]
Now I am able to update 3.1.1 version using pod update and I have also clear the derived data but again I am getting the same crash. crash line is:
#1	0x0000000109b1006c in RefundViewController.didFetchPaymentInfo(_:amountToRefund:account:) at /Users/distiller/project/Payments/Refund/UI/Controller/RefundViewController.swift:78

**Comment by hey-kj** [comment]
@tarun1April 

Thank you for this crash log. I will investigate this and get back to you.

**Comment by hey-kj** [comment]
@tarun1April 

Can I assume the refund does not crash for you anymore due to your latest issue report #353  ?

**Comment by tarun1April** [comment]
Yes, the crash is fixed now by using decimal value instead of *nil* as
refund amount. But you have mentioned in your docs as *nil* value refers to
full refund amount. When I use decimal value instead of *nil*, the crash is
fixed.

**Comment by hey-kj** [comment]
Thank you for clarifying and for finding this issue with `nil`. 

We will fix this in the next release 💪
