### ISSUE TITLE
Refund process not completing

### ISSUE THREAD

**Issue by tarun1April** [iZettle/sdk-ios#353]
# Expected Behavior
1. **refundAmount** method should return any callback or failure response after press the "**Confirm refund**"  button.
2. So that, the user can easily found the issue in the process.

# Current Behavior

1. When we called the **refundAmount** method, then a "**Refund payment**" popup appears (all details shown in this popup is correct). 
2. After this, "**Confirm refund**" button is pressed.
3. Then, we are waiting to complete the process but nothing happened and we remain on the same view.
4. Waiting after a long time, we closed the refund view to cancel the refund process.
5.  And also please clear the purpose and use of parameter "**refundReference**" passed in **refundAmount** method. How it is created or from where it inherited. And how it differs from **paymentReference** parameter. 

# Steps to Reproduce

1. When we called the refundAmount method, then a "**Refund payment**" popup appears (all details shown in this popup is correct). 
2. After this, "**Confirm refund**" button is pressed.
3. Then, we are waiting to complete the process but nothing happened and we remain on the same view.
4. Waiting after a long time, we closed the refund view to cancel the refund process.

## Context 

* Operating Version: 12.5
* SDK version: 3.1.1

## Failure Logs

Unable to get any response/logs or callback after press the "**Confirm Refund**" button.

**Comment by hey-kj** [comment]
@tarun1April 

I am currently looking into the refund process to find out where the issue may be.

Regarding your question about `refundReference`, we have it documented in the documentation:
[reference parameter in charging method](https://github.com/iZettle/sdk-ios#charging) 

```
reference (optional): The payment reference. Used to identify a Zettle payment, used when retrieving payment information at a later time or performing a refund. Max length 128.
```

and 

[reference parameter in refunding method](https://github.com/iZettle/sdk-ios#refunding)

```
refundReference (optional): The reference of the refund. Max length 128.
```

I will come back to you once I have tested this scenario.

**Comment by tarun1April** [comment]
I have some questions regarding *refundReference *parameter.
1. Can *reference* and *refundReference* be the same?
2. Is *refundReference* an alphanumeric value / numeric value?
3. Is *refundReference* received from *chargeAmount* method response?
4. Where we again use *refundReference* except *refundAmount* method?
5. Is *refundReference* created on the spot while invoking the
*refundAmount* method?

**Comment by hey-kj** [comment]
1. They should be different because its two different operations
2. Alphanumeric value
3. No, it is not. `refundReference` is a ref you set for that specific refund you are trying to make
4. As of now you can not use it for anything else
5. If you send in `nil` there will be one generated from UUID

**Comment by tarun1April** [comment]
Ok, thanks for the 'refundReference'  clarity. 
Are you able to replicate the refund issue which I have faced and explain it to you?

**Comment by tarun1April** [comment]
Please reply us on our above issue in Refund process.

**Comment by tarun1April** [comment]
https://github.com/iZettle/sdk-ios/issues/353#issue-933610038
Please help us in this issue.

**Comment by tarun1April** [comment]
Please reply to us.

**Comment by tarun1April** [comment]
Please reply to us.

**Comment by tarun1April** [comment]
At the time of login, we press the **Accept cookies** option, then we get the callback with an error i.e.,

Error Domain=com.izettle.sdk.token.error Code=-603 "Required scope is missing." UserInfo={NSLocalizedDescription=Required scope is missing.}

If we do not **Accept cookies** at the time of login, then we remain on the same popup of **Confirm Refund** and behind this popup, a login screen appears in **SFSafari**. After this we are waiting to complete the process but nothing happened and we have to cancel the Refund.

Please check the video for this issue.
https://user-images.githubusercontent.com/86365830/126959118-70afd4e5-2036-4b97-a9f0-a6cbf12b95b0.mov

**Comment by hey-kj** [comment]
Closing due to this already [been solved](https://github.com/iZettle/sdk-ios/issues/361#issuecomment-899287635).
