### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by Ankitvaghasiya44** [iZettle/sdk-ios#354]
Hello,

I am not able to log in with valid cred.

I am getting error like : 
Domain	"com.izettle.account.error"
LocalizedDescription	"Incorrect email or password."

Thanks in Advance.

**Comment by clement-iz** [comment]
Hello @Nidhi4444 
Are you using the [enforced account](https://github.com/iZettle/sdk-ios#enforced-user-account) functionality in the integration?

**Comment by Nidhi4444** [comment]
Hello,

no, I am using normal login.

I am sending nil in enforced account email.

**Comment by Nidhi4444** [comment]
Hello,

please reply to me...I am blocked here now.

Thanks.

**Comment by avalkovskii-pp** [comment]
Hello @Nidhi4444,

Could you please show how the SDK is integrated in your code?

Best,
Andrei Valkovskii
