### ISSUE TITLE
Apple MFI Approval Process - NO REPLY from sdk@izettle

### ISSUE THREAD

**Issue by nnx2202** [iZettle/sdk-ios#355]
My app is ready for release.

Name of app: ConnectPOS Cloud
Company: SmartOSC
App version: 2.0.0
Bundle ID: com.connectpos.spos

I've been mailing SDK team since 2 weeks at sdk@izettle as instructed here , but haven't received any reply.

Apple won't approve my app without MFI Product Plan ID (PPID).

Help me, please

**Comment by hey-kj** [comment]
@nnx2202 

Thanks for reaching out! I will forward this to remind the team to get back to you.

Another side note we recently updated our email (but I think it will still be rerouted correctly) and the new email is sdk@zettle.com (without the **i**)
