### ISSUE TITLE
Refund not working

### ISSUE THREAD

**Issue by tarun1April** [iZettle/sdk-ios#357]
**Expected Behavior**
1. **refundAmount** method should return any callback or failure response after press the "Confirm refund" button.
So that, the user can easily found the issue in the process.

**Current Behavior**
1. When we called the refundAmount method, then a "**Refund payment**" popup appears (all details shown in this popup is correct).
2. After this, "Confirm refund" button is pressed.
3. Then, we are waiting to complete the process but nothing happened and we remain on the same view.
4. Waiting after a long time, we closed the refund view to cancel the refund process.
5. And also please clear the purpose and use of parameter "refundReference" passed in refundAmount method. How it is created or from where it inherited. And how it differs from paymentReference parameter.

**Steps to Reproduce**
1. When we called the refundAmount method, then a "**Refund payment**" popup appears (all details shown in this popup is correct).
2. After this, "**Confirm refund**" button is pressed.
3. Then, we are waiting to complete the process but nothing happened and we remain on the same view.
4. Waiting after a long time, we closed the refund view to cancel the refund process.

**Context**
Operating Version: 12.5
SDK version: 3.1.1

**Failure Logs**
Unable to get any response/logs or callback after press the "Confirm Refund" button.

**Comment by tarun1April** [comment]
At the time of login, we press the **Accept cookies** option, then we get the callback with an error i.e.,

Error Domain=com.izettle.sdk.token.error Code=-603 "Required scope is missing." UserInfo={NSLocalizedDescription=Required scope is missing.}

If we do not Accept cookies at the time of login, then we remain on the same popup of Confirm Refund and behind this popup, a login screen appears in SFSafari. After this we are waiting to complete the process but nothing happened and we have to cancel the Refund.

Please check the video for this issue.
https://user-images.githubusercontent.com/86365830/126959118-70afd4e5-2036-4b97-a9f0-a6cbf12b95b0.mov

**Comment by MarcoDeJong** [comment]
In what language is your application written?

**Comment by tarun1April** [comment]
Programming Language: Objective C
Platform: iOS

**Comment by hey-kj** [comment]
Closing due to this already [been solved](https://github.com/iZettle/sdk-ios/issues/361#issuecomment-899287635).
