### ISSUE TITLE
Add documentation on compatibility/integration with e.g. React Native/Flutter

### ISSUE THREAD

**Issue by MarcoDeJong** [iZettle/sdk-ios#358]
It would be very helpful if you could be a bit more elaborative on how integration with the SDK should work, for e.g. React Native or Flutter. The is no mention of what the SDK is compatible with whatsoever.

If not possible, please list a few integration partners whom could help setting above up, as this would ease working with your SDK.

**Comment by hey-kj** [comment]
Hello @MarcoDeJong 

Support for integration with non iOS native is nothing that we provide, but there are unofficial bindings between other frameworks such as xamarin, https://github.com/NAXAM/izettle-ios-binding , although it seems this one is not supported anymore. 

In short what we have in our documentation is what we provide and all other integrations is not something we provide.
