### ISSUE TITLE
Not able to create iZettleSDKAuthorization

### ISSUE THREAD

**Issue by Lebron1992** [iZettle/sdk-ios#377]
# Expected Behavior

Create the `iZettleSDKAuthorization` object.

# Current Behavior

Got error: `Callback URL is missing under URLSchemes in the plist.`

# Steps to Reproduce

I had added the callback URL to plist, as follow:

![image](https://user-images.githubusercontent.com/13708531/142977585-bb744108-b75d-4387-85e6-444efa728a4f.png)

But when I try to init the `iZettleSDKAuthorization` object, I got the error:
```swift
do {
    let authenticationProvider = try iZettleSDKAuthorization(
        clientID: "xxxxxxxxxxxxxxx",
        callbackURL: URL(string: "myapp://login.callback")!)

    iZettleSDK.shared().start(with: authenticationProvider)
} catch {
    // Callback URL is missing under URLSchemes in the plist.
    print(error.localizedDescription)
}
```

## Context 

* Operating Version: iOS 15
* SDK version: 3.3.0

**Comment by clement-iz** [comment]
Already addressed by support
