### ISSUE TITLE
Keyboard return key doesn't work when refunding a payment

### ISSUE THREAD

**Issue by chrisjf** [iZettle/sdk-ios#38]
### Description
When the user is refunding a payment, they must type in their password. After typing in their password the orange "Confirm" button is hidden behind iOS's software keyboard, and tapping the "Next" return key does nothing.

### Steps to reproduce
- Process a payment with the iZettle SDK
- Start a refund
- Tap on the Password box and type in your password

### Actual Results
- Tap on the "Next" return key; nothing happens
- the "Confirm" button is hidden behind the keyboard when typing in the password

### Expected Results
- Tap on the "Next" return key; the password should be submitted and the refund payment process should continue (the same as tapping the "Confirm" button)
- the return key should be labeled "Done" (like the Sign In screen)
- the "Confirm" button should be visible when typing in your password (like the Sign In screen)

### Reproduced Using
iZettle SDK: v1.2.1
Device Model: iPad Air A1474
OS: iOS 9.2

#### Problem:
![problem](https://cloud.githubusercontent.com/assets/105042/12595990/0e482122-c44c-11e5-82ea-751ecc5e97c7.PNG)

#### Desired Solution: 
(Except for return key)
![desired solution](https://cloud.githubusercontent.com/assets/105042/12596040/46d79266-c44c-11e5-9db5-a85f352f3335.PNG)

#### Similar Existing Solution (Sign In Screen)
![similar exisiting solution](https://cloud.githubusercontent.com/assets/105042/12596043/4d8f8000-c44c-11e5-9bfa-0699b1a66abe.PNG)

**Comment by mattiasjahnke** [comment]
Thank you very much @chrisjf for a great bug report. We'll have a look at it and get a patch out asap.

**Comment by chrisjf** [comment]
Sounds great. Thank you for the quick reply. Looking forward to the patch. :+1:

**Comment by mansbernhardt** [comment]
There is a 1.2.2 beta branch out if you want to try it out at: https://github.com/iZettle/sdk-ios/tree/1.2.2beta

**Comment by chrisjf** [comment]
I tried out 1.2.2beta. The fix looks good @mansbernhardt. Thank you very much :)
