### ISSUE TITLE
Add mock/test option for working without Reader

### ISSUE THREAD

**Issue by MarcoDeJong** [iZettle/sdk-ios#380]
For improving developer experience, it would be a great improvement, when the SDK can process (dummy) request and response without using the actual Reader. 

When working in a larger development team, I have to provide every user with a reader, but above that they have to use their personal bankcards to test transaction or implementations.

Above all, unhappy flows are currently impossible to test: users enter wrong pincode 3 times, card blocked, etc.

**Comment by davidzettle** [comment]
Hello Marco, we are sorry that this went undetected for long.

We are actually adding a developer mode to test dummy payments during the upcoming weeks to our Developer Portal in the try out section of our get started page: [https://developer.zettle.com/docs/get-started](https://developer.zettle.com/docs/get-started).

I hope that this will continue to help if you need any additional testing.

Best,
