### ISSUE TITLE
Translucent navigation bar on iOS 15

### ISSUE THREAD

**Issue by ls-philippe-casgrain** [iZettle/sdk-ios#381]
# Expected Behavior

Solid navigation bar when running the SDK on iOS 15.2.

# Current Behavior

Navigation bar is translucent and that can make buttons hard to see depending on the background colour.

![translucent](https://user-images.githubusercontent.com/3964293/148436429-54cf7b12-8d95-47df-b097-5a6a773fe30c.png)

# Steps to Reproduce

1. Open the project Example > Sample > iZettleSDKSample.xcodeproj in Xcode 13.2.1.
2. Build and run the application on an iOS 15 device (e.g. iPad Air 4th generation, iOS 15.2)
3. Press the "Charge" button
4. Examine the modal dialog and its navigation bar

## Context 

Does not occur on iOS 13 / 14. We ran into this issue for our own app and we had to explicitly call `configureWithOpaqueBackground()` as described [here](https://developer.apple.com/documentation/uikit/uibarappearance/3197998-configurewithopaquebackground)

* Operating Version: iOS 15.2 / Xcode 13.2.1
* SDK version: 3.3.1

## Failure Logs

n/a

**Comment by ls-philippe-casgrain** [comment]
Note that this also affects the Settings modal dialog

**Comment by clement-iz** [comment]
Hi @ls-philippe-casgrain 
This has already been addressed and the fix will be available in our next SDK release.

BR,
Clement

**Comment by ls-philippe-casgrain** [comment]
Thank you. I'm surprised no one reported it yet. We were quite surprised in our app.

**Comment by kyleiikyle** [comment]
I see the latest release has IOS 15 bugs addressed. Was this issues fixed in the latest release? I see you said would be addressed then but this issue is still open.

**Comment by clement-iz** [comment]
@kyleiikyle Yes, this was fixed in the latest release.
