### ISSUE TITLE
Document: Apple MFI Approval Process - Reader v.2 Only

### ISSUE THREAD

**Issue by MarcoDeJong** [iZettle/sdk-ios#392]
### Please update your documentation, so the steps for only supporting reader v.2 are mentioned.

_As an app developer,
I would like to know how to implement Zettle Card Reader v.2 only for my app,
So I will have a smooth journey releasing it on the Apple App Store_

**Context**
Me and my development team have been working on an app, coupling with your reader two devices.

After having contact with sdk@zettle.com, it became clear "no other actions" are needed, if only using reader version two, to get our app approved by Apple.

Once in the approving proces, Apple keeps rejecting our app, because of mentions of the `com.izettle.cardreader-one` in the Plist. So far I haven't heard back from your support desk, what steps to take.

**Comment by MarcoDeJong** [comment]
@hey-kj Thanks! That is an error in my question, my plist still uses the right one ;)

**Comment by MarcoDeJong** [comment]
Ok, so apparently the documentation has been moved, to https://developer.zettle.com/docs/ios-sdk/installation-and-configuration , with a notion of NOT using Reader 1. Nice.

However, when following the steps exactly; Apple says this:


### Guideline 2.5.4 - Performance - Software Requirements

>Your app declares support for external-accessory in the UIBackgroundModes key in your Info.plist file but does not declare any external accessory protocols supported by your app. The external accessory background mode is intended for apps that communicate with hardware accessories through the External Accessory framework.

>Next Steps

>If your app is meant to work with external hardware, supported protocols must be included in the UISupportedExternalAccessoryProtocols key in your app's Info.plist file - and the hardware's PPID # should be provided in the Review Notes field of your app in App Store Connect.

>Additionally, your app must be authorized by MFi to use the desired hardware. If you are not yet in the MFi Program, you can enroll at [MFi program](https://developer.apple.com/programs/mfi/).

>Please either revise your Info.plist to include the UISupportedExternalAccessoryProtocols key and update your Review Notes to include the PPID # - or remove the external-accessory value from the UIBackgroundModes key.

**Comment by kevintq** [comment]
Did anybody ever find an answer to this? We have exactly the same problem. Can't seem to get a response from Apple or zettle

**Comment by tennisgent** [comment]
@kevintq We're having the exact same problem. We're only supporting Reader 2, but Apple keeps rejecting our app for the store because they say we're missing the required plist string. 

> **ITMS-90683: Missing Purpose String in Info.plist** - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources

But [the docs](https://developer.zettle.com/docs/ios-sdk/installation-and-configuration) explicitly say this should only be necessary for Reader 1 support:
![CleanShot 2022-11-09 at 13 32 48](https://user-images.githubusercontent.com/1782077/200937000-9873e185-bfaa-4404-996e-decb80afb7dd.png)


We would LOVE it if someone at Zettle could take the time respond. We are currently blocked despite multiple submissions to the App Store for review.

**Comment by MarcoDeJong** [comment]
I feel your pain, guys ;)

However, I have managed to get things sorted out. It took me for about two month, dealing with communication between Apple and Zettle, me being the man-in-the-middle without any proper knowledge.

As Apple is the gatekeeper, their information is correct. It is absolutely impossible with the current review process at Apple, to use the Zettle skd-ios without having a PPID. 

Whatever Zettle tells you on this part - Yes, it is even wrong in their own documentation-, you can not "skip this step" as in the image above from @tennisgent . You will have to follow the steps, as if you were setting this up for using Card Reader 1, even if you intend NOT to use it 🥳 

The process for this is fairly simple... As long as Zettle replies swiftly. You will receive an Excel-sheet, in which you have to fill in some information on your app. Zettle then replies to you with your newly created PPID. This PPID will have to be put in the comment section during your app review request in your Apple Developer Account.

**Comment by kevintq** [comment]
hi guy a update which hopefully everyone will find useful as Marco said, we've just managed to get apple approval, but essentially we followed the steps as if we were using cardreader 1 so whatever zettle will tell you just ignore it to apply for a PPID number and add this to your info.plist file <key>UISupportedExternalAccessoryProtocols</key>
2	 <array>
3	     <string>com.izettle.cardreader-one</string>
4	 </array>

After a week of frustration, they approved it within two hours and, hope this helps, and I have a mentioned to zettle that they should update documentation, but I doubt they will take any notice :-)

**Comment by tennisgent** [comment]
@MarcoDeJong @kevintq This is very helpful to know! Thanks for taking the time to respond and fill us in on your experience 🙏. It sounds like we just need to keep reaching out to Zettle until we can get them to give us that excel file. We'll do our best to get them to respond. So far we haven't had much luck. 😬 

I do have a few questions for you though if you have the time to answer:

1. How long ago did you submit your app for approval to Apple? I'm just curious how long Zettle has been aware of this approval issue and hasn't updated their online documentation.
2. This one is a bit more of a loaded question. I see you have a lot of issues logged in this repo and it sounds like you (@MarcoDeJong) are using a React Native (or Flutter) app, which is exactly what we are doing as well. So far we've managed to get this SDK integrated and it has worked for some testing with our beta users, but we're still running into a few issues. The Zettle team seems to be a bit hard to get a hold of when we have questions. Given the struggles you've had during your time integrating with them, how has your experience been overall? Has Zettle been easy to work with? If you were starting out with this process now, would you still choose Zettle as your payment processor? 

Any thoughts/answers you guys have would be super helpful. Thanks!

**Comment by kevintq** [comment]
my apple approval from rejection to approved was 4 hours ( after a week on arguing :-) our app is native if that helps the sdk was good and easy to use, zettle support was next to useless took over a week to provide the ppid. we had the app in beta internal testing and it seem to work well with the zettle reader if it help this is the file you have to fill in to get you ppid ( took 2 days jus to get this) attached, hope the helps
[MFI_Form_Zettle_Card_Reader.xlsx](https://github.com/iZettle/sdk-ios/files/9981815/MFI_Form_Zettle_Card_Reader.xlsx)

**Comment by MarcoDeJong** [comment]
@tennisgent To answer your questions ;)

1. Well, I have informed Zettle for the correct flow already a year ago. Then got to really into approval flow with Apple in April this year. (After having the app already running for quite some time in 'testing' mode)

2. Indeed. We are developing in React native. Initial set-up was quite painful. React native was known, however coupling with this API made us use a (tiny) bit of Swift as well for intermediate layer. The Zettle team is willing to give answers, but most of them get are quite political and avoiding real solutions. I guess they are completely unaware of what the SDK end-users are doing. After all implementation took quite long, mostly because of 'waiting time' for Zettle AND Apple.

If I would start over I might have chosen another payment provider. But now I have all the footwork done, implementing a second app, would be a breeze.

**Comment by davidzettle** [comment]
Hello and thank you for your comments. 

We are updating this information in our Portal and help center as this has been required by Apple independently of the reader version as stated above due to our background mode used as well in the Zettle reader 2.

I believe all of you have already had a successful application submitted so I will go ahead and close this thread. If you need to apply for one still you can find the steps here: https://ext-izettle.atlassian.net/servicedesk/customer/portal/3/group/4/create/24 <- to be updated soon to remove only for reader one, so you can just ignore that, download the file and submit after you have filled it and attached it.

Regrads,
