### ISSUE TITLE
iZettle library latest version (with previous version i was able without issues) binary and entitltments 0, while exporting to ipa xcode 6.1.1, thus not able to export to IPA

### ISSUE THREAD

**Issue by alok1upadhyay** [iZettle/sdk-ios#4]
![screen shot 2015-04-28 at 1 47 42 pm](https://cloud.githubusercontent.com/assets/7948432/7365639/c609343c-edaf-11e4-84c5-927bacb8ccc2.png)

Hi @mattiasjahnke 

As per the screen shot:

I am trying to create an app store distribution provisioned build to submit on apple itunes test flight. I have previously prereleased it many times, but this time i have included iZettle latest library(last version did not create issue in archiving) in my project. i have cross check my app id services, provisioning profile services, capabilities.

Any idea is it related to external iZettle library ?

Thanks,
Alok

**Comment by mattiasjahnke** [comment]
Hi @alok1upadhyay 

Make sure you strictly follow the installation guide.

For this particular issue, check to make sure you don't have ```iZettleSDK.framework``` in "Copy Bundle Resources" (located in under your targets "Build Phases").

**Comment by alok1upadhyay** [comment]
@mattiasjahnke thanks for the response,

yes i have followed installation guide and mistakenly added iZettleSDK.framework along with bundles in "Copy Bundle Resources".

issue have been fixed and i am able to create IPA.
