### ISSUE TITLE
iZettle Library 

### ISSUE THREAD

**Issue by mobipos** [iZettle/sdk-ios#40]
![screen shot 2016-01-23 at 8 09 10 pm](https://cloud.githubusercontent.com/assets/16935094/12640582/955e9002-c5e5-11e5-8f8b-03a6047757a8.png)
Hi guys can you take a look at the screenshot? Library clashing with library from payanywhere. Thanks.

**Comment by mansbernhardt** [comment]
Hi,

Please try again using the 1.2.2beta branch at: https://github.com/iZettle/sdk-ios/tree/1.2.2beta

Please let me know if you still are having problems and if possible insert the linker output as text instead as an image.

**Comment by mansbernhardt** [comment]
I would like to know if the latest fixes work for you, so we can release a new version including them.

**Comment by mobipos** [comment]
Hi,

Sorry, haven't got the time to try out yet.
Give us a day, I should give you a reply by tomorrow.
Thanks for your help.

Regards,
MobiPos Support

**Comment by mobipos** [comment]
Hi, the new sdks works for compilation. Now I'm having another issue. 
I'm running on simulator and no reader is plugged in. 
I receive this error upon payment via manual entry. 

2016-02-04 22:29:02.675 iZettle SDK Sample[30439:1597895] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayI readerModelName]: unrecognized selector sent to instance 0x7a9dda80'

**Comment by mansbernhardt** [comment]
There is a new beta candidate up that should fix that crash at: https://github.com/iZettle/sdk-ios/tree/1.2.2beta

**Comment by mobipos** [comment]
The error still persists.

**Comment by jensutbult** [comment]
We messed up the 1.2.2branch. Could you give 1.2.2-branch a try?

**Comment by mobipos** [comment]
Alright, tested with a manual entry payment. Works fine.
