### ISSUE TITLE
Authorization Status in Swift

### ISSUE THREAD

**Issue by DowsingUK** [iZettle/sdk-ios#401]
# Expected Behavior

Please describe the behavior you are expecting.

Android SDK has StateObserver<User.AuthState> is there anything similar for iOS?

# Current Behavior

What is the current behavior?
I haven't found a way to get authorization status

# Steps to Reproduce

Please provide detailed steps for reproducing the issue.
N/A

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: iOS
* Swift version: Last

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ppeelen** [comment]
Hello @DowsingUK!

Thank you for reaching out. Unfortunately the iOS SDK currently does not support anything similar to the Android SDK's StateObserver or give any authorisation status.
