### ISSUE TITLE
startWithAPIKey method

### ISSUE THREAD

**Issue by ceetn** [iZettle/sdk-ios#41]
We have a technical question for you guys, what exactly does the 'startWithAPIKey' method?
We have a discussion in our team when to call this method. At the launch of the application or only when you want to start a payment? 
Does this make a bluetooth connection to the device?

**Comment by mansbernhardt** [comment]
You typically call startWithAPIKey early in your app launch cycle and only once. When the SDK tries to connect to BT devices depends on active user sessions etc and is an implementation detail that might change between releases. What are your concerns?

/Måns

From documentation:

Before you execute any operations in iZettle SDK, you have to start the SDK with your API key. This is typically done in your AppDelegates method `application:didFinishLaunchingWithOptions:`.

    - (void)startWithAPIKey:(NSString *)apiKey;
    
Example:

	- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    	[[iZettleSDK shared] startWithAPIKey:@"API_KEY"];
    	return YES;
	}

**Comment by ceetn** [comment]
> What are your concerns?

That starting the iZettleSDK would create some overhead while the iZettle integration is only used in 10% of the application sessions (for example). But from what I'm reading this is not really the case.

Thank you very much!
