### ISSUE TITLE
Error when trying to do a test purchase

### ISSUE THREAD

**Issue by patwhitehead1** [iZettle/sdk-ios#42]
Just trying a test transaction, I’m receiving this error message:

Error Domain=com.izettle.transaction.error Code=6 "Could not connect to iZettle. / An unknown error occurred. Please try again later." UserInfo={izMessage=An unknown error occurred. Please try again later., NSErrorFailingURLStringKey=https://mercury.izettlepay.com/mobile/psstate, izTitle=Could not connect to iZettle., NSLocalizedDescription=Could not connect to iZettle. / An unknown error occurred. Please try again later.}

Any idea what the issue could be? I'm using the API key provided as well as the account (externaldemo@izettle.com). I am entering the card number manually and using the iOS simulator.

Thanks

**Comment by mattiasjahnke** [comment]
Hey,

We couldn't find anything out of the ordinary when investigating this. The error says that you couldn't connect to the iZettle servers.

Does this happen every time? If so, please provide a timestamp to help us look through the logs.

**Comment by patwhitehead1** [comment]
Yes this is happening every time. Just tried again now, here is the error with timestamp:

2016-02-17 11:28:49.403 iZettleTest[4642:1258211] error: Error Domain=com.izettle.transaction.error Code=6 "Could not connect to iZettle. / An unknown error occurred. Please try again later." UserInfo={izMessage=An unknown error occurred. Please try again later., NSErrorFailingURLStringKey=https://mercury.izettlepay.com/mobile/psstate, izTitle=Could not connect to iZettle., NSLocalizedDescription=Could not connect to iZettle. / An unknown error occurred. Please try again later.}

**Comment by mattiasjahnke** [comment]
@patwhitehead1 What timezone did that timestamp come from?

**Comment by patwhitehead1** [comment]
This was in EST. 

> On Feb 18, 2016, at 5:03 AM, Mattias Jähnke <notifications@github.com> wrote:
> 
> @patwhitehead1 What timezone did that timestamp come from?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

------------------------------
The information and attachments in this email are confidential and 
proprietary and intended only for use by the individual or entity who is 
the intended recipient or those authorized to receive or view them. If you 
received this communication in error please notify the sender immediately 
and permanently delete the original message and any attachments without 
making a copy. Unauthorized use, distribution, or copying of information 
received in error is prohibited and unlawful.

**Comment by mansbernhardt** [comment]
It seems you are using an app id "blah.iZettleTest" that you have not been registered with us. We are investigating why you don't get att better error back though...

**Comment by patwhitehead1** [comment]
Oh ok, I was just making a test app to learn the SDK before adding it to the app. I have tested iZettle on the app that we registered with you, and it is working without issue.

Thanks
