### ISSUE TITLE
No UI, or Errror/callback when calling chargeAmount during a UIViewController transition 

### ISSUE THREAD

**Issue by Clancey** [iZettle/sdk-ios#424]
# Expected Behavior

Error, or UI should be shown when calling chargeAmount

# Current Behavior

If you are dismissing a UIViewController animated when you call chargeAmount, no UI is show. And no error. IT just hands indefinitely 

# Steps to Reproduce
Have a UIViewController modal presented. Dismiss it at the same time as you call chargeAmount
No UI is shown, and no error is presented
## Context 

For my app, I am dismissing the employee login screen and calling chargeAmount at the same time. When this happens, iOS won't show the Zettle UI since there is a ViewController transition going on.

* Operating Version:
* SDK version:

**Comment by Clancey** [comment]
That's exactly what I am doing. However I was transition from PayPal Here Sdk, and it went from working to nothing. 

One idea, override view did appear, and send a message to the sdk saying it was shown. If it wasn't show. In 1 second cancel auth and throw an error, or auto try presenting the UI again. Anything is better than an indefinite hang.

**Comment by Clancey** [comment]
Another option is to always create your popup in a new UIWindow. It will look the same, but it can't have this type of issue. And you don't need the parent UIViewController anymore. If you ignore the C#, but here is a great example of it: https://github.com/Clancey/SimpleAuth/blob/main/src/SimpleAuth.iOS/WebAuthenticatorWindow.cs

**Comment by MBelogorodtsev-IZ** [comment]
Thank you, we will consider this option as well.

**Comment by MBelogorodtsev-IZ** [comment]
Thank you again for bringing this issue. We have implemented the fix and starting from the next minor version the SDK will return error if something is already presented from the ViewController provided into it. This way, there won't be any logic hanging in background.

That said, it's still required to start ZettleSDK flows when no transitions is happening and nothing is presented in the ViewController provided.

And thank you for great suggestion on presenting Zettle flows from Window, we will definitely consider it during future SDK improvements.
