### ISSUE TITLE
IZFuture repeatFunction

### ISSUE THREAD

**Issue by VanCert** [iZettle/sdk-ios#43]
App builds ok but as soon as i call 

[[iZettleSDK shared] startWithAPIKey:@"APPKEY"];

i get

+[IZFuture repeatFunction:]: unrecognized selector sent to class 0x100992910
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[IZFuture repeatFunction:]: unrecognized selector sent to class 0x100992910'
*** First throw call stack:
(0x183d85900 0x1833f3f80 0x183d8c514 0x183d895b8 0x183c8d68c 0x1006e6ffc 0x1833f60cc 0x1833f6e30 0x120009d3c 0x120018960 0x120017b20 0x120017bd4 0x12000a08c 0x12000e0fc 0x120009044)
libc++abi.dylib: terminating with uncaught exception of type NSException

can you give me any help with this please.

**Comment by mansbernhardt** [comment]
Looks really strange as this is a class method. Could you enable the exception break point in xcode and send a call stack with symbols when you hit the break point.
