### ISSUE TITLE
SDK crashes when accessory disconnects

### ISSUE THREAD

**Issue by svenmuennich** [iZettle/sdk-ios#431]
# Current Behavior

We noticed a crash of our app caused by this SDK. From the stacktrace it looks like a reader disconnected but the respective notification was processed on the wrong queue `com.apple.root.default-qos`.

# Steps to Reproduce

Unfortunately we are not able to reproduce this.

## Context 

* Operating Version: iPadOS 16.3.1
* SDK version: 3.7.2

## Failure Logs

Crash info:
```
Assertion failed: ([NSThread isMainThread]), function -[IZCallbacker callAllWithValue:], file IZCallbacker.m, line 50.
```

Stacktrace:
```
Crashed: com.apple.root.default-qos
0  libsystem_kernel.dylib         0x7274 __pthread_kill + 8
1  libsystem_pthread.dylib        0xd654 pthread_kill + 208
2  libsystem_c.dylib              0x1fe88 abort + 124
3  libsystem_c.dylib              0x734b4 err + 266
4  iZettlePayments                0x46fbb0 -[IZCallbacker callAllWithValue:].cold.1 + 38
5  iZettlePayments                0x70034 -[IZCallbacker callAllWithValue:] + 364
6  iZettlePayments                0x5d240 -[CardReaderManager removeReader:] + 124
7  iZettlePayments                0x5e420 -[CardReaderManager accessoryDidDisconnect:] + 212
8  CoreFoundation                 0x34ae4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 140
9  CoreFoundation                 0xd40a0 ___CFXRegistrationPost_block_invoke + 84
10 CoreFoundation                 0xb8b48 _CFXRegistrationPost + 404
11 CoreFoundation                 0x482a8 _CFXNotificationPost + 684
12 Foundation                     0x5721c -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
13 ExternalAccessory              0x69d8 -[EAAccessoryManager _externalAccessoryDisconnected:] + 808
14 ExternalAccessory              0x30f4 -[EAAccessoryManager _checkForConnectedAccessories:backgroundTaskIdentifier:] + 552
15 libdispatch.dylib              0x63850 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x647c8 _dispatch_client_callout + 16
17 libdispatch.dylib              0x65d8 _dispatch_queue_override_invoke + 724
18 libdispatch.dylib              0x13c7c _dispatch_root_queue_drain + 340
19 libdispatch.dylib              0x1447c _dispatch_worker_thread2 + 172
20 libsystem_pthread.dylib        0x1b14 _pthread_wqthread + 224
21 libsystem_pthread.dylib        0x167c start_wqthread + 8
```

**Comment by ppeelen** [comment]
Hi @svenmuennich! 

Thank you for bringing this to our attention! I will look into this and get back to you as soon as possible.

**Comment by ppeelen** [comment]
Hi @svenmuennich!
I little update here on this issue. We've identified the source and a fix is currently under testing. This should be resolved in the next release. I will update you when a release ready for you to test.

**Comment by ppeelen** [comment]
Hi again @svenmuennich!

My apologies for this late reply, but I want to ensure you that your issue was not forgotten. The fix for the issue you reported should be released in version 3.16 of the SDK; however as of right now we do not have an ETA on this release. We hope to be able to release this to you shortly.

**Comment by ppeelen** [comment]
Hi @svenmuennich!

[Release 3.18.0](https://github.com/iZettle/sdk-ios/releases/tag/3.18.0) is now public and should address the issue you mentioned.
 I will close this issue now with regards to the release.

Thank you again for reaching out and making us aware of this bug. If you are experiencing any further issues, please do not hesitate to reach out.

**Comment by svenmuennich** [comment]
Thank you!
