### ISSUE TITLE
Venmo Payment Shows Failure in Zettle SDK But Payment Successfully Pulled From Venmo Account

### ISSUE THREAD

**Issue by chaderick9** [iZettle/sdk-ios#434]
# Expected Behavior

When I initiate a `VENMO QRC` payment with the following code snippet:

```objective-c
{
  @try {
    NSDecimalNumber *amount = [NSDecimalNumber decimalNumberWithString:[[args valueForKey:@"grandTotal"] stringValue]];
    NSString *internalTraceId = [[args valueForKey:@"cartId"] stringValue];
    
    if (@available(iOS 13, *)) {
      [[iZettleSDK shared] chargePayPalQRCWithAmount:amount reference:internalTraceId appearance:1 presentFromViewController:[self currentApplicationViewController] completion:^(IZSDKPayPalQRCPaymentInfo *paymentInfo, NSError *error) {
        if (!error && paymentInfo) {
          resolve([self handleQRCPaymentPayload:paymentInfo withReferenceId:internalTraceId]);
          return;
        }
        reject(@"E_QRC_PAYMENT_CANCELLED", error.description, nil);
      }];
    } else {
      reject(@"E_QRC_PAYMENT_CANCELLED", @"iOS 13+ required", nil);
    }
  } @catch (NSException *exception) {
    reject(@"E_QRC_PAYMENT_CANCELLED", exception.description, nil);
  }
}
```

I expect the payment to be successful and not return an error.

# Current Behavior

When I initiate a `VENMO QRC` payment and scan the VENMO QR code that the Zettle UI displays on the iPhone running the SDK - the Zettle UI returns the error ( see screenshot below ) as well as returns the `error.description` : `IZSDKPayPalQRCTechnicalError`. This prevents the Zettle UI from progressing and showing the expected successful icon making the user believe the payment was unsuccessful. However, (see 2nd screenshot below) the VENMO payment is in fact successful. 

# Steps to Reproduce

  1. create and charge a VENMO QRC payment `chargePayPalQRCWithAmount` ...
  2. scan the QR code presented in the Zettle UI with a different mobile device running the VENMO app

## Context 

This implementation has been working for the last 8 months and only recently started breaking on Aug. 3, 2023 and no new deploy of our mobile app had occurred.

We have reached out to your support team who is unaware that this same issue is happening even with your official Zettle app ... Could it be our paypal account? We have no trouble processing payments with the zettle card readers within our same mobile app.

* Operating Version:
  - iOS: 16.6
  - model: iPhone 14 Pro Max

* SDK version:
  - originally experienced the issue on `3.7.2`
  - still experiencing the issue after upgrading to `3.10.0`

## Screenshots

![IMG_3805](https://github.com/iZettle/sdk-ios/assets/8715974/6eb9f76a-46ae-4bc4-821c-d3c4b08e6626)
![IMG_3806](https://github.com/iZettle/sdk-ios/assets/1107400/e862d7fd-22e4-4627-a427-7f8b3f347d87)

**Comment by ppeelen** [comment]
Hello @chaderick9!
Thank you for reaching out. From the little code we can see, it seems that you are performing the call to the SDK correctly. In order to investigate this further we would need more information about the transaction made and for that we would like to ask you to create a ticket using our developer portal as such information should not be shared in a public forum. 

Could you please be so kind and create a ticket via https://developer.zettle.com, top right corner "Support". Please include a link to this issue as well as much detailed information about the transaction made with possible payment references.

**Comment by chaderick9** [comment]
Thanks for your reply, @ppeelen 

We actually already have created a ticket via the developer link you mentioned. This was done over a week ago and unfortunately It was only because of our poor experience through that stream that we then resulted to this github repo.

Here is our existing jira ticket number. `API-1867`

```CRITICAL ERROR - NEED IMMEDIATE FIX: Venmo is showing an error indicating payments are not processing, but indeed they are.```

We will reply within that ticket and include a reference to this repo now.

Thanks so much.

**Comment by ppeelen** [comment]
@chaderick9 I have been informed that the issue should now have been resolved. I will close this issue, but if the problem persists, please do not hesitate to let us know and reopen this issue or the ticket you mentioned before.
