### ISSUE TITLE
Unsuccessful Cancel with in-progress refund

### ISSUE THREAD

**Issue by JD-** [iZettle/sdk-ios#44]
# Description

When a refund is in-progress, the "Cancel" action is always available. Tapping on it dismisses the "Refund Payment" view despite the cancellation will be unsuccessful as far as the transaction refunding is concerned.

The user will expect the refund to have successfully been cancelled while it has not.

# Steps to reproduce

- Process a payment with the iZettle SDK
- Start a refund
- Tap on the Password box and type in your password
- Tap "Cancel" while the spinner next to the password field is still active

**Expected result:** The transaction is not refunded
**Actual result:** The transaction is refunded but the user does not know about it
**Suggested fix:** Disable the cancel button while refund is in progress or returns an error when cancellation failed.

# Video
[Link to video](https://drive.google.com/file/d/0B_DAFH-0FxIzalJJaWplc1R3ckE/view?usp=sharing)
(Scenario in the video - Process payment - Start refund - Cancel - Try to refund the same transaction)

iZettle SDK: v1.2.1
Device Model: iPad Air A1474
OS: iOS 9.2

**Comment by mattiasjahnke** [comment]
Hey @JD- thanks for a great bug report!

We will release a fix for this as part of the coming version 1.2.2

**Comment by mansbernhardt** [comment]
Release in 1.2.2
