### ISSUE TITLE
MacCatalyst binary

### ISSUE THREAD

**Issue by Clancey** [iZettle/sdk-ios#441]
Could you please add a MacCatalyst version in the XCFramework? I would love to deploy on both iOS and Mac.

**Comment by ppeelen** [comment]
Hi @Clancey!

Thank you for your feature request regarding adding MacCatalyst support to our SDK. We will consider it during our internal discussions. For now, we will close this ticket, but your suggestion has been duly noted.

Best regards,
Paul Peelen
