### ISSUE TITLE
Get device serial number

### ISSUE THREAD

**Issue by tierracero** [iZettle/sdk-ios#442]
Add the possibility to get serial number from device will slow to provide an extra layer of information and conviniance to the final user

**Comment by nataliq-pp** [comment]
Hi @tierracero, thank you for your feature request! We appreciate your input. I assume that by `device` you mean the connected reader. Could you please confirm if that's the case and provide more details about your specific use case? This will help us better understand your needs and evaluate the feasibility of incorporating this feature into our SDKs.

Best,
Nataliya
