### ISSUE TITLE
Card rejected "out of country"

### ISSUE THREAD

**Issue by ggemmill** [iZettle/sdk-ios#447]
# Expected Behavior

Card presented should be accepted

# Current Behavior

John Lewis Partnership Mastercard card starting 537370 was rejected "not in the same country" . NatWest Mastercard presented immediately after was accepted. Same behaviour reported earlier today, but no details.

# Steps to Reproduce

Usual process to make a payment 

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Not known
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by nataliq-pp** [comment]
Hi @ggemmill,

Thanks for reaching out. I'm sorry to hear that you're having trouble accepting cards with the Zettle SDK.

The error you're referring to can be related to the concrete merchant location or setup among other things. That's not something that can be addressed in the SDK or your integration with it.

My recommendation is that the merchant experiencing this issue contacts Zettle's support by visiting https://www.zettle.com/ and navigating to the support contact page.

I hope this helps! 

Best, Nataliya Patsovska Marmelstein
