### ISSUE TITLE
iZettle Cordova

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#45]
Hello, I'm integrating iZettle with cordova ios App, do you have any additional plug-in to link the SDK with cordova?
Regards

**Comment by mansbernhardt** [comment]
Sorry, but no such additional plug-in exists.

**Comment by asa47** [comment]
Hello, thanks for the reply. I end up creating my own plugin and it works, however after clicking on "cancel" button, if I reopen iZettle I received the following exception:

WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <iZettleSDKException> iZettle SDK already started.

Could you please advice me on what to do? I guess I just need to stop iZettleSDK, but I am not sure how to do it.
Regards

**Comment by mansbernhardt** [comment]
You should only call:

- (void)startWithAPIKey:(NSString *)apiKey;

once.

**Comment by asa47** [comment]
Yes I was calling it every time..my bad...now Im calling once however I receive the same exception; and this is my function:

`- (void) chargeAmount:(CDVInvokedUrlCommand *)command {

//here i just set the parameters i.e _lastReference and amount

[[iZettleSDK shared] chargeAmount:amount currency:nil reference:_lastReference presentFromViewController:self.viewController completion:^(iZettleSDKPaymentInfo *paymentInfo, NSError *error) {}];
}`

Any advice?
Regards

**Comment by mattiasjahnke** [comment]
`iZettle SDK already started` means that `startWithAPIKey:` was called a second time.

A similar exception; `iZettle SDK not started` will be thrown if you've forgot to call `startWithAPIKey` before calling any other operation.

**Comment by asa47** [comment]
Ok thanks for the help, the `startWithAPIKey ` was called twice by my init function (not sure how), anyway now it is fully working :)
Thanks again.
Regards

**Comment by fabgrenier** [comment]
Hi @asa47, did you succed to create your plugin ? Are you interested to open source it as we can use it and contribute ?

If you don't want, could you just tell me how much time you spent to developp it and if you had some big problems ? Thanks for your help !

**Comment by asa47** [comment]
Hello @fabgrenier,
Yes I did implement the plugin and it is fully working. It quite simple to integrate with cordova, it just a few scripts. I do not mind forking my code to the original git repository (https://github.com/ttopholm/iZettle), I am just waiting for an approval from the original author.
