### ISSUE TITLE
Could not initialize payment, frozen screen

### ISSUE THREAD

**Issue by basvandorst** [iZettle/sdk-ios#453]
# Expected Behavior
Time-out or failed payment after 1.5 minute

# Current Behavior
![image](https://github.com/iZettle/sdk-ios/assets/1196963/5a807221-853d-4884-918d-064d72371cc7)

## Context 
See screenshot. We have seen this a couple of times and there isn't a way to escape from this screen. 
Also there is no timeout (which is the case after 1.5 minute, when the payment is initialized).

Side note: we have seen network dips by this client, so the network is not 100% stable.

# Steps to Reproduce
n/a

* Operating Version: iOS
* SDK version: [3.18.0](https://github.com/iZettle/sdk-ios/releases/tag/3.18.0)

## Failure Logs
n/a

**Comment by ppeelen** [comment]
Hallo @basvandorst!

Bedankt voor uw bug report.

For us to be able to investigate this a bit further I would like to request some addition information. Could you please answer the following questions, and please **do not** specify any account / merchant / store details, only generic information please.

 - Did you experience this only on one and the same device? If not, did you experience this on Android as well?
 - What is the OS version of the device you experienced this issue on?
 - At approximately what time did you experience this issue?
 - Can you walk me through the steps you performed prior to getting to this state?

We would, of course, like to like to get more detailed information, but we would like to request that you submit a support ticket via our developer portal, where you can more securely send us such details. Please visit [https://developer.zettle.com](https://developer.zettle.com) and select "support" in the top right corner (on desktop).

**Comment by basvandorst** [comment]
@ppeelen thanks,
> Did you experience this only on one and the same device? If not, did you experience this on Android as well?

Different devices, only iOS.

> What is the OS version of the device you experienced this issue on?

17.1 and 17.2

> At approximately what date & time did you experience this issue?

Last time today: 3 April, 13:40-13:45 CEST.

> Can you walk me through the steps you performed prior to getting to this state?

Nothing special, just start a normal purchase trx/payment. 


> We would, of course, like to like to get more detailed information, but we would like to request that you submit a support ticket via our developer portal

tbh, i don't have more (technical) information than this. Of course, if you want, i can also raise a support ticket!

**Comment by ppeelen** [comment]
Thank you again for the updated information. 

Unfortunately we have not been able to re-create the issue nor find more info on this specific problem. If the problem persists, I would like you to request a support ticket with our first line support as instructed in my last message. That way we could go more into detail and try to find more information on what might have happened in this occasion.

For that reason I will be closing this incident, but please feel free to include the link in your support request.

**Comment by basvandorst** [comment]
Thanks for your reply @ppeelen 

Already raised a ticket by your support desk and linked to this issue as reference (Case #04175170)
