### ISSUE TITLE
PrivacyInfo.xcprivacy error when submitting to App Store

### ISSUE THREAD

**Issue by planetcoops** [iZettle/sdk-ios#455]
# Expected Behavior

Expect PrivacyInfo.xcprivacy file to be valid

# Current Behavior

Submission fails with the following error:

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/iZettlePayments.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

# Steps to Reproduce

Updated to SDK version 4.0.0 and submitted app to App Store

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

SDK version: 4.0.0

## Failure Logs

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/iZettlePayments.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by nataliq-pp** [comment]
Thank you for reporting this, we are looking into it and will address as soon as possible.

**Comment by planetcoops** [comment]
Fixed via #456

**Comment by nataliq-pp** [comment]
@planetcoops  Thank you for the quick verification of the fix! Let us know if you encounter any other errors or warnings with your app submission.
