### ISSUE TITLE
Which method is used to get the list of readers connected?

### ISSUE THREAD

**Issue by AmanBhattWebkul** [iZettle/sdk-ios#462]
Can you please elaborate on which method is used to get the reader list?
Can we get an empty list when no readers are connected?
What will be the format of the connected reader's data?

**Comment by ppeelen** [comment]
Hi @AmanBhattWebkul!

Currently there is no support in our SDK to provide the list of available card readers. Today the SDK fully handles this internally, if the [charge](https://developer.zettle.com/docs/ios-sdk/user-guides/manage-card-payments#charging) method is called and no reader is connected, the SDK will show the user the UI for pairing their reader with the device.

I've created a task for us to explore the possibility to add support for the requested feature.

If you have any further questions, please do not hesitate to reach out to us again.

Best regards,
Paul Peelen
