### ISSUE TITLE
Feature Request - stay connected

### ISSUE THREAD

**Issue by Clancey** [iZettle/sdk-ios#468]
Our credit card reader is always plugged in, we would like a way to keep the credit card reader awake and ready. Right now when we request payment the device is asleep and needs to re-awake each time.

**Comment by nataliq-pp** [comment]
Hi @Clancey, the reader should not go to sleep mode if it's charging. When the integrating app is re-launched the SDK should quickly re-establish the connection with the reader. Can you please share a few more details about the issue you're experiencing so we can help you best:
1. What is the model of the reader you're using?
2. When you say "always plugged in", do you mean connected directly to a charger or a different setup?
3. When you navigate to your reader in Settings, what status label do you see (e.g "Sleeping" or something else?) and do you see the battery charging icon?
4. When you say "the device is asleep" do you mean that the reader screen is completely off?

**Comment by Clancey** [comment]
Yes, Sorry for the delay. AT our locations we have the zette device mounted in official cradles, as to keep them always charged.
When you say "Quickly" that's a relative term. When you're standing at a checkout counter waiting for the terminal to re-connect. It doesn't feel quick. Since the device is always charging. I would love a api or config to force the device to stay awake  and connected so we don't have disconnects.

**Comment by ppeelen** [comment]
Thank you for your response.

Yes, "quickly" is a relative term. It should take from a few- up to 10 seconds to wake up when the host re-establishes the connection. However, if the supplied USB cable is connected and providing the correct power to the reader, the reader should not "power off" (go to sleep)... even if the host att disconnects. The reader should continue to be powered on if I remember this correctly. The reader powers off only if there is no power source connected.

If you are experiencing that the reader powers off despite it being connected to power, it would be good to contact support. This should not happen. If so, are you experiencing this with multiple readers?

**Comment by ppeelen** [comment]
I've now closed this issue due to inactivity. If this is still an issue, please reopen the issue with further details.

All the best,
/ Paul Peelen
