### ISSUE TITLE
Stuck at "Setting up reader" irregularly

### ISSUE THREAD

**Issue by vladdeSV** [iZettle/sdk-ios#471]
I have been getting reports from multiple of our customers that the Zettle popup gets stuck at "Configuring reader", requiring a restart of the Zettle card reader.

From what I've heard from two managers, this happens almost every morning when they start up the device and when doing the first transaction. After restarting the card reader, every following transaction works fine. The other manager also mentioned this, however with less specifics, but could confirm this happened almost every day. This happened on multiple different devices.

This is an example photo, which shows the text (translated) "Configuring reader":

![photo](https://github.com/user-attachments/assets/b2661639-d271-4971-931b-d3c6049807c0)

I am at loss here, as I cannot reproduce this error reliably – in fact, I've only seen this happen maybe once on my device.

## Other

Is this a known issue? A similar report was filed #453, but it has a different message. I have no idea how to reproduce it.

I have so little to go on, and I can't find anything else that's remotely similar to my issue. Please let me know how to proceed here.

## Context 

* Operating Version: iOS 17 / 18
* SDK version: 3.22.0

**Comment by ppeelen** [comment]
Hi @vladdeSV!

Thank you for reaching out. It seems to me that you are experiencing this issue with our V2 reader. Each time a reader is connected to the POS, it will have to sync with our backend which causes the "Ställer in läsaren" (Setting up reader) message, this can take a bit of time.. however it should complete rather quickly, meaning less then a minute but often around  the 10-20s range for a v2.

In order for us to investigate this further, we would like to get more details with regards to the two merchants you mention. These details, however, cannot be share via Github and we would like you to request a support ticket via our [developer portal](https://developer.zettle.com), using the support button on the top right corder (or via the menu on a mobile device). Please reference this message on Github and include information about the merchants as well as reader serial number (if you have those available).

From what I can see from your issue, it is a different one to the one you linked.

Best regards,
Paul Peelen

**Comment by vladdeSV** [comment]
Thank you for the response @ppeelen, and I'll take this further with the support team.

Just out of curiosity, is there any way for me to artificially create this error on my device? I'm looking to see if I can re-create the problem our customers are having.

**Comment by ppeelen** [comment]
Hi @vladdeSV!

Not to my knowledge. Possibly by setting a slow network connection using Network Link Conditioner on your iOS Device, but even then it should go rather quickly.

Best regards,
Paul Peelen

**Comment by vladdeSV** [comment]
Thanks for the info!

Closing this issue for now.
