### ISSUE TITLE
Unable to pair Paypal reader

### ISSUE THREAD

**Issue by ls-philipp-jacob** [iZettle/sdk-ios#475]
# Expected Behavior

Using the lastest version 4.16.1 of the SDK, I am unable to pair with the new Paypal reader.

# Current Behavior

The modal for selecting the reader type does not list the new Paypal reader.
Selecting any of the available options does not allow me to pair with the Paypal reader.

_Note:_ I'm seeing the same behavior with the latest version 7.86.0 of the Zettle Go app on iOS.

![ConnectCardReader](https://github.com/user-attachments/assets/bda99473-a006-48e5-b0ef-75552f044e74)

# Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start the reader
2. Pressing the power button shows the "Reader number".
3. Initiate a payment with the new SDK version 4.16.1
4. Log in to Zettle account (if not already done before)
5. Trying to connect a reader does not show the new reader type (only "Zettle Reader" and "Reader 2" are shown)
6. (Selecting "Zettle Reader 2" (which seems to have the same pairing flow) does not present any available devices, which is probably expected, I just wanted to mention it here for completeness)

## Context 

I'm not aware of any conditions that may apply.

* Operating Version: iOS 17.7.1
* SDK version: 4.16.1

## Failure Logs

n/a

**Comment by mohannazak** [comment]
Hello Phillip,
Thanks for the detailed description, can you please provide which region your account is?

**Comment by ls-philipp-jacob** [comment]
I think our test account is a German account.

I see that the new reader is only available in Sweden for now. Is there a way to enable the Paypal reader for an existing non-Swedish account or how else can we make this work for testing purposes?

**Comment by mohannazak** [comment]
Thanks for the input; Please reach out to our support page on top right of [this page](https://developer.zettle.com/).
Please provide your test account email(s) for them and also mention this Github issue on your support ticket. We will enable it for you and you can test it by the end of Monday.
