### ISSUE TITLE
The price amount is moving when key board goes away on Refund payment screen 

### ISSUE THREAD

**Issue by Priyalpatel-lightspeed** [iZettle/sdk-ios#48]
**Description**
On refunding payment screen, the price amount is not stable, It's moving when key-board goes away. 

**Steps to reproduce**
Process a payment with the iZettle SDK
Start a refund
Tap on the Password box (key board shows), tap to hide the key-board(Do this 2-3 times and you should be able to see)

**Note** - Only happening on iOS version 8.4

[Price_Moving.zip](https://github.com/iZettle/sdk-ios/files/128736/Price_Moving.zip)

iZettle : M010-PROD13-V2-3
Device Model: iPad mini 3 - A1600
OS: iOS 8.4.1

**Comment by mansbernhardt** [comment]
Thanks a lot for reporting and for providing the really depicting movie. We will look into it.

(Sorry for the late reply)
