### ISSUE TITLE
Getting error message "Payment Cancelled" on swipe of Magnetic strip card 

### ISSUE THREAD

**Issue by alok1upadhyay** [iZettle/sdk-ios#5]
Hi @mattiasjahnke ,

I have successfully implemented refund feature, we will facilitate our merchants with batch refunds, library is working fine.

Today i try to make payment of amount 1 using swipe feature, i was able to connect bluetooth card reader with iPad. iZettle SDK open the animated pop up with "swipe/insert card". When i swipe my magnetic strip card reader it displayed error message "Payment Cancelled".

Then i tried again 9-10 times and it opened signature form as expected. 

Not a big issue but how to avoid this error ?

Thanks,

Alok

**Comment by mansbernhardt** [comment]
Hi Alok,

Where did the UI present "Payment Cancelled", did you enter the view with the progress circle? Did you enter a pin? Did you reach the signature. How close after the swipe did you get the error?

**Comment by alok1upadhyay** [comment]
hi @mattiasjahnke ,

 iPad app was showing "insert/swipe card", as well as bluetooth card reader was displaying "insert/swipe card". I swipe the card and immediately, get the screen "Payment cancelled".

There was neither progress circle nor pin nor signature in between. just swiping the card opened "Payment Cancelled Screen".(is there some thing like invalid swipe you guys handle ? just guessing)

In successful payments i was able to see progress circle and signature screen.

**Comment by mattiasjahnke** [comment]
Not sure if this was some temporary hiccup, but I'm closing the issue for now. Please get back to us if the problem persists.
