### ISSUE TITLE
Memory Leak and Crash

### ISSUE THREAD

**Issue by ghost** [iZettle/sdk-ios#50]
Hi Guys, we are using your library and after doing 3-5 payments the application crash for memory warning.
Looking at Xcode instruments there is leak when the ViewController is displayed.

Can you investigate? As partner we need your support to fix this bug.

**Comment by mansbernhardt** [comment]
Thanks for reporting. I did find a regression causing one of the view controllers in the payment flow not being released that caused a couple of mb each round. This has now been fixed and we will prepare a new release. However, I don't think this leak should cause your app to crash on memory warning after just 3-5 payments (about 10-15 mb of memory leakage in total)?

**Comment by jensutbult** [comment]
Could you please test the beta-1.2.3 branch and see if it solves the issue?

**Comment by mansbernhardt** [comment]
@Apparound, have you been able to test the beta to see if it helps?
