### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by patwhitehead1** [iZettle/sdk-ios#51]
I have imported the iZettle SDK into my project, however there are several duplicate symbols:

- ClearButton
- CardReader
- CardReaderManager

This is conflicting with another framework that we use. Is it possible to have these classes prefixed to avoid duplicates?

**Comment by mansbernhardt** [comment]
This is something we could look into. Is this a comprehensive list of all the collisions you are seeing?

Are those collisions with your code or other third party's code? If the former it might be quicker if you fix the collisions yourselves by prefixing them.

**Comment by mansbernhardt** [comment]
Any progress on this one?

**Comment by mattiasjahnke** [comment]
@patwhitehead1 please get back to us if you're still experiencing problems. Closing this issue for now.
