### ISSUE TITLE
Payment Process Issue

### ISSUE THREAD

**Issue by asa47** [iZettle/sdk-ios#52]
Hello,

When I process a card payment, I receive an error message after inserting the card in the card reader.
The error massage says: "Could not connect to iZettle. An unknown error occured. Please try again later."

Im not sure if it is caused by my iZettle api key, or I could have done something wrong.
Any advice?

Regards

**Comment by mansbernhardt** [comment]
I suspect it's your api key and/or bundle-id that might not be identical to the one you have registered with us. Unfortunately the current version of the SDK does not report this error back correctly. A fix for that will be release in 1.2.3 release.
