### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by iainblight** [iZettle/sdk-ios#55]
Afternoon. 

We received a new API key to integrate into our app as we changed our app bundle name, however now we receive an integration error on screen. Out bundle name is **com.Flex-e-card.Mpos** and the API key is **D08E667FADD60CA9560BA44ABD861800**. Is there a way we can get into some logs to see what the error could be? Any help you could provide would be highly appreciated. 

Regards, 
Iain Blight

**Comment by mattiasjahnke** [comment]
Hey,

The api key and bundle id you provided seems correct. Make sure you have that exact bundle id configured in Xcode.

There is no way of getting any other error messages/logs than you already receive. If you could post the error message you see, perhaps we can have a closer look into what might cause the problem.

Regards
Mattias

**Comment by iainblight** [comment]
Hi Mattias. 

This is sorted at our end, apologies for the hassle. Many thanks for checking. 

Regards,
Iain
