### ISSUE TITLE
'iZettle SDK already started'

### ISSUE THREAD

**Issue by patwhitehead1** [iZettle/sdk-ios#56]
Our app calls [[iZettleSDK shared]startWithAPIKey:] when the user selects iZettle as their default payment gateway. However, if they choose a different payment provider and then switch back to iZettle in the same session, calling [[iZettleSDK shared]startWithAPIKey:] again will result in a crash with this message: 'iZettle SDK already started'.

Is there any way to check if iZettle has started already so that we can bypass this method call?

**Comment by mattiasjahnke** [comment]
Hey!

We recommend you start the iZettleSDK when the app launches.

No, there is no supported way to see if the SDK is started (since it's designed to be started only once upon launch). You could store the information in a variable of your own.
