### ISSUE TITLE
Enforced user login

### ISSUE THREAD

**Issue by andriirogulin** [iZettle/sdk-ios#57]
Hi guys! After updating to version 1.2.3 enforced user logging doesn't work no more. Setting user email to this field doesn't have any effect on iZettle login screen - email field is not pre-filled

**Comment by mansbernhardt** [comment]
Just tried it and it works fine in my tests. Are you sure you haven't changed something else as well?

Could you verify that enforcedUserAccount is set before calling the SDK to display the login UI. Is the email field editable? Could you send us a screen shot?

**Comment by gigeos** [comment]
Hye! I tried to force email account too. In your sample, in your sample, I do it:

```
- (IBAction)charge:(id)sender {

    [iZettleSDK shared].enforcedUserAccount = @"email@test.fr";

    // Note! Replace this reference with your own if you want to be able to query iZettle about payment info and perform refunds.
    _lastReference = [self _uniqueReference];
    NSDecimalNumber *amount = _amountWheel.amount;
    
    [[iZettleSDK shared] chargeAmount:amount currency:nil reference:_lastReference presentFromViewController:self completion:^(iZettleSDKPaymentInfo *paymentInfo, NSError *error) {
        _lastPaymentInfo = paymentInfo;
        _lastError = error;
        _timestamp = [NSDate date];
        
        [self _updateLastPaymentToolbar];
        [self _showConsole];
    }];
}
```
But any email address appear on login page. I have tried to set it in `viewDidLoad` too

**Comment by gigeos** [comment]
Is it possible to show how you solve this problem in your tests, please?

**Comment by mansbernhardt** [comment]
Hi, I downloaded the 1.2.3 release again and can now confirm that a can reproduce the bug. What was different from my previous test, was that I now tried on an iPhone instead of an iPad. Could you verify that it works on iPads but not iPhones?

**Comment by gigeos** [comment]
Yes I confirm that it works on a iPad 9.3.1

**Comment by mansbernhardt** [comment]
Great, thanks a lot for reporting this issue. I have created a fix, that needs to be verified, so we can post a new 1.2.4 release (hopefully tomorrow). @jensutbult make sure to comment on this issue when you have a release ready.

**Comment by gigeos** [comment]
I'm waiting for this fix, thank for your help !

**Comment by gigeos** [comment]
Have you news about merge or stability of current branch 1.2.4 ?

**Comment by jensutbult** [comment]
1.2.4 has been released now and should solve this issue.
