### ISSUE TITLE
iZettleSDK crash for an unhandled exception

### ISSUE THREAD

**Issue by Rauleinstein** [iZettle/sdk-ios#58]
Hello guys, In the recent development we have some crashes due to the iZettleSDK. I have a trace to help you debug this. 
Last Exception Backtrace:
0   CoreFoundation                  0x1848c5900 __exceptionPreprocess + 124
1   libobjc.A.dylib                 0x183f33f80 objc_exception_throw + 56
2   Bubblmee Kiosk                  0x100154288 -[iZettleSDK _validateConditions:](iZettleSDK.m:264)
3   Bubblmee Kiosk                  0x1001552c0 -[iZettleSDK(Operations) abortOperation](iZettleSDK.m:350)
4   Bubblmee Kiosk                  0x1001114d0 -[BMPaymentProgressViewController homeTimeout](BMPaymentProgressViewController.m:273)

If you need I can give you the full crash but that has be more private.

**Comment by mansbernhardt** [comment]
Hi,

Note that we really think you should have good reason to use abortOperation as stated in the header:

/*! Attempt aborting the ongoing operation. Only use this if absolutely necessary. The state of the payment will be unknown to the user after this call. */
- (void)abortOperation;

Could you explain why you think it is necessary for you app to use abortOperation?

Back to the crash, I think in your case you are running into one of our asserts that you must call this from the main thread and that the API has to have been started. But the exception thrown should give you more info.

/Måns

**Comment by Rauleinstein** [comment]
Thank you Måns, my point was that the whole app crashed badly, maybe this exception should be handled differently. I'll fix my code to use that abortOperation only when need it.

**Comment by mansbernhardt** [comment]
We could respond with an error, but similarly as out of bounds and requirement to call UI code from the main thread, we see these as integration/programming errors, hence we want to assert hard as early as possible.
