### ISSUE TITLE
Manual Entry

### ISSUE THREAD

**Issue by pcobas** [iZettle/sdk-ios#6]
When selecting manual entry, upon tapping on any field ,the keyboard automatically dissapears.
This is also happening in Visa Payment screen, when tapping the country code.

**Comment by mattiasjahnke** [comment]
Hi @pcobas!

This is not a behaviour we're familiar with. Does your app contain any keyboard-handling logic? For example listening for keyboard events and taking actions such as resigning the first responder?

/Mattias

**Comment by mattiasjahnke** [comment]
@pcobas I'm closing this. Please get back to us if the problem persists.
