### ISSUE TITLE
Disable logout button once logged in

### ISSUE THREAD

**Issue by cedricdevriendt** [iZettle/sdk-ios#60]
Is it possible to disable the logout button once a user is logged in?
Or maybe keep the button visible, but ask for the password if you want to logout?

We have a customer facing application and we don't want the customer to log out and mess up the configuration of the application.

**Comment by vtim** [comment]
👍

**Comment by Shadowstyler** [comment]
You could put the iPhone in guided access and modify the accessible regions.

**Comment by valkovsky** [comment]
Hi!
As of now it's not possible to remove it. We're looking into options of how to improve the logout functionality
