### ISSUE TITLE
App crash on chargeAmount

### ISSUE THREAD

**Issue by thomasnordquist** [iZettle/sdk-ios#61]
We tried to integrate the SDK with our App but when we call chargeAmount and login with the test credentials the app crashes on login.

```
Terminating app due to uncaught exception 
'NSUnknownKeyException', reason: '[<IZAccount 0x1748f400> setValue:forUndefinedKey:]
: the entity Account is not key value coding-compliant for the key "lastModified".'
```

We have no trouble with the example and an empty project.

Do you have any idea what happens here ?

**Comment by mattiasjahnke** [comment]
Hey @thomasnordquist 

Sounds some sort of collision with our code bases. Could you send the snippet from your code were you use "lastModified"?

**Comment by thomasnordquist** [comment]
lastModified ist an attribute of our AppProfile entity
Is there a chance that you also try to persist an AppProfile entity ?

After I renamed our "AppProfile" entity we got a new error.

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSFetchRequest could not locate an NSEntityDescription for entity name 'Account''
```

**Comment by mattiasjahnke** [comment]
Do you have a core data datamodel called "Account"?

**Comment by thomasnordquist** [comment]
Fixed it !
We didn't have a namespace collision (I checked your datamodel).
Some code tried modify your entities, after adding a safeguard it works as expected.

Thanks for your help !
