### ISSUE TITLE
Error: "Incorrect integration"

### ISSUE THREAD

**Issue by rachidfinge** [iZettle/sdk-ios#62]
When attempting to integrate the iZettle SDK in our app, the “Incorrect integration” error appears after using iZettle’s login form provided by the SDK. The issue appears both on the iOS Simulator as well as on our test device, an iPhone 6s Plus running iOS 9.3.1.

The Bundle ID of the app is one we submitted to your team earlier. 

At launch of the app, in the App Delegate, we use the startWithAPIKey method as follows:
`[[iZettleSDK shared] startWithAPIKey:@"our-key-as-provided-by-iZettle"];`

The following is the entry in info.plist:

```
    <key>UISupportedExternalAccessoryProtocols</key>
    <array>
        <string>com.miura.shuttle.izettle</string>
    </array>
```

Then, to initiate a charge, we make the following call:

```
    NSString *amount = [NSString stringWithFormat:@"%f", totalPrice];
    [[iZettleSDK shared] chargeAmount:[NSDecimalNumber decimalNumberWithString:amount]
                             currency:@"EUR"
                            reference:@"reference"
            presentFromViewController:self
                           completion:^(iZettleSDKPaymentInfo * _Nullable paymentInfo, NSError * _Nullable error) {
                               NSLog(@"completion, payment info: %@   error: %@", paymentInfo, error);
                           }];
```

This call makes the login form appear. We’re using demo credentials provided by iZettle by email (username = demo.nl@izettle.com).

This is the point where the "Incorrect integration" error appears. From the NSError object:

`Error Domain=com.izettle.account.error Code=2 "Payment error / Incorrect integration. Contact your app provider." UserInfo={izTitle=Payment error, NSLocalizedDescription=Payment error / Incorrect integration. Contact your app provider., izMessage=Incorrect integration. Contact your app provider.}`

Please advice.

Finally, I'd like to point out that emails to sdk@izettle.com, as mentioned on this GitHub account, went unanswered for a week and counting.

**Comment by mattiasjahnke** [comment]
Hey @rachidfinge 

The error message you describe will be shown if the API key and Bundle ID provided doesn't match what we have in our systems. What's the bundle ID you're using?

**Comment by rachidfinge** [comment]
The Bundle ID is `nl.Deviate.wol.Doorbitch`.

**Comment by mattiasjahnke** [comment]
Thank you, we will investigate what happened.
