### ISSUE TITLE
Getting iZettle SDK/Device status

### ISSUE THREAD

**Issue by leonid-s-usov** [iZettle/sdk-ios#64]
Hi,

I don't seem to find even minimal API to get the status of the SDK
- If any user is logged in
- name of currently logged in user
- if the device is online
- if a transaction is in progress

This is minimal to make the UX better with presenting the user with an up to date information regarding the payment device.
Maybe the methods are there, but not yet exposed via the public API? Is it possible to get that information somehow?

**Comment by mansbernhardt** [comment]
Hi,

Can you please give us some more background on why you need these features and how you would use them? We try to keep the SDK API surfaces as small as possible to remove a lot of problems for both us and you. To open up more API's there should be really good reason for it.

"If any user is logged in"
Not sure why you need this? With fast user switching there can be 0-n users "logged in" at the same time.

"name of currently logged in user"
See above

"if the device is online"
What does online mean? We can have 0-n readers connected at once using different technologies such as audio, bluetooth etc. Why do you need that info?

"if a transaction is in progress"
Which part of the transaction. You initiated one and get a completion when it is done.
As the SDK takes over the screen during a transaction, I'm not sure what you would use that info for?

**Comment by leonid-s-usov** [comment]
Let me complete the integration as of now and I will be able to respond with more details. I am new to the SDK, and am trying to build it into an existing UX where if have a list of payment providers with statuses and ability to see all connected devices and if they are online in the settings of my application. Similarly, before the checkout I would like to give a user an option to choose from available payment methods and those should be somehow detected as available prior to building this list.
In any case, I will update once I understand better the flow of iZettle - probably I want something it wasn't designed for

**Comment by leonid-s-usov** [comment]
So, like I mentioned before, I would love to get at least some indication of the current availability of devices and the fact that there is at least one current active account logged in from the SDK to properly update my UI

**Comment by leonid-s-usov** [comment]
May I have any update here? If it is acknowledged as something to improve, or it is still unclear?

**Comment by mansbernhardt** [comment]
Hi, 

We need to better understand why it is important for you to know which is the current active account. We need you to also define what that means to you as there might be many active accounts at once (due to fast user switching), and enforcedUserAccount will affect what account will be used when you start a payment.

As for devices (and payment methods), this is not that straightforward to expose and might change between releases, hence to make the API as simple as possible this is something we would try to avoid. This is also not a request we heard from other users.

**Comment by leonid-s-usov** [comment]
OK I understand that you need to be generic, but in my POS application I don't see a good use-case of the fast user switching, to be honest.
We support a number of payment providers in our app and there is a generic configuration screen where you can enable/disable a provider. It is just a matter of consistency and UX for me, as I would like to notify the user in my UI if the iZettle SDK has been configured or not, and if it is not then I would even not render the "pay with iZettle" button on the checkout.

But that doesn't seem like a big issue to me even if you have multiple accounts logged in - why not expose an array of emails, with the first one being the current account, or something like that?

Connected devices list is not straightforward, I see, but maybe at least some indication if at least one device is present would be really nice from an SDK like yours. It's just too inflexible if I need to present your view controller should I want to display any info about the current state.

**Comment by leonid-s-usov** [comment]
1.4 is out, but no event simple api to get the sdk login status..

**Comment by leonid-s-usov** [comment]
Any updates here? I would really appreciate a simple way to know if the SDK is configured or not, prior to popping up the controller.

**Comment by mansbernhardt** [comment]
@leonid-s-usov I don't think we should expose emails but we might consider expose a method such as:
```objc
- (BOOL)hasActiveSession() // Will respect the current enforced user account
```

Would that be helpful?

**Comment by leonid-s-usov** [comment]
That would be really helpful, yes!

**Comment by mansbernhardt** [comment]
"We support a number of payment providers in our app and there is a generic configuration screen where you can enable/disable a provider."

@leonid-s-usov Trying to understand what you are trying to achieve. By being  "configured" or "enabled" what do you mean by that? Do you mean to have an active session? But how would you enable/disable an active session from this configuration screen, using the current SDK API?

**Comment by leonid-s-usov** [comment]
On the configuration screen the "iZettle" provider will appear as not activated until it reports at least one active session. When accessed in the settings, your configuration controller is pushed

On the payment screen iZettle will not be an option if it is reported as "inactive", i.e. without any active session.

**Comment by mansbernhardt** [comment]
@leonid-s-usov Please have a look at https://github.com/iZettle/sdk-ios/tree/sdk_version_1.4.1

**Comment by leonid-s-usov** [comment]
The link is broken :(

**Comment by leonid-s-usov** [comment]
OK, nice! Indeed, I have seen the `hasActiveAccount` in the 1.4.1
Why isn't it there at 1.5? We have already updated long ago to that version.
