### ISSUE TITLE
Be able to force login and password

### ISSUE THREAD

**Issue by gigeos** [iZettle/sdk-ios#66]
Hi guys! We need to prevent users to login because all of them use same account, so email and password have to be setted. Is it possible to have that?

Thanks!

**Comment by mansbernhardt** [comment]
Hi,

You can only force to use a certain user, but we won't allow you to handle iZettle users passwords. From the docs:

### Enforced User Account

- **enforcedUserAccount** _(optional)_: If set, operations will be restricted to only work for the specified iZettle username.

By setting the shared instance property **enforcedUserAccount** to an iZettle username, subsequent operations will be 
restricted to only be performed on that account. If the set enforced user account was not previosuly logged in, an 
iZettle login prompt will be presented with a readonly email field prefilled with the enforced user account. If the 
enforced user account was already logged in (even though another account has been used in between), the account will 
be switched to use the enforced user account account instead. 

If **enforcedUserAccount** is set to nil, any iZettle account can be used, and the email field will be editable.

Enforced user account can be changed between operations to allow switching between different users for different 
operations. This is useful for integrators supporting multiple accounts. 

Preferably integrating apps will provide a settings page where the user can enter their iZettle account (used to 
set the enforced user account).

**Comment by gigeos** [comment]
Thank you for your answer! Yes I use enforcedUserAccount for the moment but is it possible to add a method to your SDK to set email and password ?

**Comment by mansbernhardt** [comment]
We have not current plan (and the SDK would probably never allow) the third party integrator handle iZettle passwords. We might in the future allow you to login to e.g. a web site and provide a authentication token or something similar that you could pass to the SDK.

**Comment by gigeos** [comment]
Ok thanks for your answer!
