### ISSUE TITLE
Wrong Password Can Be Entered More Than 10 Times

### ISSUE THREAD

**Issue by chrisjf** [iZettle/sdk-ios#72]
### Description

When the user is refunding a payment, they must type in their password. After typing in their password incorrectly multiple times, the user can continue to try typing in their password. I don't know if it's the demo account I am using that has maximum password attempts disabled (externaldemo@izettle.com) or if it's for all accounts. This could possibly be an attack vector to guess a user's password.
### Steps to reproduce
- Process a payment with the iZettle SDK
- Start a refund
- Tap on the Password box and incorrectly type in your password 10 times
### Actual Results
- Nothing happens; you can continue trying to guess the password
### Expected Results
- Eventually after 10 attempts you should have to wait a minute to try your password again, or enter a "Are You Human" CAPTCHA code, or some other security measure.
### Reproduced Using

iZettle SDK: v1.2.2
Device Model: iPad Air A1474
OS: iOS 9.3.2
### Screenshots

![Refund](https://cloud.githubusercontent.com/assets/105042/16242579/04adf13a-37c1-11e6-954d-08e753a3f339.PNG)

**Comment by mansbernhardt** [comment]
Hi,

Thanks for reporting. We have currently disabled the check for number of failed attempts for refunds. Earlier we had that enabled, but it caused a lot of problems with users getting their account block etc. We have discussed this problem internally and potential improvements, but have currently nothing new to report.
