### ISSUE TITLE
iZettle SDK resets UIView.animationsEnabled property

### ISSUE THREAD

**Issue by mgamer** [iZettle/sdk-ios#73]
In our iPad app we prefer to disable all UI animations in order to speed up transitions between views.

We do it by executing `[UIView setAnimationsEnabled:NO]` in `application: didFinishLaunching:` in `AppDelegate`. It seems that showing up iZettle payment dialog reenables animations. 

Could you let me know if this is a bug or intended behaviour?

**Comment by mansbernhardt** [comment]
Yes we might have a collision here. Not sure how to best solve it though. The SDK could save the state before changing it, and restore it back when it is done. It might partly solve the problem but not the cases where you might change it in the middle of this. For your interest our app is using a push pop abstraction to handle this.

When are you changing this, only once at app startup or continuously?

**Comment by mgamer** [comment]
Thanks for your quick answer! We set `UIView.animationsEnabled` to `false` only at the app launch. For now we can restore `UIView.animationsEnabled` property to `false` each time an iZettle transaction is finished processing. Nevertheless we would truly appreciate having the solution implemented in the SDK itself.

**Comment by leonid-s-usov** [comment]
@mansbernhardt, has this been addressed in the version 1.4 of the SDK?

**Comment by mansbernhardt** [comment]
@leonid-s-usov Do you have a similar problem? This kind of issues are hard to solve when two independent code base share the same code base and Apple design bad api:s using global switches such as this one.

**Comment by leonid-s-usov** [comment]
We are working on the same application. Just wanted to understand if anything was changed regarding the issue.

Yes, this particular aspect is not very well designed, but I believe that the SDK should clean up after itself in case it alters some global state.

**Comment by mansbernhardt** [comment]
@leonid-s-usov & @mgamer please have a look at https://github.com/iZettle/sdk-ios/tree/sdk_version_1.4.1 to see if it solves your issue with animations.
