### ISSUE TITLE
Distinguish contactless and Apple Pay transactions

### ISSUE THREAD

**Issue by PawelDecowski** [iZettle/sdk-ios#75]
I know — not an issue per se. But I couldn’t find a better communication channel.

So in `iZettlePaymentInfo` there is a property `entryMode` which equals to `CONTACTLESS_EMV` for contactless payments. Is it the same for Apple Pay? Is there any way to tell the transaction was an Apple Pay one?

**Comment by TomasPro** [comment]
Hi Pawel,

Apple Pay can operate in both EMV (contactless_EMV) and magstripe (contactless_magstripe) modes - the former being the case for 100% of EU issued Apple Pay cards and the latter will most likely only be prevalent in the US.

As for being able to tell that a transaction was an Apple Pay one: during a contactless/NFC payment the contactless card/phone/watch/device may (optionally) provide information to the Reader about its 'Form Factor' (card, mobile device, non-card). Our infrastructure however does not at this point support the functionality to inform the App about the form factor. Even if that was however possible, there would still not be any option to distinguish among different mobile based wallet solutions - e.g. Apple Pay vs Android Pay vs Samsung Pay etc.

I hope that answers you question.
