### ISSUE TITLE
Apple MFI Approval Process - no reply from sdk@izettle

### ISSUE THREAD

**Issue by mihird** [iZettle/sdk-ios#78]
I have received API key and the app is ready for release.

I've been mailing SDK team since 2 weeks at sdk @izettle as instructed here , but haven't received any reply.

Apple won't approve my app without MFI Product Plan ID (PPID).

Can anybody help me here?

**Comment by mattiasjahnke** [comment]
Hi,

Sorry it's been taking so long! I know a lot of my co-workers are on summer vacation, I'll see what I can do.

/Mattias

**Comment by mihird** [comment]
Thanks Mattias.

I've mailed my app details to you. Hope I can release my app soon.
