### ISSUE TITLE
iZettle SDK Crash

### ISSUE THREAD

**Issue by dclerc** [iZettle/sdk-ios#8]
Got the following crash today with iZettle SDK 1.1. Running in iOS 7 simulator.
![izettle-sdk-crash](https://cloud.githubusercontent.com/assets/915049/8086158/361b03c6-0f94-11e5-94bb-516257d87fe6.png)

**Comment by mattiasjahnke** [comment]
Hi @dclerc 

Are you able to reproduce the crash every time?

**Comment by dclerc** [comment]
No, it only happened once in two weeks.

David

**Comment by mattiasjahnke** [comment]
Closing this, please get back to us if you're still experiencing this
