### ISSUE TITLE
iZettle settings view not displaying properly

### ISSUE THREAD

**Issue by patwhitehead1** [iZettle/sdk-ios#80]
We have recently updated to 1.3.0 and the settings view is not displaying correctly. Please see screenshot:

![simulator screen shot jul 25 2016 4 31 00 pm](https://cloud.githubusercontent.com/assets/5133878/17116495/0a61ab6e-5286-11e6-81f2-76be831e7886.png)

**Comment by mattiasjahnke** [comment]
Hey Patrick,

This was indeed strange.

1) Is there a navigation bar at all?
2) Make sure all frameworks are included correctly according to the installation guide. We're missing some styling (the "forgot your password" is supposed to be blue)
3) If you enter an e-mail and password in order for the "Sign in"-button to become enabled, what color is it?
4) What version of iOS are you running in this simulation?
5) Are you doing some `UIAppearance` styling or swizzling that could interfere with out styling logic?

**Comment by patwhitehead1** [comment]
Thanks Mattias,

1) Please see new screenshot (taken when using the debug view hierarchy tool).
2) All three frameworks have been included (added into embedded frameworks).
3) Entering a username and password does not change the sign in button. The entered text also does not appear to be visible (but the placeholder text disappears).
4) iOS 9.3
5) As far as I can see, we are not changing anything in UIAppearance that would affect this.
6) The sample app works fine, no issues.

![screen shot 2016-07-26 at 11 22 50 am](https://cloud.githubusercontent.com/assets/5133878/17145469/441cda0c-5328-11e6-8746-e52616955b2d.png)

**Comment by mattiasjahnke** [comment]
By using the debug view hierarchy tool, can you see *why* components aren't showing? Are they white? Alpha = 0? Hidden = true?

**Comment by patwhitehead1** [comment]
I'm unable to see why this is happening. Here is what I found in the debug view hierarchy:

email text field: 
<IZTextField: 0x7fcbbc7b1f80; baseClass = UITextField; frame = (8 18; 435 28); text = 'test@test.com'; clipsToBounds = YES; opaque = NO; gestureRecognizers = <NSArray: 0x7fcbbc7bc240>; layer = <CALayer: 0x7fcbbc7b0090>>

clear button (and label on that button): 
<ClearButton: 0x7fcbbc750c40; baseClass = UIButton; frame = (15 30; 78 24); opaque = NO; tintColor = UIDeviceRGBColorSpace 0.368627 0.470588 0.556863 1; layer = <CALayer: 0x7fcbbc750f10>>

<UIButtonLabel: 0x7fcbbc71ae00; frame = (10 0; 58 24); text = 'Cancel'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fcbbc7783d0>>

**Comment by mattiasjahnke** [comment]
Hi @patwhitehead1 sorry for the delay.

I don't really know what causes this behavior, and I'm not sure how to go about solving this since we can't reproduce it here, and the sample app is working for you. So there must be something in your app (integration/usage, or some logic in your code) that is causing this.

We've never seen this on our side or from any other integrator.

I think that a good way forward is using the view debugger trying to understand why the views aren't shown (perhaps compare your apps debugging and a debug on the sample app).
