### ISSUE TITLE
iZettle Payment Methods

### ISSUE THREAD

**Issue by JoshWilliams92** [iZettle/sdk-ios#82]
I was just wondering if you are able to get data on cash payments or is it only card & contactless payments?

**Comment by mattiasjahnke** [comment]
Hey @JoshWilliams92 

The iZettle SDK only supports card payments

**Comment by JoshWilliams92** [comment]
Ok, not a big deal and thanks for the quick response. Would customers have to sign into their iZettle account to access reports on cash payments from the till?

**Comment by mattiasjahnke** [comment]
Cash payments made from the official iZettle app will be visible amongst the reports and transaction history on my.izettle.com and in the iZettle app. Does that answer your question?

**Comment by JoshWilliams92** [comment]
Yes it does, thanks! I have had a look through the HTTP API docs and I have found what I needed. I may use both the Mobile SDK and the Rest API.
