### ISSUE TITLE
Issue updating SDK to 1.3.0

### ISSUE THREAD

**Issue by sanaqvi** [iZettle/sdk-ios#83]
Hi,

We have integrated our productwith iZettle card reader Pro in the past and it was working fine without any issues at all. Since izettle has introduced new card reader that means we have to update SDK at our end to make it work. 

Issues following SDK upgrade:

- Can not connect to new card reader 
- Can connect to old Pro and take payments.
- Please see attached screen shot, following SDK update (using Pod method), It still shows SDK 1.2.5. is this normal? or must show 1.3.0?????

We have adopted a method of Pod  as given on GitHub but we don’t know whether it has fetched the new SDK version 1.3.0 because during update, it was showing 1.2.5 version on command line. Please see below.
Is this normal? if not then why it is not picking up right version rom Github? We are using old API key that we have used for the Pro reader and i don’t think we need new API key or new card reader do we?

pod update
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Update all pods
Updating local specs repositories

CocoaPods 1.1.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using PNChart (0.8.9)
Using UICountingLabel (1.2.0)
Using iZettleSDK (1.2.5)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 3 total
pods installed.

I will appreciate your quick response.

**Comment by mattiasjahnke** [comment]
Hi,

Could you please share your iZettleSDK-entry in the Podfile?

Regarding the new reader not connecting, did you add it's accessory protocol string to your plist?

```
<key>UISupportedExternalAccessoryProtocols</key>
<array>
    <string>com.izettle.cardreader-one</string>
    <string>com.miura.shuttle.izettle</string>
</array>
```

**Comment by sanaqvi** [comment]
Hi,

Yes we do have those entries.

Pod file Entry:
pod 'iZettleSDK'

info.plist file:

<key>UISupportedExternalAccessoryProtocols</key>
	<array>
		<string>jp.star-m.starpro</string>
		<string>com.miura.shuttle.izettle</string>
		<string>com.izettle.cardreader-one</string>
	</array>

**Comment by mattiasjahnke** [comment]
For some reason `pod update` doesn't seem to update to the latest version.

https://cocoapods.org/?q=izettle 1.3.0 is the latest available on cocoapods.

Try `pod update --verbose` and see if there are any errors during the update.

**Comment by sanaqvi** [comment]
Hi,

Developer has managed to fix the problem with Pod. It has taken 1.3.0 now and installed it. but on compilation it is showing following error. Any idea how can we resolve it?

dyld: Library not loaded: @rpath/iZettlePayments.framework/iZettlePayments
  Referenced from: /Users/****/Library/Developer/CoreSimulator/Devices/****/data/Containers/Bundle/Application/*****/JusteMenu_iPad.app/JusteMenu_iPad
  Reason: image not found

Please note i have put **** to hide few things.

**Comment by mattiasjahnke** [comment]
Hey,

Not without fiddling around myself - your developer can probably sort it out. That looks like a problem not related to our sdk but your projects settings and integration with the sdk which makes it harder for me to help you out.

**Comment by karlvr** [comment]
@mattiasjahnke a small note; the README around external accessory—the text above the example code doesn't mention the new external accessory protocol that needs to be added for 1.3.

**Comment by sanaqvi** [comment]
We managed to resolve issue couple of days ago.

Thanks for your support.
Syed Naqvi | Director| IT Platforms | Development and Delivery | Technology & Transformation
Biz Outsourcing Solutions Ltd UK

M 00-44-7595932206 | E sanaqvi@bizoutsourcingsolutions.com <mailto:sanaqvi@bizoutsourcingsolutions.com>
Has someone impressed you or made your day a little easier? Give them a SHOUT!

P Save Paper – Do you really need to print this email?

**Comment by sanaqvi** [comment]
we have managed to resolve issue couple of days ago.

thanks for your support

**Comment by mattiasjahnke** [comment]
Thanks @karlvr - we'll look into how we can make it more clear!

Great @sanaqvi - Was there anything in our documentation we should improve to make the integration easier for other integrators?

**Comment by asa47** [comment]
Hello @sanaqvi, I am trying to integrate the new SDK, however I have encounter your same error: 

`dyld: Library not loaded: @rpath/iZettlePayments.framework/iZettlePayments
  Referenced from: /var/mobile/Containers/Bundle/Application/***
  Reason: image not found`

Could you please tell me how you managed to remove the error?

Kind Regards

**Comment by sanaqvi** [comment]
Hi Russell,

I will ask my development team and get a note on resolution of this issue. I will certainly share it at some point tomorrow.

Thanks
Syed

**Comment by asa47** [comment]
Hello, I just solved the issue, and thanks for the quick reply! @sanaqvi. 

Just in case anyone get into the same issue just look at this:
[http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta](url)
