### ISSUE TITLE
New terminals connection error

### ISSUE THREAD

**Issue by andriirogulin** [iZettle/sdk-ios#84]
Hi there!

Our team got a problem:
The new iZettle terminal (https://www.izettle.com/no/card-readers/izettle-reader) is no recognised as connected within the SDK part of our app. It is connected in bluetooth. The terminal display says "Connected to iPhone”.
The iZettle app displays the terminal as connected, but SDK in our app doesn’t see it.
I updated the firmware for terminals

**Comment by mattiasjahnke** [comment]
Hi @andriirogulin 

Did you upgrade to SDK version 1.3.0 and followed the integration guide (especially the section of adding the accessory protocol string to you .plist)?

**Comment by andriirogulin** [comment]
Yep, but it doesn’t work

**Comment by mattiasjahnke** [comment]
Does it work in the sample app?
Does it work if the iZettle app isn't installed on the device?

**Comment by mattiasjahnke** [comment]
Closing this issue, please reopen if the problem persists

**Comment by andriirogulin** [comment]
Looks like the problem is fixed, thanks!

Regards,
Andrii
