### ISSUE TITLE
iZettle New device connection problem

### ISSUE THREAD

**Issue by divyanshyadav** [iZettle/sdk-ios#85]
First, I have tested new iZettle device on SDK 1.2.3 but its now showing terminal there. After that I have updated the iZettle SDK to 1.3.0 but its still now showing on iZettle payment screen. All the old iZettle devices are connecting fine. Am I missing something?

**Comment by mattiasjahnke** [comment]
Hi @divyanshyadav 

Make sure you've added the accessory protocol identifier in you plist:
https://github.com/iZettle/sdk-ios#5-setup-external-accessory-protocols-in-infoplist

**Comment by mattiasjahnke** [comment]
Closing the issue, please re open if the problem persists
