### ISSUE TITLE
App Store rejects an app with iZettle 1.3.0.1

### ISSUE THREAD

**Issue by vorobievalex** [iZettle/sdk-ios#86]
Application loader returns error:
[Transporter Error Output]: ERROR ITMS-90087: "Unsupported Architectures. The executable for POS.app/Frameworks/iZettlePayments.framework contains unsupported architectures '[x86_64, i386]'."

The app architectures are "armv7, arm64"
iZettle is linked through Podfile:
    pod 'iZettle',          '~> 1.3.0.1'

**Comment by mansbernhardt** [comment]
Hi, perhaps you have run into the following from our docs:

### 4. Create a new “Run Script Phase” in your app’s target’s “Build Phases” and paste the following snippet in the script text field:

    bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/iZettleSDK.framework/strip-frameworks.sh"
 
This step is required to work around an [App Store submission](http://www.openradar.me/radar?id=6409498411401216) bug when archiving universal binaries.
