### ISSUE TITLE
New SDK terminal update issue

### ISSUE THREAD

**Issue by dclerc** [iZettle/sdk-ios#87]
We're unable to use the latest iOS SDK in our product as we are constantly getting an "unknown error" when the SDK attempts to upgrade the terminal's firmware.

We reproduced the issue with the App Store iZettle App, therefore it's not an issue with our app or how we integrated the SDK with our app.

Here's the scenario
- Pair the DATECS reader to the iPad
- Launch the iZettle app
- Add an item and pay with iZettle
- The SDK screen starts and shows "Updating card reader" for 2 seconds and then fails with the message "An unknown error occurred". This repeats a second time and then move to the "Insert/Swipe card" screen
- If I insert a card it says "Reading card" then "Updating card reader", then "Cannot connect to iZettle" and then "An unknown error occurred"

The accessory details are DATECS PMSCBIR6PETM firmware 1.2.3, hardware 3.2.1.

Please assist as this is keeping us from releasing a new version of our app to the App Store and is negatively impacting our clients who are using iZettle.

**Comment by linnie** [comment]
Hello @dclerc ,
sorry to hear that you are experiencing problems with our service. In order for me to investigate further, could you please supply me with the login address you have used during the failed attempts?

Thank you,

Best regards

Linnie

**Comment by dclerc** [comment]
Can you provide me an email address where I can send you my login address? I don't want to post that on GitHub.

**Comment by linnie** [comment]
Yep, understand, linnie@izettle.com
