### ISSUE TITLE
Card brands list

### ISSUE THREAD

**Issue by iabdullin** [iZettle/sdk-ios#88]
Hello team,

  Customers that use iZettle integration complain that some of card types are reported in Revel merchant console as "Other". This happens due to cardBrand is returned as a string and POS tries to parse it. Do you have a list of pre-defined card brands in iZettle SDK? In that case we can extend our parsing logic and provide more accurate results to customers.

Thanks,
Ildar

**Comment by mansbernhardt** [comment]
Here is the current list (but remember that it might change over time).

VISA
MASTERCARD
AMERICAN_EXPRESS
MAESTRO
JCB
DINERS
GIROCARD
V_PAY
VISA_ELECTRON
CARNET
UNION_PAY
CB
UNKNOWN

**Comment by iabdullin** [comment]
Thanks
