### ISSUE TITLE
Crash in `-[IZettleNetworkContext(Networking) appendHeadersToRequest:]`

### ISSUE THREAD

**Issue by karlvr** [iZettle/sdk-ios#89]
We have seen the following crash in production with the 1.3 SDK. It occurs during the init of the SDK. The API key doesn't change, so this appears to be something unusual happening inside the SDK?

```
Crashed: com.ReactiveCocoa.RACScheduler.mainThreadScheduler
0  iZettlePayments                0x10166b000 -[IZettleNetworkContext(Networking) appendHeadersToRequest:] + 420
1  iZettlePayments                0x10166b39c -[IZettleNetworkContext(Networking) requestWithURL:legacyJson:] + 156
2  iZettlePayments                0x1016d89e0 __75-[IZettleTranslationsDataSource downloadTranslationsForLanguageIdentifier:]_block_invoke + 592
3  iZettleShared                  0x101906860 +[IZFuture(Utilities) performOnlyOneAtTheTimeForKey:block:] + 356
4  iZettlePayments                0x1016d8754 -[IZettleTranslationsDataSource downloadTranslationsForLanguageIdentifier:] + 144
5  iZettlePayments                0x1016d7720 -[IZettleTranslationsDataSource setupLanguageWithLanguageIdentifier:] + 272
6  iZettlePayments                0x1016d7534 -[IZettleTranslationsDataSource setOverrideLanguageIdentifier:regionLocale:] + 356
7  iZettlePayments                0x1016d72ac -[IZettleTranslationsDataSource init] + 352
8  iZettleSDK                     0x101876c78 -[iZettleSDK startWithAPIKey:] + 444
```

In this case `-[iZettleSDK startWithAPIKey:]` is called by a ReactiveCocoa signal on the main thread. The crash was `EXC_BAD_INSTRUCTION 0x0000000088d07182`.

We've seen the crash twice so far from one user, so perhaps there is something about the user's setup. Noting the language identifier mentions in the stack, perhaps the user has an odd language configured on their device?

The crash occurred on an iPad Air running iOS 9.1. The user was in New Zealand. If there are any questions you'd like us to ask of the user, please let me know.

**Comment by mattiasjahnke** [comment]
Hi @karlvr sorry for the late reply.

Sounds like the language/region configuration could be the problem here, yes. We'll investigate!
