### ISSUE TITLE
Request: function to see if there is a user currently logged in

### ISSUE THREAD

**Issue by roycef** [iZettle/sdk-ios#9]
There is currently no way to see if there is an authenticated user.  If you provide a function to call and see if there is an authenticated user with a valid session it will allow us to provide better messaging to the user with in our app and to display your views so they can log themselves in if required. 

A simple return of a bool is fine but it would be 'nice to have' the email address of the current user's account returned.

**Comment by cflorion** [comment]
I agree, in terms of user experience, this is missing indeed :)

**Comment by mattiasjahnke** [comment]
Please refer to #16
