### ISSUE TITLE
Version 1.3.0 doesn't work with CocoaPods 0.39.0

### ISSUE THREAD

**Issue by mastohhh** [iZettle/sdk-ios#91]
With CocoaPods, `strip-frameworks.sh` is not in `${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}` but in Pod's directory ?

```
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/iZettleSDK.framework/strip-frameworks.sh"
```

I think there is the same problem inside `strip-frameworks.sh` [L39](https://github.com/iZettle/sdk-ios/blob/master/iZettleSDK/iZettleSDK.framework/strip-frameworks.sh#L39)

How do I install iZettle SDK with CocoaPods ?

**Comment by jensutbult** [comment]
I just verified that strip-frameworks.sh is in the iZettleSDK.framework directory when installing from Cocoapods. Does Xcode complain when you try to run the shell script during the build phase?

**Comment by mansbernhardt** [comment]
What version of XCode are you using?

**Comment by mastohhh** [comment]
I tried weeks ago with Xcode 7, and now Xcode 8, same problem.

When I build, Xcode error is : 

`bash: /Users/masto/Library/Developer/Xcode/DerivedData/myapp-bgdasqfzwyavakgncsrmddfxllqv/Build/Products/Debug-iphonesimulator/myapp.app/Frameworks/iZettleSDK.framework/strip-frameworks.sh: No such file or directory`

**Comment by jensutbult** [comment]
Is there a strip-frameworks.sh file in the iZettleSDK.framework?

**Comment by mastohhh** [comment]
Yes, but the framework is in the Pods' directory.

**Comment by jensutbult** [comment]
That's alright. It's copied into the Frameworks directory during the build process. What's in iZettleSDK.frameworks in your build directory (the one the error is pointing at)?

**Comment by mastohhh** [comment]
Ok. There's no iZettle Framework in `/Users/masto/Library/Developer/Xcode/DerivedData/myapp-bgdasqfzwyavakgncsrmddfxllqv/Build/Products/Debug-iphonesimulator/myapp.app/Frameworks/`

**Comment by jensutbult** [comment]
Sounds like your script is being run before the frameworks are copied. Make sure to move the strip frameworks script last in the list of scripts to run.

**Comment by mastohhh** [comment]
It's the last one.

Does Cocoapods needs to know if it's en embedded framework ?

**Comment by jensutbult** [comment]
What does your Podfile look like?

**Comment by mastohhh** [comment]
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

pod 'iZettleSDK',                   '~> 1.3.0'
```

**Comment by jensutbult** [comment]
And what happens if you create a new project from scratch and add the iZettleSDK pod?

**Comment by mastohhh** [comment]
Do you use `use_frameworks!` in your Podfile ?

When I try with it, some other pods don't work, so I don't know if this is the solution...

**Comment by mastohhh** [comment]
Do you plan to add a Carthage version ?

When I try with Carthage : here's the error 

```
*** Cloning sdk-ios
*** Checking out sdk-ios at "1.3.0"
*** Skipped building sdk-ios due to the error:
Dependency "sdk-ios" has no shared framework schemes
```

**Comment by jeremangnr** [comment]
Using CocoaPods 0.37.2 I had to manually add the frameworks as "Embedded Binaries" in the "General" tab of my target:

![screen shot 2016-09-23 at 12 34 30 pm](https://cloud.githubusercontent.com/assets/1508415/18791769/60af96e2-818a-11e6-8911-925804c15394.png)

**Comment by jensutbult** [comment]
I've verified it with version 1.0.1 of cocoapods and my current Podfile looks like this:

```
platform :ios, '8.0'

target 'iZettle SDK Test' do
	pod 'iZettleSDK'	
end

```

I suggest you upgrade cocoapods and then try again.

**Comment by mastohhh** [comment]
Ok, my cocoapods version was outdated !

When I try with 1.0.1, some other pods causes problems, so I don't know if this is the fix.

I'm now installing iZettle Framework manually, thanks for your help.
