### ISSUE TITLE
safari asks for confirmation before opening in iOS >= 9 before opening izettle

### ISSUE THREAD

**Issue by thomaskien** [iZettle/sdk-ios#92]
Hey,

we use iZettle since several years now for payment in connection to our self-made webapp-payment-system in php/mysql for use in our office.

to start the payment-process we open a page with a header containing:

<META HTTP-EQUIV=\"refresh\" CONTENT=\"1;URL=izettle://api/payment/charge?enforcedUserAccount=...

and to start the payment process and the parameters x-failure and x-success to report. That works quite well.

Starting with iOS 9 Safari now asks for confirmation before opening iZettle.

Is there a way to avoid that? We do not want to stay with iOS 8 forever ...

A websearch shows a possible connection with some LSApplicationQueriesSchemes to be defined in iZettle-APP itself.

Regards,

Thomas

**Comment by mattiasjahnke** [comment]
Hi @thomaskien the URL-scheme has been deprecated for almost a year now - we do not offer any support for it and it might stop working in future releases of the iZettle app.

If you want to keep using your web solution, we suggest you build a simple native iOS app that integrates with the native iZettleSDK (this repository) and expose a URL scheme in that app for your web solution to call.

**Comment by thomaskien** [comment]
Thanks for your reply matthias!

I see, please don't switch of that legacy-feature too soon! ;-)) 
The creation of a tiny app indeed sounds like the best way for us to go.

Regards,

Thomas
