### ISSUE TITLE
com.apple.private.externalaccessory.showallaccessories entitlement

### ISSUE THREAD

**Issue by szysz3** [iZettle/sdk-ios#93]
Hi!

There's a problem with entitlement on ios 10.0+:

`Sample[447:44525] Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement`

adding Wireless Accessory Configuration and External Accessory Communication does not help.

**Comment by mattiasjahnke** [comment]
Hi!
Try adding this entry in your plist

Key:
"Privacy - Bluetooth Peripheral Usage Description" (that's `NSBluetoothPeripheralUsageDescription`)

Value:
"Connect card readers and other accessories."

That should take care of the problem. We'll in the meantime investigate and update our documentation accordingly.

**Comment by sgermain06** [comment]
This doesn't solve the issue. I still get the same error.

**Comment by flipbosch** [comment]
Yes we have the same issue. We tried many possible solutions mentioned on the internet with: ""com.apple.private.externalaccessory.showallaccessories" entitlement" but without any luck. 

Also tried updating to iZettleSDK 1.3.1. 

Hope there is an fix, since multiple users experience crashes now on 10.x

**Comment by mattdouhan** [comment]
Any news on this, we have the same issue and its a showstopper

**Comment by mattiasjahnke** [comment]
Hey, I believe we see the same warning but we haven't experienced any problems while submitting to app store. Do you have problems submitting?

**Comment by mattdouhan** [comment]
I can submit to iTunes connect not tried to real App Store 

But the device don't work for me either 

M

**Comment by Sajjon** [comment]
There is a thread about this at [Apple forum](https://forums.developer.apple.com/thread/61646)
