### ISSUE TITLE
Payment processing start point

### ISSUE THREAD

**Issue by unkempt** [iZettle/sdk-ios#94]
Hi, not really an issue, more like advice :) I really need some help?? (please)

I'm using this function to get the izettle ready for a payment to be read. It calls "_updateLastPaymentToolbar" when complete, but I need to call a function when the card payment starts processing... i.e when the app starts showing the processing animation, is this possible???

- (void)initCharge {
    _lastReference = [self _uniqueReference];
    NSDecimalNumber *amount = [[NSDecimalNumber alloc] initWithString:@"1.00"];
    [[iZettleSDK shared] chargeAmount:amount currency:nil reference:_lastReference presentFromViewController:self completion:^(iZettleSDKPaymentInfo *paymentInfo, NSError *error) {
        _lastPaymentInfo = paymentInfo;
        _lastError = error;
        _timestamp = [NSDate date];
        
        [self _updateLastPaymentToolbar];
    }];
}

I hope you can help
Thanks
Rich

**Comment by mattiasjahnke** [comment]
Hey @unkempt 

Since iZettle will take over the entire screen during the payment flow, I'm not sure what you'd like to update. As you point out, you'll be called when the payment is complete, and you can update your UI.

We do not have support for listening in on the payment process, sorry.

**Comment by unkempt** [comment]
We're creating a digital installation/experience and want the user to know they are waiting for the payment to process to finish. It's an automated system and the user will not interact with a shop assistant or be seeing the payment screen. 

Any ideas?

**Comment by mattdouhan** [comment]
but iZettle takes over the entire screen so even if you could listen in on the payment process updating the UI is useless as it won't be seen anyway, and the iZettle card reader will give the update to the user since they have to insert the card into the device it seems logical.
