### ISSUE TITLE
Refund Issue

### ISSUE THREAD

**Issue by stephengilroy** [iZettle/sdk-ios#95]
After completing a test transaction on the external demo account, we are trying to refund that transaction but are receiving this error message: "Refund error: Insufficient funds in your iZettle account".

Is there anything we can do to fix this?

**Comment by adeemotu** [comment]
externaldemo account is set to be auto-reverted, which means this will periodically (30-60 min) reverse transactions

**Comment by stephengilroy** [comment]
Is this auto-revert a new feature? We've been able to refund transactions in the past?

**Comment by mattdouhan** [comment]
Is it possible to refund partial amounts? and also does the customer need to present the card for a refund or it can be done without the card being present as long as we know the transaction number?

**Comment by mattiasjahnke** [comment]
@mattdouhan Yes, `1.4.0` introduces partial refunds. The customer does not have to present the card, but the user will have to enter the password on the account.

**Comment by mattdouhan** [comment]
Hi

You mean the store staff need to enter the password on the izettle account ?

M

**Comment by mattiasjahnke** [comment]
@mattdouhan yes, that is correct

**Comment by mattdouhan** [comment]
Ok thanks, really not ideal, it would be great if we could fix the password in the app just as we can fix the username to make the staff experience more transparent, in high traffic situations we don't want to bother staff with entering passwords all the time.

**Comment by patwhitehead1** [comment]
We're still having the same issue with the auto-reverted funds (I'm on the same development team as stephengilroy). It appears that the funds are reverted immediately, so we can never successfully complete a refund. Can we disable this?

**Comment by mansbernhardt** [comment]
@patwhitehead1 Please do the refund testing with an account not having auto-reverting on (that is, not a test account).

**Comment by patwhitehead1** [comment]
Thanks @mansbernhardt, so we should sign up for our own account (for testing purposes)?

**Comment by iabdullin** [comment]
Working on this integration as well. Weird that it is not possible to test refunds and we need to somehow to obtain live accounts... Previously refunds worked fine on test account

**Comment by TomasPro** [comment]
@patwhitehead1 apologies for the troubles - we do plan to address the problem with partials not being usable/testable with demo accounts but unfortunately we have no ETA for it to be reelased. For the time being I would like to ask you to create a production "private individual" account through website  (in case you dont have one already). Please email sdk@izettle.com in case you need assistance and/or in case your development team is located in country outside of our existing markets.
